Kruptein/PlanarAlly

- CHANGELOG.md
- PlanarAlly/static/css/planarally.css
- PlanarAlly/static/css/rooms.css
- PlanarAlly/templates/planarally.jinja2
- PlanarAlly/templates/rooms.jinja2
This pull request adds a new exit button at the bottom of the menu and it takes the user back to their rooms. A new logout button was also added to the rooms page that uses the existing logout function on the server side. I was not quite sure about the placement of the logout button but I think it looks fine now and I also added a placeholder button that in the future can be used to alter account settings like changing passwords.
> Exit and logout button

- PlanarAlly/static/css/planarally.css
This is the same style as the toolbar and other menus in the room.
Signed-off-by: Jakob Sinclair <sinclair.jakob@mailbox.org>
> Improve look of context menu

- CHANGELOG.md
- ts_src/assetManager/assets.ts
Similar to https://github.com/Kruptein/PlanarAlly/pull/76 but for the Asset Manager.
This one just needs setData() to be called, but I can't set it to null it seems.
> Fix error dragging assets in Asset Manager in Firefox

- CHANGELOG.md
- PlanarAlly/static/css/planarally.css
If the asset or note accordion were empty they were to small for the icons. This PR fixes that issue:
Signed-off-by: Jakob Sinclair <sinclair.jakob@mailbox.org>
> Fix empty note and asset accordion being too small

- client/src/game/store.ts
This PR changes the zoom value that is used to sync with the server from the display value to the actual used value.
Additionally a bug is fixed whereby the locationOptions were passed as undefined due to shenanigans with vuex-module-decorator
> Use zoomFactor instead of zoomDisplay to sync Fixes #176

- client/src/game/geom.ts
Change the Point class and its subclasses to use `this` for its common methods.
This allows us to remove all overloads that just did typecasting AND more importantly also fixes a bug where these overloaded methods were typed fine in TS but actually became normal points in JS.
> Improve Point inheritance

- CHANGELOG.md
- client/src/game/layers/layer.ts
- client/src/game/shapes/shape.ts
This PR adds Shape.drawSelection and refactors Layer.draw to use that method instead.
This opens up possibilities for shape specific selection implementations.
> Refactor Layer.draw to use Shape.drawSelection

- CHANGELOG.md
- client/src/game/layers/layer.ts
This PR closes issue #175 and hides all shapes on the fow layer regardless of their vision blocking setting (while not on the FOW layer).
> Hide ALL shapes on FOW layer

- CHANGELOG.md
- server/api/socket/shape.py
This PR fixes a longer standing issue with shape movements.
During mouse movements the shape data returned to clients contained some private fields like auras/trackers/labels etc that should have been cleared before transmission.
> Fix private shape auras, trackers, labels and name being revealed during movement.

- CHANGELOG.md
- client/src/game/events/keyboard.ts
Resets the viewport of the client back to 0,0
> Recover from "scrolling away" from the map

- client/src/game/ui/floors.vue
This PR fixes issue #225.
The remove icon is no longer visible if only one floor exists and the actual method invocation will also return early.
> Prevent last floor from being removable

- server/api/socket/__init__.py
This PR fixes issue #224 .
Since the introduction of floors there has been a bug in the server which prevented the gridsize from being adjusted.
This might also address issue #221 which is also related to a bug with grid sizes.
> Fix gridsize not settable

- server/models/signals.py
This PR fixes issue #221.
Upon creating a new floor, a new gridlayer is instantiated with the default values instead of checking if there is another gridlayer with differing grid size.
> Fix girdlayer creation not taking existing gridsize into account

- CHANGELOG.md
- client/src/game/events/keyboard.ts
- client/src/game/layers/manager.ts
Up until now there was one set of convenience keybindings related to floors: Page Up/Down, which would change the camera one floor up or down.
This PR adds the ability to move selected shapes by using ctrl + Page Up/Down without moving the camera and by using ctrl + shift + Page Up/Down which also moves the camera.
A small implementation change also means that Page Up/Down is now processed on key down and no longer on key up as it was previously
> Add more keybinding options for floor movement

- CHANGELOG.md
- client/src/game/ui/annotation.ts
This PR fixes a stupid bug that has been in the codebase for a while; Changing location would stop the annotation manager from working.
> Fix broken annotations on location change. Fixes #156

- client/src/game/manager.ts
- client/src/game/shapes/utils.ts
- client/src/game/store.ts
- client/src/game/visibility/te/draw.ts
- client/src/game/visibility/te/iterative.ts
- client/src/game/visibility/te/te.ts
Since the addition of floors, `getlayer` has been readjusted to require a floor name as the first parameter.  This apparently has not been properly fixed everywhere.
This PR fixes some found issues, most prominently is the shapeUpdate when a redraw is required.
> Fix uses of getLayer without floor name

- client/src/game/shapes/asset.ts
- client/src/game/shapes/shape.ts
AssetRects (i.e. shapes from your asset menu and not hand drawn with the draw tool) ignored stroke/fill colours as it is useless for their rendering.
It is however useful for badges.  This change makes it that the assetrect colours are also properly synced.
It also changes the default colour for assetrects strokeColour to white.
> Fix assetrect colour sync

- CHANGELOG.md
- Dockerfiles/server_config_docker.cfg
- server/app.py
- server/server_config.cfg
As requested in #257 this PR adds a configuration option to the server config to set the origins allowed for CORS.
> Add configuration option for CORS origins.

- CHANGELOG.md
- client/src/game/geom.ts
- client/src/game/shapes/polygon.ts
- client/src/game/shapes/shape.ts
The detection to see if a polygon line was selected did not take the line width into account which makes it pretty difficult to select if the two points are grid aligned.
This solves part of issue #262
> bugfix(Polygon): Take line width into account for selection detection

- CHANGELOG.md
- client/src/game/ui/tools/draw.vue
- client/src/game/ui/tools/select.vue
WIth the introduction of draw and resize snapping in the latest release, some complaints came in of uses where the snapping would actually work against the DM.
This PR introduces the alt modifier that while pressed disables the snapping feature just like the grid snapping.
> feature(Draw): disable snapping with alt modifier

- CHANGELOG.md
- client/src/game/api/events.ts
- client/src/game/comm/types/general.ts
- client/src/game/store.ts
- client/src/game/ui/menu/menu.vue
- client/src/game/ui/tools/draw.vue
- client/src/game/ui/tools/select.vue
- client/src/game/utils.ts
- server/api/socket/__init__.py
- server/models/user.py
- server/save.py
This PR adds a new client option to set the behaviour of the alt modifier.
This modifier by default disables snapping while pressed.  The new user option inverts this and by default does not snap unless alt is pressed.
> feat(Snapping): add client option to invert alt behaviour

- CHANGELOG.md
- client/src/game/ui/menu/asset_node.vue
- client/src/game/ui/menu/menu.vue
This PR adds a simple search bar to the sidemenu in the asset panel.
It does a simple .includes check to determine whether it matches, so no fancy regex or such for now.
All folders with subitems that do not match the search are hidden.
> feat(asset): Add search bar to in-game asset menu

- CHANGELOG.md
- server/config.py
This adds a secondary but more important config file in data dir. Any option set in that file override settings from previous files. This file can contain only a handful of options. All other will be taken from base config file.
> Add tiered config file

- .circleci/config.yml
- client/vue.config.js
The release files so far provided either consisted of a windows exe build which can be ran straight away or of two archives that github creates that reflect the repository itself.
The repository no longer stores the js artifacts and thus the latter two archives cannot be ran straight away but need to have the js artifacts built first.
This PR adds a circle CI pipeline that creates a tarball and a zip archive with prebuilt js artifacts so that the server can be ran straight away.
> feature(prebuilt-artifacts): Provide binary artifacts for all platforms

- CHANGELOG.md
- client/package-lock.json
- client/src/core/types.ts
- client/src/game/api/events.ts
- client/src/game/api/events/access.ts
- client/src/game/comm/types/shapes.ts
- client/src/game/events/keyboard.ts
- client/src/game/layers/fow.ts
- client/src/game/layers/layer.ts
- client/src/game/shapes/owners.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/utils.ts
- client/src/game/ui/initiative/initiative.vue
- client/src/game/ui/selection/edit_dialog.vue
- client/src/game/ui/selection/edit_dialog/access.vue
- client/src/game/ui/selection/edit_dialog/dialog.vue
- client/src/game/ui/selection/selection_info.vue
- client/src/game/ui/tools/createtoken_modal.vue
- client/src/game/ui/tools/draw.vue
- client/src/game/ui/tools/ping.ts
- client/src/game/ui/tools/ruler.ts
- client/src/game/ui/tools/select.vue
- server/api/socket/shape.py
- server/api/socket/shape/__init__.py
- server/api/socket/shape/access.py
- server/models/shape.py
- server/save.py
This PR improves various aspects of the shape access system.
It now shows a dropdown instead of a text field to select users in the session. This prevents accidental typos and just overall annoyance with adding access.
Additionally there is also the possibility to give someone vision access but not edit access.  Edit access here entails every kind of interaction with the shape.  And vision access is limited to just giving vision of the token's lightsources.
There now also is a default setting to choose behaviour for those players not specified.
> feature(Shape): Improved user access permissions

- CHANGELOG.md
- client/src/game/layers/fow.ts
- client/src/game/layers/fowplayers.ts
- client/src/game/layers/layer.ts
- client/src/game/layers/manager.ts
On window resize all canvas elements are automatically readjusted.  The lighting and vision systems however use a virtual canvas for some off screen drawing which was not being adjusted and could cause strange walls appearing.
> bugfix(Lighting): Window resizes could mess with lighting boundaries

- CHANGELOG.md
- client/src/game/layers/utils.ts
- client/src/game/shapes/baserect.ts
- client/src/game/shapes/circle.ts
- client/src/game/shapes/shape.ts
- client/src/game/ui/tools/draw.vue
- client/src/game/ui/tools/select.vue
- client/src/game/units.ts
- client/src/game/visibility/te/draw.ts
You can now use the ctrl modifier to retain aspect ratio during resize operations.
Note that the ctrl modifier is also used to add more elements to your selection.  The former only triggers when resizing.
Also in this PR due to some changes to resizing in general:
* Improvements to general resizing: only snap resize the point being resized
* Improvements to drawing: snap start and endpoints to grid
> feature(Resize): shape resizing can now retain aspect ratio

- CHANGELOG.md
- client/src/game/ui/tools/map.vue
As a result of the maptool resize, the map could sometimes jump to unexpected places.
This PR changes it so that the center of the chosen resize rectangle will remain in the exact same place after the resize.  This should result in less jarring resizes.
> bugfix(MapTool): sudden map jumps

- client/src/game/ui/menu/asset_node.vue
Fix the asset list search in-game to be case insensitive.  Closes #296
> bugfix(AssetList): case insensitive search

- Dockerfile
Added requirements to install with apt-get install which are required to build successfully on raspbian.
Solves issue #308
> Satisfy requirements for building docker on rapsbian

- CHANGELOG.md
- server/api/socket/asset_manager.py
Relatively simple two line change to enable the server to actually delete files. Folders and Files that are removed by the Asset Manager call the same `Asset.Remove` endpoint, so it is necessary to check if the asset being removed is a file or folder. Folders aren't created on the server, so checking for the file_hash's existence is sufficient to protect against errors which arise from trying to delete non-existent assets on the server.
I've briefly tested this and confirmed that I can add and remove assets and their asset files indeed are removed from the server disk.
> Delete server files removed with asset manager

- client/src/game/events/keyboard.ts
Make sure to clear previous selection boxes when changing floors in all cases.
This closes #332
> bug(Floor): Always clear selection upon floor change

- CHANGELOG.md
- client/src/game/store.ts
- client/src/game/ui/tools/draw.vue
Fix the draw brush tool not resetting upon floor change.  This closes #335 .
Incidentally this also fixes the brush not appearing until mousemove when changing layers.
> bug(Draw): Reset the draw tool on floor change

- CHANGELOG.md
- client/src/game/api/events.ts
- client/src/game/comm/types/settings.ts
- server/models/campaign.py
When rejoining/reloading/reconnecting a session you no longer get put on the lowest floor, but on the floor you last visited.
This closes #334
> bug(Floor): Remember active floor upon rejoining

- server/api/socket/shape/access.py
The code responsible for changing just one of the two access rights, was not using a proper method to check permission, which resulted in the DM not being able to change these settings.
> bug(Ownership): Fix specific edit/access right changing not working

- CHANGELOG.md
- client/src/game/api/events.ts
In most circumstances the players that have edit access to a shape will want to follow the shape moving floors.  This closes #336
> feat(Floor): Move players with edit access if shape changes floor

- client/src/game/ui/menu/locations.vue
During the development somehow accidentally a line got commented and as a result moving all players didn't actually do much anymore
> fix(Location): Moving all players not doing anything

- CHANGELOG.md
- client/src/game/events/keyboard.ts
- client/src/game/ui/tools/select.vue
- client/src/game/ui/tools/utils.ts
This PR changes the behaviour of the collision check to include an optional shrink parameter.
When this paramter is set to true, the provided shape will be shrunk by 3/4th before checking for collision.  This allows shapes to go through doors/hallways that are slightly smaller than the shape itself.
Vision is calculated from the center, so at no point the vision should be impacted.
> feat(Movement): Fit shapes through doors/paths slightly smaller

- CHANGELOG.md
- client/src/game/api/events.ts
- client/src/game/events/keyboard.ts
- client/src/game/layers/utils.ts
- client/src/game/store.ts
- client/src/game/ui/floors.vue
When changing floors the intent is that on reconnect the player is automatically put on that floor again.  This was bugged for players.
> bugfix(Floor): Player active floor not memorised

- CHANGELOG.md
- client/src/game/api/events.ts
- client/src/game/api/events/shape.ts
- client/src/game/comm/types/shapes.ts
- client/src/game/layers/layer.ts
- client/src/game/shapes/shape.ts
- client/src/game/ui/selection/edit_dialog/dialog.vue
- client/src/game/ui/tools/select.vue
- server/api/socket/shape/__init__.py
- server/api/socket/shape/options.py
- server/models/shape/__init__.py
- server/save.py
This PR introduces a toggle in the shape dialog to mark a shape as invisible.
When invisible a shape is only visible for players with edit_access.  Do note that public auras are still visible for all players as an invisible creature with a torch would still shed light.
This closes #318
> feat(Shape): invisible shapes

- CHANGELOG.md
- client/src/game/ui/tools/ruler.ts
Add 1 decimal point to the ruler output.
This provides more clarity and also works better when using a unit size that uses floats.
> bug(Ruler): Add 1 decimal point to the ruler

- CHANGELOG.md
- client/src/game/ui/settings/GridSettings.vue
On firefox the input field for the grid unit size would show a red border when providing a floating point number.  These numbers are in fact allowed and accepted, but the UI was not aware.
This closes #312
> bugfix(Settings): fix firefox showing invalid input for floating point grid sizes

- CHANGELOG.md
- client/src/game/ui/initiative/initiative.vue
- client/src/game/ui/initiative/store.ts
In most cases initiative is changed when the DM calls for initiative.  Which means that most players will be interacting with the initiatives at the same time.
When you change a value causing a reorder, it could lead to other player still editing losing their changes.
This PR addresses that problem by delaying changes from other players when you're editing an initiative, only updating them when you release focus on the input field.
> bug(Initiative): Improve simultaneous inputs

- CHANGELOG.md
- server/api/socket/initiative.py
There was an ownership check that would always fail for players.
> bug(Initiative): Players not being able to update effects

- CHANGELOG.md
- client/src/game/api/events.ts
- client/src/game/layers/utils.ts
- server/api/socket/floor.py
When reloading there was a possibility that you reset to the map layer instead of the layer you previously had active.
Additionally when creating a new floor it will no longer move everyone to it immediately.
> bug(Layer): Fix active layer sometimes resetting on reload

- CHANGELOG.md
- client/src/game/store.ts
- client/src/game/ui/settings/dm/AdminSettings.vue
The DM was listed in the player list in the admin DM settings and thus could be kicked.  This is no longer the case.
This fixes #356
> bug(DmSettings): Fix DM no longer being able to kick themselves

- CHANGELOG.md
- client/src/game/events/keyboard.ts
- client/src/game/ui/tools/map.vue
- client/src/game/ui/tools/select.vue
- client/src/game/ui/tools/tool.vue
- client/src/game/ui/tools/tools.vue
- client/src/game/ui/tools/utils.ts
This PR introduces the concept of 'Tool Mode'.  The toolbar will now show a different set of tools based on the active mode.  There is a build and a play mode that can be toggled from in the toolbar as well as with the TAB key.
The intent is to make the toolbar a bit less cluttered with different tools that are not all needed during play as well as provide a way to deal with some other annoyances.
For example in play mode you will no longer be able to resize shapes.  This is an uncommon action during play and often leads to frustration when you intend to move a token but accidentally resize it.  You can at all times swap to build mode and do a resize if you desire.
> feat(ToolMode): Build/Play mode

- CHANGELOG.md
- client/src/game/ui/floors.vue
It was impossible to draw/select something in the area right of the layer bar due to a faulty pointer css rule
> bug(UI): Fix area right of layer selector preventing draw/select

- server/api/socket/initiative.py
Removal of initiative values either through the dialog or by removing a shape was broken since a small initiative rework earlier in the release cycle.
> bug(Initiative): Removal not working properly

- CHANGELOG.md
- client/src/game/ui/menu/locations.vue
On firefox when the location bar does not fit the screen, the scrollbar would not be displayed in the location bar, but instead be displayed on the entire page at all times.
This closes #364
> bug(Scrollbar): Fix firefox scrollbar issue

- CHANGELOG.md
- client/src/game/shapes/circulartoken.ts
When basic tokens are created their name will default to 'Unknown shape' like all other shapes.  With the basic tokens we have however a more suitable default which is the label given during the creation of the token.
This will now be used as the default.  This closes #384
> feat(BasicToken): Set the default name to their label

- CHANGELOG.md
- client/src/App.vue
Use `overscroll-behavior` to disable overscroll refresh feature that Android Chrome implemented.
While using touch screen device, playing and using pan to move, if scroling down, most likely it'll trigger refresh and make it very hard to play on Android Chrome.
Related to #324, and this simple fix is to improve the touch screen experience.
> Contain body to disable pull refresh

- client/src/locales/en.json
Campaign and session have been used interchangeably throughout the UI whereas it should almost always be campaign.
This closes #400
> bug(Terms): Replace session with campaign in translation strings

- CHANGELOG.md
- client/src/game/ui/floors.vue
- client/src/game/ui/selection/shapecontext.vue
This PR removes the delete and add actions in the floor selector for players as well as remove the option to move a shape to a different floor/layer/location.
> bug(UI): Remove a couple of DM only interactions from the player UI

- CHANGELOG.md
- client/src/game/ui/initiative/initiative.vue
This PR adds a hover text with the name of the shape when you move your mouse over an initiative shape image.
Closes #388
> feat(Initiative): Show shape name on hover for images

- Dockerfile
Fix #413 
As Dockerfile reference: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
> Using LABEL instruction instead

- CHANGELOG.md
- client/src/auth/login.vue
- client/src/core/components/languageDropdown.vue
- client/src/game/ui/menu/menu.vue
- client/src/i18n.ts
- client/src/locales/de.json
- client/src/locales/en.json
- client/src/locales/zh.json
`client/src/core/components/languageDropdown.vue` implements a dropdown selection for language switching.
It hard-coded supported languages and I do think it's acceptable for the current use case since the translation file is webpacked.
Maybe it needs a better UI/UX, but I'm not good at this.
After language selected, it will call localStorage API and stores the locale info for next time loading such as refreshing.
> [FEAT] I18n language selection UI and store locale

- client/src/locales/de.json
The German locale had leftover english text in one of the fields, and two translations were switched.
> Removed english in German locale and fixed switched translations

- CHANGELOG.md
- client/src/game/ui/tools/draw.vue
Polygon points now also respect grid snapping as all other shapes do during draw.
This PR closes #425
> feat(Draw): Polygon now respects grid snapping

- CHANGELOG.md
- client/src/game/shapes/circle.ts
- client/src/game/shapes/circulartoken.ts
- client/src/game/shapes/line.ts
- client/src/game/shapes/polygon.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/text.ts
Implemented visibleInCanvas for CircularTokens, thus fixing the bug where auras would not be displayed when the source token is out of frame #427
> Fixed visibleInCanvas to support aura

- CHANGELOG.md
- client/src/game/ui/menu/locations.vue
- client/src/game/ui/ui.vue
When the left sidemenu is open a horizontal bar appears if there are more locations than can fit the horizontal axis.  This is due to firefox misbehaving on overflow in a grid context.
This was partially fixed in the past but didn't address the left menu potentially being open this is now resolved and fixes #437
> bug(Firefox): Fix firefox location scroll when menu open

- CHANGELOG.md
- client/src/game/comm/types/shapes.ts
- client/src/game/geom.ts
- client/src/game/input/keyboard.ts
- client/src/game/layers/fow.ts
- client/src/game/layers/layer.ts
- client/src/game/layers/manager.ts
- client/src/game/layers/utils.ts
- client/src/game/manager.ts
- client/src/game/shapes/asset.ts
- client/src/game/shapes/baserect.ts
- client/src/game/shapes/boundingrect.ts
- client/src/game/shapes/circle.ts
- client/src/game/shapes/circulartoken.ts
- client/src/game/shapes/line.ts
- client/src/game/shapes/polygon.ts
- client/src/game/shapes/rect.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/text.ts
- client/src/game/shapes/utils.ts
- client/src/game/store.ts
- client/src/game/ui/annotation.ts
- client/src/game/ui/selection/shapecontext.vue
- client/src/game/ui/tools/map.vue
- client/src/game/ui/tools/select.vue
- client/src/game/ui/tools/tool.vue
- client/src/game/ui/tools/tools.vue
- client/src/game/utils.ts
- server/models/shape/__init__.py
- server/save.py
This PR adds support for rotation.
This includes rotation of individual shapes as well as groups.  Rotation is only possible in build mode to prevent UI clutter.
Currently the rotation UI is already visible, the actual rotation still has to be done.
> feat(Rotation): Add rotation support

- CHANGELOG.md
- server/planarserver.py
To (further) prevent bug-reports like #434 or #218 the server now provides a helpful error-message, pointing towards the tutorial.
Tested on Linux; not sure whether concatenation in line 10 actually should be done with '/' instead of '+' (does os.isdir() support that?) to support Windows denoting directories with backslash, though.
> Gh 434 warning

- client/src/game/layers/manager.ts
Players entered the map layer instead of the token layer, so they could not operate their tokens.
This PR fixes it by changing the default layer index from 0 (the map layer) to 2 (the token layer).
*Needs further investigation.*
> bug(Layer): Fix setLayerIndex by setting to 2 (token layer)

- server/api/socket/shape/__init__.py
Moving a shape would properly sync across clients, but would never actually persist in the database and thus reset on reload.
This closes #464
> bug(Shape): Fix shape position update not persisting

- client/src/game/shapes/shape.ts
Some UI elements were using the wrong matrix transformation for their rendering.  This fixes #465
> bugfix(UI): Fix some UI elements not rendering correctly

- CHANGELOG.md
- client/src/game/api/events.ts
- client/src/game/api/events/location.ts
- client/src/game/comm/types/settings.ts
- client/src/game/input/keyboard.ts
- client/src/game/layers/grid.ts
- client/src/game/layers/utils.ts
- client/src/game/settings.ts
- client/src/game/shapes/baserect.ts
- client/src/game/shapes/circle.ts
- client/src/game/store.ts
- client/src/game/ui/menu/menu.vue
- client/src/game/ui/settings/GridSettings.vue
- client/src/game/ui/tools/map.vue
- client/src/game/ui/tools/ruler.vue
- client/src/game/units.ts
- client/src/locales/de.json
- client/src/locales/dk.json
- client/src/locales/en.json
- client/src/locales/es.json
- client/src/locales/ru.json
- client/src/locales/zh.json
- server/api/socket/__init__.py
- server/api/socket/location.py
- server/models/campaign.py
- server/models/user.py
- server/save.py
The grid size (i.e. #pixels 1 grid cell takes) was a DM setting, but this is ultimately better suited as a client setting.  Different users have different computer screens, might be using a projector etc, which all call for different sizes.
This closes #460
> feat(Settings): Make grid size a client setting

- CHANGELOG.md
- client/src/game/ui/tools/tools.vue
In some cases mouseleave would not be triggered (e.g. alt tabbing), which caused some shapes to remain on screen (e.g. rulers).
This might solve some of the issues in #278
> bug(UI): Fix mouseleave not always triggering

- client/src/game/input/keyboard.ts
- client/src/game/shapes/baserect.ts
- client/src/game/shapes/circle.ts
- client/src/game/units.ts
- `snapToGrid`/`resizeToGrid` used grid size in client options instead of default grid size (50), make it snap incorrectly.
- arrow keys moving shapes used client set grid size too.
This PR fixed these two incorrect behaviors by changing to `DEFAULT_GRID_SIZE` from `gameStore`.
> Fix snap to grid and keyboard move

- CHANGELOG.md
- client/src/game/ui/tools/map.vue
#311 reproducible after PR #451 event-improvements.
Make map tool call `Shape.Update` in `apply()` might fix this.
*Needs further investigation*
> bug(Map): Fix map resize not replicate

- CHANGELOG.md
- client/src/game/shapes/baserect.ts
- client/src/game/shapes/boundingrect.ts
- client/src/game/shapes/polygon.ts
- client/src/game/shapes/shape.ts
- client/src/game/ui/tools/select.vue
- client/src/game/utils.ts
- server/models/shape/__init__.py
- server/save.py
It came to my attention last week that resizing/rescaling rotated shapes was fundamentally broken.
This PR fixes #476 as well as some other issues with rotated shapes:
- hit detection was done on the unrotated shape
- bounding box was not always shown correctly
- angles were stored as integers in the database which invalidated a whole set of angles.
> bugfix(Rotation): Fix resizing of rotated shapes and some other rotation issues

- client/src/game/ui/tools/pan.ts
This PR fixes a bug introduced to a recent change to tool behaviour when the screen loses focus.  The pan tool was left behind with a small inconsistency compared to the other tools.  This fixes #488
> Bug(Pan): Fix wrong behaviour when the mouse leaves the screen

- CHANGELOG.md
- server/api/socket/shape/__init__.py
When moving a shape to a different location, the shape was still available on the old location until a refresh of that location for each player.  This also affected some other things with that shape like initiative being broken.
This is now resolved and fixes #493 .
> bug(Location): Fix shape not disappearing on location move

- CHANGELOG.md
- client/src/game/api/events/floor.ts
- client/src/game/layers/store.ts
- client/src/game/ui/floors.vue
- client/src/game/ui/tools/select.vue
- client/tests/unit/game/visibility/te/pa.test.ts
- server/api/socket/floor.py
This PR adds the possibility to reorder floors by simply dragging them around.
This closes #463 .
> feat(Floor): Allow floor reordering

- CHANGELOG.md
- client/src/game/layers/utils.ts
- server/scripts/remove_faulty_images.py
Asset drops on the game board that are not images located in /static are no longer accepted
-   This fixes the possible spam of "could not load image /game/..." in your console for future cases
-   A script has been added in the server/scripts folder to remove existing assets
> bug(Board): Restrict asset drop to /static images

- CHANGELOG.md
- client/src/game/layers/layer.ts
This PR adds the ability to remove spawn tokens.  In the past this would cause issues, but now there are proper dialogs in place to inform if a location does not have spawn information.
> feat(SpawnLocation): Allow spawn token removal

- client/src/game/api/events/location.ts
- client/src/game/comm/types/settings.ts
- client/src/game/settings.ts
- client/src/game/ui/selection/shapecontext.vue
- client/src/game/ui/settings/GridSettings.vue
- client/src/game/ui/settings/VariaSettings.vue
- client/src/game/ui/settings/VisionSettings.vue
- client/src/game/ui/settings/dm/DmSettings.vue
- client/src/game/ui/settings/location/LocationSettings.vue
- client/src/locales/en.json
- server/models/campaign.py
- server/save.py
This adds a new DM/location setting that when enabled will automatically move a player along with a token if they own a token and the token is being moved to another location/spawn.
The setting will be enabled by default.
This closes #444.
> feat(Location): Move tokens on location change

- client/src/game/shapes/shape.ts
This fixes a bug introduced in a recent dev change that prevents new auras from persisting to the database.
> bug(Aura): Fix new auras not persisting

- CHANGELOG.md
- client/src/game/ui/tools/select.vue
This fixes #504, where unlocking a shape using the quick selection info, would put the shape in drag mode.
> bug(UI): Fix unlocking shape starting drag mode

- CHANGELOG.md
- client/src/game/ui/tools/map.vue
This PR makes sure that input to the map tool is valid.
Only strictly positive numbers are now allowed.
This fixes #442
> bug(Map): Prevent some invalid inputs for map tool

- CHANGELOG.md
- client/src/game/layers/utils.ts
- client/src/game/ui/tools/ruler.vue
This PR adds snapping behaviour to the ruler.  It follows all snapping rulers in regards to activating (i.e. alt key to alter the behaviour in your client settings).
It can snap to all grid line crossings, grid cell centers and the middle between each set of grid crossings.
This closes #485
> feat(Ruler): Add snapping

- .gitignore
- CHANGELOG.md
- client/src/App.vue
- client/src/game/api/events.ts
- client/src/game/api/events/notification.ts
- client/src/notifications.ts
- client/src/router.ts
- server/api/http/__init__.py
- server/api/http/notifications.py
- server/app.py
- server/auth.py
- server/models/__init__.py
- server/models/general.py
- server/models/notifications.py
- server/planarserver.py
- server/requirements.txt
- server/routes.py
- server/save.py
- server/server_config.cfg
This PR adds the ability to create system notifications as requested in #453.
These notifications are shown as toasts in the topleft corner and will be fetched on normal http requests on any endpoint. Additionally when new messages are published, any client already in-game will also receive and display the notification instantly using the existing websockets.
When the user closes a notification, it is marked as read in localstorage and will no longer show up.
In order to manage these notifications a separate API server is launched next to the main server.  A new section has been created in the server_config to configure this to your liking. By default it will listen on 'localhost' instead of the default '0.0.0.0' that the main webserver has.
The admin API server currently consists of:
GET …
> feat(SystemNotifications): Implement system notifications

- client/src/game/shapes/template.ts
- client/src/game/shapes/variants/baserect.ts
This PR fixes two issues with templates.
1) The width and height was not correctly set when placing an asset on the board.
2) When selecting a default empty template the asset would not appear on the board properly.
> bug(Template): Fix size not persisting and default templates not always working

- CHANGELOG.md
- client/src/game/input/keyboard.ts
> bug(Lock): Fixed locking shapes via keyboard shortcut did not sync to the server

- CHANGELOG.md
- client/src/game/ui/floors.vue
> bug(UI): Fix floor rename always setting a blank name

- CHANGELOG.md
- client/src/game/input/keyboard.ts
This is a small quality of life improvement that opens the shape edit dialog when one shape is selected. This closes #550
> feat(UI): Add Enter to open edit dialog

- CHANGELOG.md
- client/src/game/ui/tools/ruler.vue
> bug(UI): Remember ruler visibility state between tool changes

- CHANGELOG.md
- client/src/game/api/emits/initiative.ts
- client/src/game/ui/initiative/initiative.vue
- client/src/locales/en.json
- server/api/socket/initiative.py
This helps the confusion surrounding effects removal (which only triggered upon reaching 0 automatically) as well as the option to remove non-numeric initiatives.
The original remove on 0 behaviour still exists as well.
This closes #390
> feat(Initiative): Added remove button to initiative effects

- CHANGELOG.md
- client/src/game/ui/initiative/initiative.vue
A bug in the initiative code prevented new effects from immediately synchronizing to other clients. They had to refresh their page to see them.
> bug(Initiative): New initiative effects do not immediately sync to other clients

- CHANGELOG.md
- client/src/game/shapes/shape.ts
- server/api/socket/shape/options.py
This fixes #385 where changing names of a shape would not always update the representation in the initiative list.
This also fixes a more general issue where updating a public name, those users that do not own the shape would not be informed of the change.
> bug(Shape) Fix name syncing issues

- CHANGELOG.md
- client/src/game/ui/selection/edit_dialog/ShapeSettings.vue
- client/src/game/ui/selection/edit_dialog/TrackerSettings.vue
> bug(Trackers): Fix trackers not providing empty rows until re-opening dialog

- CHANGELOG.md
- client/src/game/shapes/shape.ts
> bug(Trackers): Fix extra empty tracker rows when pasting

- CHANGELOG.md
- client/src/game/api/emits/shape/core.ts
Rectangles are defined as a reference point (topleft corner) with a certain width, height and angle. When resizing there are cases that the topleft corner moves and this was not handled properly resulting in the width and height to adjust correctly but the refpoint to remain the same causing a shift of the resized shape to the original refpoint.
This fixes #584
> bug(Resize): Fix rectangle resizing causing position shift

- CHANGELOG.md
- server/api/socket/location.py
When players disconnect, it's sometimes possible that a faulty sid is still associated with them and this goes wrong on location change.
> bug(Server): Fix location changes sometimes not going through for everyone

- CHANGELOG.md
- client/src/game/shapes/variants/baserect.ts
- client/src/game/units.ts
When resizing a rotated shape, snapping operations would produce wonky results.
This is now fixed and closes #595
> bug(Resizing): Fix snapping on rotated resize operations

- client/src/assetManager/contextMenu.vue
- client/src/assetManager/manager.vue
- client/src/core/components/modals/confirm.vue
- client/src/core/components/modals/modal.vue
- client/src/core/components/modals/prompt.vue
- client/src/game/Game.vue
- client/src/game/api/events.ts
- client/src/game/api/events/shape/options.ts
- client/src/game/layers/utils.ts
- client/src/game/shapes/template.ts
- client/src/game/ui/floors.vue
- client/src/game/ui/labels.vue
- client/src/game/ui/menu/locations.vue
- client/src/game/ui/menu/menu.vue
- client/src/game/ui/note.vue
- client/src/game/ui/selection/edit_dialog/ExtraSettings.vue
- client/src/game/ui/selection/selection_info.vue
- client/src/game/ui/selection/shapecontext.vue
- client/src/game/ui/settings/dm/AdminSettings.vue
- client/src/game/ui/settings/location/LocationAdminSettings.vue
- client/src/game/ui/tools/defaultcontext.vue
- client/src/game/ui/tools/draw.vue
- client/src/game/ui/tools/select.vue
- client/src/game/ui/tools/tool.vue
- client/src/game/ui/tools/tools.vue
- client/src/game/ui/ui.vue
- client/src/settings/account.vue
This is a change behind the scenes that gets rid of some $parent.$parent chains to reuse dialog components. Instead these components are now just created multiple times in the relevant place.
> feat(UI): Restructure reusable components

- CHANGELOG.md
- client/src/game/ui/tools/tools.vue
There was an area in the topcenter of the screen that under certain circumstances would prevent any mouse actions. This is now resolved.
> bug(UI): Fix dead area in topcenter of UI

- CHANGELOG.md
- client/src/game/shapes/shape.ts
When auras are toggled to become publicly visible, the other clients receive this event but do not properly configure the aura as a new vision source. This causes the aura to not actually be visible until a refresh in some cases.
> bug(Aura): Fix public aura sync issue

- CHANGELOG.md
- client/src/game/ui/tools/filter.vue
- client/src/game/ui/tools/pan.vue
- client/src/game/ui/tools/ping.vue
- client/src/game/ui/tools/ruler.vue
- client/src/game/ui/tools/select.vue
- client/src/game/ui/tools/tool.vue
- client/src/game/ui/tools/tools.vue
- client/src/game/ui/tools/vision.vue
This PR allows other tools to open the shape context menu as well.
This originally was only possible from within the select tool.
Two exceptions on this rule are the Draw and Map tools.
The former has its own use for the right click button and the latter should ideally only be open for the specific map operation.
Additionally the Vision and Filter tools are now able to perform most of the Select tool's features with the exception of rotating and resizing.
> feat(UI): Allow opening of shape context menu in other tools

- CHANGELOG.md
- client/src/game/geom.ts
- client/src/game/shapes/variants/boundingrect.ts
- client/src/game/ui/tools/select.vue
When making a selection, an algorithm runs to decide which shapes should be selected as a result.
This PR changes the algorithm used.  The new algorithm is accurate but does require more calculations.
This fixes things like selecting a region that falls in the bounding box of a polygon, but does not actually include the polygon itself like the following image:
It also coincidentally fixes a bug with selecting rotated shapes
> feat(Selection): Use accurate shape detection on shape select

- CHANGELOG.md
- client/src/game/layers/utils.ts
When dropping assets on the map, they sometimes would be autorescaled to 1 grid cell (or just empty when not using the grid).
This can be annoying for assets that you would prefer to keep in their original form (e.g. maps etc)
> bug(Assets): Don't rescale all assets to 1 grid cell on drop

- CHANGELOG.md
- client/src/game/ui/tools/ruler.vue
- client/src/game/ui/tools/select.vue
- client/src/game/ui/tools/tools.vue
- client/src/game/ui/tools/utils.ts
When moving shapes around and seeing if you have enough movement to get somewhere, you often need to swap between select and ruler.  There now is an optional toggle on the select tool to show a ruler while moving shapes.
This also supports the multi ruler feature merged earlier with (space)
> feat(Select): Add direct ruler support

- CHANGELOG.md
- client/src/game/ui/tools/draw.vue
- client/src/game/ui/tools/filter.vue
- client/src/game/ui/tools/map.vue
- client/src/game/ui/tools/ruler.vue
- client/src/game/ui/tools/select.vue
- client/src/game/ui/tools/tool.vue
- client/src/game/ui/tools/tools.vue
- client/src/game/ui/tools/vision.vue
When changing mode the helper UI for some tools would not move and point to a different tool or an empty area on the map
> bug(UI): Fix toolbar helpers UI location on mode change

- CHANGELOG.md
- client/src/game/shapes/variants/baserect.ts
Another bugfix that addresses selection of rotated shapes, this time not in a groupselect context
> bug(Selection): Fix selection of rotated rectangles and assets

- CHANGELOG.md
- client/src/game/api/emits/client.ts
- client/src/game/api/events/client.ts
- client/src/game/store.ts
- client/src/game/ui/tools/map.vue
- client/src/game/units.ts
- client/src/game/utils.ts
As reported in #621 there is an issue with the size of auras when using a modified gridsize.
While fixing this I did some more thorough checks and encountered a couple of other places that were not using the correct math to handle modified gridsizes. In particular the map tool would also wrongly scale items and the zoom function would be off when loading a map resulting in a wrong location being shown.
This fixes #621
> bug(Grid): Fix various issues with modified client gridsizes

- CHANGELOG.md
- client/src/game/api/emits/location.ts
- client/src/game/api/events.ts
- client/src/game/ui/selection/shapecontext.vue
- server/api/socket/location.py
When the DM moves tokens to a spawn point, it will only change the location but not explicitly set the position to be centered on.
This is now fixed and more user friendly.
> bug(Spawn): Set location x/y position on spawn teleport

- CHANGELOG.md
- server/api/socket/initiative.py
Under certain conditions, tokens that changed location would not be able to get any initiative assigned to them
> bug(Initiative): Fix initiative sometimes not working on location change

- CHANGELOG.md
- server/api/socket/shape/options.py
This closes #636. When toggling the name visibility it would not immediately sync the active name value or "?" to other clients.
> bug(UI): Fix shape name not syncing immediately on visibility toggle

- CHANGELOG.md
- client/src/game/api/events/shape/core.ts
- client/src/game/input/keyboard.ts
- client/src/game/layers/fowlighting.ts
- client/src/game/layers/layer.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/utils.ts
- client/src/game/ui/initiative/initiative.vue
- client/src/game/ui/selection/shapecontext.vue
- client/src/game/ui/tools/select.vue
When you control multiple shapes and use the vision tool or initiative vision lock, private auras of non-active shapes would still be visible. This is now resolved.
This closes #625
> bug(Vision): Fixes private auras of non-active shapes no longer showing up

- CHANGELOG.md
- client/src/game/Game.vue
- client/src/game/api/events/shape/core.ts
- client/src/game/input/keyboard.ts
- client/src/game/layers/layer.ts
- client/src/game/layers/utils.ts
- client/src/game/manager.ts
- client/src/game/operations/model.ts
- client/src/game/operations/movement.ts
- client/src/game/operations/operations.ts
- client/src/game/operations/resize.ts
- client/src/game/operations/rotation.ts
- client/src/game/operations/undo.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/utils.ts
- client/src/game/ui/tools/draw.vue
- client/src/game/ui/tools/select.vue
- client/tests/unit/game/visibility/te/pa.test.ts
This PR adds undo and redo support. (ctrl+z and shift+z).
Currently the number of remembered operations is hardcoded to 50.
This value might change or become configurable in the future.
To-do list:
This closese #66
> feat(Undo): Add undo and redo support

- client/src/game/shapes/shape.ts
This is a follow-up of an earlier PR #639 that addresses the same issue but also for default access permissions.
This closes #625
> bug(Vision): Fix vision tool private auras with default permissions

- CHANGELOG.md
- client/src/game/layers/fowlighting.ts
This fixes a bug where the minimal vision for tokens would be visible on all floors.
> bug(Vision): Fix minimal vision being applied to all floors

- CHANGELOG.md
- client/src/game/api/events.ts
- client/src/game/visibility/te/pa.ts
When creating a new floor, the initial triangulation was not called which caused any lighting related shape to break the floor until a refresh.
> bug(Floor/Vision) Fix floor triangulation not called for newly created floors

- CHANGELOG.md
- client/src/game/ui/selection/shapecontext.vue
When moving a shape to another location, all related users are moved with it.
This change was not reflected in the locations bar until a refresh.
> bug(UI): Update location bar user position when moving shape

- CHANGELOG.md
- client/src/game/ui/floors.vue
This PR closes #653 which showed that it's possible to create a floor with a name already in use, which would result in errors when interacting with this new floor.
> bug(Floor): Fix floor creation duplicate names

- CHANGELOG.md
- client/src/game/ui/tools/select.vue
When moving a shape into a wall, the shape and the mouse will no longer be in sync, which can give some unpleasant behaviour.
This closes #648
> bug(Select): Fix shape mouse snap desync

- CHANGELOG.md
- client/src/game/Game.vue
- client/src/game/api/events/client.ts
- client/src/game/comm/types/settings.ts
- client/src/game/store.ts
- client/src/game/ui/settings/client/BehaviourSettings.vue
- client/src/locales/en.json
- server/api/socket/__init__.py
- server/models/user.py
- server/save.py
This PR closes #578 and adds a new behavioural setting to the client settings to disable the ability to zoom when using the scroll wheel.
> feat(ClientSetting): Add disable scroll to zoom setting

- CHANGELOG.md
- client/src/game/shapes/template.ts
When dropping an asset with template info for width and/or height, they would not be rescaled when dealing with a non-default grid scale (e.g. 10ft per square)
This closes #629
> bug(Template): Fix template drops not rescaling to grid

- client/src/game/api/emits/client.ts
- client/src/game/api/events/client.ts
- client/src/game/comm/types/settings.ts
- server/api/socket/location.py
During load the location user options (last pan location + layer/floor info) was not loaded correctly due to the change in client settings types recently introduced
> bug(Load): Fix location user options not being set correctly on load

- CHANGELOG.md
- client/src/game/layers/layer.ts
- client/src/game/ui/tools/draw.vue
- client/src/locales/en.json
This adds a new mode to the draw tool for DMs.
When operating in erase mode you can draw shapes as usual which will make everything below them on their floor transparent. 
Just as shapes drawn in reveal or hide mode appear automatically on the 'fow' layer, shapes drawn with this tool will appear automatically on the 'map' layer, although nothing prevents you from moving it to another layer.
These shapes are selectable and actually follow the draw stack. So if you move a particular map asset to the top it will appear over the erased area, great for things like a wooden log that lays over a gaping hole for example!
Potential usecases:
- an explosion destroys a part of the floor and you want to show things on the floor below
- you forgot to remove some part of an asset you uploaded and want …
> feat(Draw): Erase mode

- CHANGELOG.md
- client/src/dashboard/main.vue
- client/src/game/api/events.ts
- client/src/router.ts
Right now when a session is locked and you try to join as a player you just get redirected to the dashboard without much info.
> feat(UI): Show a small info popup when trying to join a locked session

- CHANGELOG.md
- client/src/game/api/emits/groups.ts
- client/src/game/groups.ts
- client/src/game/layers/utils.ts
- client/src/game/models/general.ts
- client/src/game/shapes/utils.ts
- server/models/campaign.py
This fixes a bug where sessions would be slow to load.
This was caused due to a regression introduced with the more complex grouping logic, that did an async callback to the server during the initial load. This in turn caused the normal layer loading to be halted until all grouping info was retrieved.
> bug(Startup): Fix long loading times

- client/package-lock.json
- client/package.json
- client/src/game/api/emits/shape/core.ts
- client/src/game/api/events/shape/core.ts
- client/src/game/shapes/shape.ts
- client/src/game/svg.ts
- client/src/game/ui/ActiveShapeStore.ts
- client/src/game/ui/selection/edit_dialog/ExtraSettings.vue
- client/src/game/visibility/te/pa.ts
- client/tests/unit/game/visibility/te/pa.test.ts
Setting up all the walls etc can be an arduous task.  To alleviate that work significantly there now is an option to upload an svg to use as a reference for the walls.
This can be accessed from the Extra settings panel when you've selected an asset.
Some considerations:
- The svg is expected to be somewhat simple, as in just a collection of `<path>` elements. Any styling/scripting/other stuff is not supported and the behaviour of such an svg is undefined when used. (the svg is just scraped for its path info and not used otherwise)
- For obvious reasons, how smaller the svg, the better the performance will be in PA.
- Remove everything that should not be a wall (room numbers, doors, stairs, other furnishing, text etc) This is just meant as a wall mask on top of your regular asset.
It's …
> feat(Vision): Use svg mask to draw vision lines

- CHANGELOG.md
- client/src/game/models/ddraft.ts
- client/src/game/shapes/template.ts
- client/src/game/ui/selection/edit_dialog/ExtraSettings.vue
- server/api/socket/asset_manager/__init__.py
- server/api/socket/asset_manager/common.py
- server/api/socket/asset_manager/ddraft.py
This PR adds support for dungeondraft's dd2vtt format.
When dropping such an asset on the board, an extra option will appear in the asset's extra settings to 'apply' the ddraft features.
It's done in this way for now, as there is no current concept of shapes belonging to eachother, so when you resize/refit your asset to the map, the walls would not follow if they were applied immediately. (expect changes here in the future).
This closes #677
> feat(Assets): Support dd2vtt assets

- CHANGELOG.md
- client/src/game/shapes/variants/togglecomposite.ts
Due to a bug there was always a minimal area visible for tokens that have variant information even though the player did not own the shape.
> bug(Variant): Fix minimal vision over non-owned variant shapes

- CHANGELOG.md
- client/src/game/api/emits/shape/options.ts
- client/src/game/api/events/shape/options.ts
- client/src/game/input/keyboard.ts
- client/src/game/models/shapes.ts
- client/src/game/models/templates.ts
- client/src/game/shapes/shape.ts
- client/src/game/ui/ActiveShapeStore.ts
- client/src/game/ui/selection/edit_dialog/PropertySettings.vue
- client/src/locales/en.json
- server/api/socket/shape/data_models.py
- server/api/socket/shape/options.py
- server/models/shape/__init__.py
- server/save.py
This commit allows you to mark assets as defeated which draws a red cross through them.
This state can be toggled using the 'is defeated' checkbox in the object properties or by selecting the asset and pressing 'x'.
Make sure to do your PR on the `dev` branch and NOT on the `master` branch.  This repo uses gitflow which only uses the master branch as a release branch.
Make sure to update the `CHANGELOG`.
> Add defeated indicator to tokens

- CHANGELOG.md
- client/src/game/shapes/variants/circle.ts
- client/src/game/ui/tools/ping.vue
Just like the ruler received changes, the ping tool now also has a fixed size that is decoupled from the zoom scale.
This greatly increases clarity when certain players are zoomed out, where the ping tool would appear very small.
> feature(Ping): Make size constant irregardless of zoom level

- server/planarserver.py
I noticed the url to the self hosting tutorial wasn't working when I was setting up my development environment. I've updated it to point to the correct page.
> Updated self hosting tutorial URL

- CHANGELOG.md
- client/src/assetManager/AssetManager.vue
This change causes the websocket used to upload files to wait for an ack before sending the next slice of the file.
I've tested with large sets of tokens known to cause the upload to fail previously as well as large files and with this change they are uploaded with no issues. Uploads are slightly slower now but not significantly so.
> Fix upload bug

- CHANGELOG.md
- client/src/game/ui/initiative/initiative.vue
This PR fixes a bug where a modal would appear for all players when a group initiative token is deleted.
This modal now only appears when initiated from the initiative UI itself
> bug(Initiative): Fix global group initiative removal popup

- CHANGELOG.md
- client/src/game/layers/manager.ts
When using floors, light/vision sources on higher floors would not be updated when panning (and other operations). This could be abused to see into rooms not intended and just gives an odd vibe.
This does sadly remove part of an optimisation that was in place with multi floor rendering, but this can't be helped.
> bug(Vision): Fix multi-floor static vision

- CHANGELOG.md
- client/src/assetManager/AssetManager.vue
- client/src/core/utils.ts
- client/src/game/api/events.ts
- client/src/game/input/keyboard.ts
- client/src/game/layers/store.ts
- client/src/game/layers/utils.ts
- client/src/game/manager.ts
- client/src/game/store.ts
- client/src/game/ui/initiative/initiative.vue
- client/src/game/ui/selection/edit_dialog/GroupSettings.vue
- client/src/game/ui/tools/DrawTool.vue
- client/src/game/ui/tools/SelectTool.vue
- client/src/game/utils.ts
When reordering floors, they would not be rendered correctly until a refresh.
> bug(Floor): Fix reorder wrong render until refresh

- CHANGELOG.md
- server/server_config.cfg
having an empty configuration value can be confusing, it's better to comment it to show it is optional
> by default, comment public_name config option

- client/src/game/ui/menu/MenuBar.vue
- client/src/locales/de.json
- client/src/locales/dk.json
- client/src/locales/en.json
- client/src/locales/es.json
- client/src/locales/it.json
- client/src/locales/ru.json
- client/src/locales/tw.json
- client/src/locales/zh.json
This closes #714
I changed DM 'options' to 'settings' as well to add to conformity. Changes were not only to the i18n strings but also to source to be consistent.
Not sure whether this is important enough to be mentioned within the changelog. Only pro I'd see for this would be to have an alert for translators, but translations themselves do not necessarily follow the conflict in English. So it might also be simply changed and that's it. There's still `git blame`. :)
> i18n: client/dm options to settings

- CHANGELOG.md
- Dockerfile
Removed unused packages used for building server on ARM, that are no longer needed.
This cleans around 100MB in uncompressed image.
> Docker image cleaning

- CHANGELOG.md
- client/src/game/ui/menu/MenuBar.vue
- server/api/socket/asset_manager/__init__.py
This PR finally changes the asset-menubar behaviour in-game to be updated when a change is done to the asset manager, so you no longer have to refresh the page!
> feat(Menu): Live update asset menu on asset-manager changes

- client/src/store/activeShape.ts
This PR fixes a bug where it was always required to first fully deselect a shape and then select a new shape.
> bug(Selection): Changing selection directly from one shape to another not working properly

- CHANGELOG.md
- Dockerfile
This PR should make possible to build docker image on ARM machine. Changes are only in BUILDER, so final image size is the same as before.
I tested it on Raspberry PI 4B running Raspbian buster.
> Docker image building on ARM

- CHANGELOG.md
- client/src/game/Game.vue
- client/src/game/layers/canvas.ts
- client/src/game/layers/variants/fow.ts
- client/src/game/layers/variants/fowLighting.ts
- client/src/game/layers/variants/fowVision.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/shapes/shape.ts
- client/src/store/floor.ts
This PR adds proper support for devices with a `window.devicePixelRatio` that differs from the default 1.
This should render sharper images on those devices.
> feat(Rendering): Add support for HiDPI/retina screens

- client/src/core/components/ColourPicker.vue
This PR fixes a bug where changing the hue was not possible if the saturation was 0
> bug(ColourPicker): Add a fallback hue value when saturation is 0

- client/src/game/input/keyboard.ts
This PR fixes the tab key skipping over some steps that should happen when changing tool mode.
This affected things like the rotation UI not appearing immediately
> bug(ToolMode): Fix <tab> skipping some tool mode change steps

- CHANGELOG.md
- client/src/game/api/events/client.ts
- client/src/game/layers/canvas.ts
- client/src/game/models/settings.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/variants/circularToken.ts
- client/src/game/ui/settings/client/AppearanceSettings.vue
- client/src/game/ui/settings/client/ClientSettings.vue
- client/src/game/ui/settings/client/DisplaySettings.vue
- client/src/game/ui/settings/client/categories.ts
- client/src/locales/de.json
- client/src/locales/dk.json
- client/src/locales/en.json
- client/src/locales/es.json
- client/src/locales/it.json
- client/src/locales/ru.json
- client/src/locales/tw.json
- client/src/locales/zh.json
- client/src/store/client.ts
- server/api/socket/__init__.py
- server/models/user.py
- server/save.py
This PR adds an optional feature to define the grid size in terms of mini dimensions and pixel density (PPI).
This is interesting for those players that would like to use real minis on top of a tablet running PlanarAlly.
When enabled, this will disable the zoom tool (i.e. changing zoom does nothing).
> feat(Grid): Define grid in physical terms (mini size + PPI)

- client/src/dashboard/AccountSettings.vue
- client/src/dashboard/Dashboard.vue
- client/src/dashboard/types.ts
This PR fixes #747 
The account settings are now integrated in the more recent dashboard redesign and already provide room for other entries in the navigation sidebar for future extra setting pages (user settings, admin settings etc)
> bug(UI): Reinstantiate account settings

- server/api/socket/initiative.py
The recent initiative changes, broke something in initiative initialisation for new locations created. This is now rectified.
> bug(Initiative) Fix initiative on new locations

- client/src/game/ui/initiative/Initiative.vue
This PR fixes the initiative window showing a type error if any of the shapes in the list is unknown to the viewer.
This can occur because
- The shape actually no longer exists (e.g. it was removed)
- The shape is moved to the DM Layer
In the first case everyone sees the error, in the latter only the players
> bug(Initiative): Fix type error when a unknown shape is in the list

- CHANGELOG.md
- client/src/game/api/emits/shape/circularToken.ts
- client/src/game/api/emits/shape/core.ts
- client/src/game/api/emits/shape/text.ts
- client/src/game/api/events.ts
- client/src/game/api/events/shape/circularToken.ts
- client/src/game/api/events/shape/core.ts
- client/src/game/api/events/shape/text.ts
- client/src/game/shapes/variants/circularToken.ts
- client/src/game/shapes/variants/text.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/ui/initiative/state.ts
- client/src/game/ui/settings/shape/PropertySettings.vue
- server/api/socket/shape/__init__.py
The Circular token (basic token) and text objects their text value cannot be changed after creation. This PR changes this and adds an extra "value" field to the property settings of these shapes.
This fixes #715
> feat(Shape): Add editable text value for circulartoken and text

- CHANGELOG.md
- client/src/game/ui/settings/location/GridSettings.vue
This prevents the possibility of setting the unit size of the grid to be smaller than 1, which causes multiple drawing errors.
This fixes #776
> bug(Grid): Prevent unitSize < 1

- CHANGELOG.md
- client/src/game/ui/settings/dm/AdminSettings.vue
- client/src/store/game.ts
- server/api/socket/player.py
- server/api/socket/room.py
This PR fixes #712, and prevents Co-DMs from downgrading the DM's role or kicking them.
> bug(DM-Settings): Prevent Co-DM removing main DM

- .gitignore
- CHANGELOG.md
- client/src/game/layers/floor.ts
- client/src/game/layers/variants/map.ts
- client/src/game/models/floor.ts
- client/src/game/ui/settings/FloorSettings.vue
- client/src/game/ui/settings/floor/PatternSettings.vue
- client/src/game/ui/settings/location/FloorSettings.vue
- client/src/store/floor.ts
- client/src/store/settings.ts
This PR goes further upon the recent background color feature for floors and adds support for repeating background tiles.
An image can be selected from the assets and an offset/scale can be provided to adjust the exact positioning.
Most things have been done, it's just a matter of adding the floor pattern UI to the location settings.
Additionally this PR also fixes a couple of small things:
- Don't apply a mask so that you can pan around during the location settings
- Immediately trigger a rerender when changing background settings
- Fix inconsistency in displayed background type in the floor details
(This closes #522)
> feat(Floor): Tileable floor backgrounds

- CHANGELOG.md
- client/src/game/ui/tools/Tools.vue
This PR changes the toolbar UI slightly to more prominently show the active toolmode as well as all other modes available.
> feat(UI): Improve active tool mode clarity

- CHANGELOG.md
- server/api/socket/location.py
This PR fixes a bug with the notes section in-game disappearing when changing locations
> bug(Notes): Fix notes disappearing on location change

- CHANGELOG.md
- client/src/game/ui/tools/Tools.vue
This PR tries to address some of the feedback on the recent toolbar change.
In particular the issue described in #807 that it is difficult to discern the active tool-mode on some screens.
The active tool-mode will now be a larger font size and have an underline, whereas all non active modes will be italic
> bug(Toolbar): Make active tool-mode more distinct

- CHANGELOG.md
- client/src/game/layers/variants/fowVision.ts
- client/src/game/ui/settings/location/VisionSettings.vue
This addresses the two problems mentioned in #797.
- Fix vision when min range == max range
- Prevent setting the min range > max range through the UI
> bug(Vision) Fix vision range setting conflicts

- CHANGELOG.md
- client/src/game/draw.ts
- client/src/game/layers/variants/fowLighting.ts
This PR fixes #795, when using an aura that only covers a specific angle, it would not rotate along with the shape
> bug(Aura): Fix angled auras not rotating with shape

- CHANGELOG.md
- client/src/game/ui/Annotation.vue
- client/src/game/ui/contextmenu/ShapeContext.vue
- client/src/game/ui/settings/shape/TrackerSettings.vue
- client/src/game/ui/tools/Tools.vue
This PR fixes 2 places where FF styles differently compared to chromium.
- Annotation bar was always full width on ff
- Aura UI Was way to wide
> bug(UI): Firefox styling some elements undesireable

- CHANGELOG.md
- client/src/game/api/emits/dice.ts
- client/src/game/api/events.ts
- client/src/game/api/events/dice.ts
- client/src/game/models/dice.ts
- client/src/game/tools/variants/dice.ts
- client/src/game/ui/UI.vue
- client/src/game/ui/tools/DiceTool.vue
- server/api/socket/__init__.py
- server/api/socket/dice.py
This PR adds a couple of things:
- Adds a toggle to disable auto-rolling
- Adds a toggle to share results with all players (otherwise only with DMs)
When dice are rolled the result is shared to either all players or only dms and they will receive a notification in the top right corner, informing them who rolled and what the result was.
These rolls are also added to the dice history in the dice tool and on hover shows which player a certain roll belongs to.
_I want to re-iterate that the dice tool UI is not final, and more a rough proof of concept atm._
> feat(Dice): Share results

- CHANGELOG.md
- client/src/game/layers/variants/layer.ts
- client/src/game/tools/variants/select.ts
- client/src/game/vision/state.ts
Apparently experimental mode had some glaring issues that prevented it from working at all since the big vue3 refactor.
This has been rectified, additionally a bug has been fixed where the movement triangulation was not updated if you don't use snapping.
> bug(Vision): Fix experimental mode

- CHANGELOG.md
- client/src/core/geometry.ts
- client/src/game/client.ts
- client/src/game/draw.ts
- client/src/game/layers/variants/fowLighting.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/models/shapes.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/variants/asset.ts
- client/src/game/svg.ts
- client/src/game/tools/variants/draw.ts
- client/src/game/tools/variants/map.ts
- client/src/game/tools/variants/ping.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/select.ts
- client/src/game/tools/variants/spell.ts
- client/src/game/ui/contextmenu/DefaultContext.vue
- client/src/game/ui/settings/shape/ExtraSettings.vue
- client/src/game/vision/state.ts
- client/src/store/floor.ts
This PR improves multiple aspects regarding the svg as wall map feature.
- scale and translate operations are taken into account
- parent <g> components are also taken into account (not only <path>)
- If a <path> is nested behind an unknown element (i.e. not <g> or <path>) it will be ignored currently!
- Simple bezier curves are handled better
- a polygon is now constructed to mimick the curve
- multi-point variants are not yet covered
The way svg data is tracked now is different compared to the old way and is more future proof.
In order to not ruin someones game I've left the old code in for now, but would like to deprecate this and urge everyone
who uses the svg feature, to reapply the svg to move to the new format. (this cannot be automated)
While we're here, I would like to re-iterate …
> feat(SVG): Multiple improvements

- server/api/http/rooms.py
- server/export/campaign.py
- server/models/campaign.py
- server/planarserver.py
- server/routes.py
- server/save.py
As the creator of a campaign you can export your campaign by going to `https://<servername>/api/rooms/<creatorname>/<campaignname>/export`.
This will download a json file to your local machine containing most information from the campaign (see status below).
This file can then be imported on another server by doing:
`python planarserver.py import --file=../path/to/campaign.json`
_All users will have a default password 'test' in the target server_
The current iteration is written with the prime purpose to make my life easier to debug user problems on servers they don't control. It is thus written with the idea to be imported in a completely clean db environment!
**NOTE** that behaviour on existing servers is undefined and should only be used **at your own risk**.
This PR only scratches the …
> feat(Export): Campaign export

- client/src/game/client.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/operations/movement.ts
- client/src/game/shapes/interfaces.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/variants/baseRect.ts
- client/src/game/shapes/variants/circle.ts
- client/src/game/shapes/variants/line.ts
- client/src/game/shapes/variants/polygon.ts
- client/src/game/shapes/variants/text.ts
- client/src/game/shapes/variants/toggleComposite.ts
- client/src/game/tools/variants/draw.ts
- client/src/game/tools/variants/select.ts
All shapes share a `get points()` function to reason about shape position on an abstract level.
This function was up until now calculated in place, which depending on the shape type could be expensive.
An earlier PR addressed this slightly by making sure the `.points` call would not be made multiple times in the same block.
This PR goes further and properly caches it, while this does mean that it does not have to be recalculated on the fly, this does mean that the cache needs to be invalidated when it no longer is correct. I tried to find all locations where cache invalidation should occur, but I might have missed some.
If selection boxes behave funky after some interaction, this is most likely the result of a stale cache, let me know!
> feat(Performance): Cache shape.points

- CHANGELOG.md
- client/src/game/api/events.ts
When the "Bring Players" actions was performed to move players to a different floor, on refresh the players would still be on the old floor due to an incorrect sync condition.
> bug(Sync): Fix "Bring Players" not saving new floor info for players

- CHANGELOG.md
- client/package-lock.json
- client/package.json
- client/src/auth/Login.vue
- client/src/game/tools/variants/draw.ts
- client/src/game/ui/tools/DrawTool.vue
- client/src/locales/en.json
- client/src/shims/swiper.d.ts
This PR splits up the draw tool UI in two separate "tabs".
Swapping between these tabs can be done with a new UI element in the bottomleft of the popover
The first tab presents basic options: shape and colour.
Nothing exotic here, the same shape specific options still appear here as well when for example selecting the polygon shape.
One noticeable improvement is that the colour selector now has an explicit header to show which selector does what. This was not always clear to users that don't interact with the colour selectors often.
The second tab presents more advanced vision related options.
The DM-only "vision mode" option has been moved to this tab as it is a very niche setting.
A new addition to the draw tool UI is the option to immediately configure the block options. When you draw …
> feat(Draw): Improve draw tool UI/UX

- CHANGELOG.md
- client/src/game/shapes/shape.ts
Whether or not the `isToken` property of a shape was marked, if the shape had default vision access, it would mistakenly be treated as a token for the minimal vision aura.
Fixes #822
> bug(Vision): Fix default vision token state

- CHANGELOG.md
- client/index.html
- client/src/auth/Login.vue
- server/api/http/auth.py
- server/routes.py
- server/server_config.cfg
This PR adds a new configuration field to the general section in the server config.
`allow_signups` defaults to true, and if set to false, will prevent users from signing up on the server.
This can be used to prevent unknown actors from joining a private server that is publicly facing.
This PR does not add alternative methods to add users as a server owner, that's for a later iteration.
> feat(Server): Add allow_signups config option

- CHANGELOG.md
- client/src/core/components/modals/Modal.vue
When resizing the screen it could occur that some modal is no longer visible due to it being out of the visible area. This PR changes the Modal behaviour to reposition on resize events if necessary
> bug(UI): Move modals on resize

- CHANGELOG.md
- client/src/assetManager/AssetManager.vue
- client/src/assetManager/socket.ts
- client/src/assetManager/state.ts
- server/api/socket/asset_manager/__init__.py
- server/api/socket/asset_manager/common.py
Adding folders via the asset manager was not supported due to browser API not being stable across all major browsers.
I get this request somewhat regularly and there nowadays is some API to do this, this is however a non-standard track API and I'll have to monitor it's progression closely as a result.
Nevertheless, this PR adds support for folders (simple or deeply nested) when dropping on the asset manager.
The upload button still only uploads files, because for some forsaken reason you can only choose either files or folders, but not both. But this feels like an ok trade-off.
This fixes #844
> feat(AssetManager): Added drop support for folders

- CHANGELOG.md
- server/api/socket/asset_manager/__init__.py
PA stores assets in a flat folder based on their hash to reduce unnecessary duplicate files if a certain file is added in multiple folders or by multiple people.
When removing a file from the asset manager, PA will check if the file is still in use in some other location and if not, removes it from the disk.
This last check was not properly done when removing folders, which this PR addresses.
> bug(AssetManager): Fix stale file cleanup for folders

- CHANGELOG.md
- client/src/game/Game.vue
In-game it was possible to have scroll bars visible due to the dice canvas not being sized strictly.
> bug(UI): Fix scroll bars visible

- CHANGELOG.md
- client/src/game/tools/variants/select.ts
When moving a shape on the token layer, intersections with walls and other movement blocking shapes are tested.  If you however move a movement-blocking shape itself, the original position was also being tested against.
> bug(Movement): Fix movement blocker intersections on token layer

- CHANGELOG.md
- Dockerfile
- client/src/App.vue
- client/src/core/socket.ts
- client/src/core/utils.ts
- client/src/game/temp.ts
- client/src/router.ts
- client/src/utils.ts
- server/app.py
- server/routes.py
This PR changes the way subpaths are handled.
In the past the subpath was handled by the server only and the client did some dark magic to figure things out and rewrite things on the fly.
With the recent-ish changes to the client side build system this no longer works and breaks things as pointed out to me recently on both github and discord.
To solve this, the client will now also properly take into account the PA_BASEPATH environment variable during build time.
An **important** change is that the basepath should now end with a slash. (e.g. `PA_BASEPATH='/subpath/')
This has a very important implication for people that user docker. You'll have to manually build your docker image as the build depends on the subpath.
You now have to pass `--build-arg PA_BASEPATH='/subpath/'` to the `docker …
> server(Subpath): Change subpath handling

- CHANGELOG.md
- client/src/core/components/ColourPicker.vue
The RGBA/HSLA/HEX fields were readonly, this is now fixed.
Closes #877
> bug(ColourPicker): Fix colour picker not accepting manual input

- client/src/game/id.ts
- client/src/game/systems/access/index.ts
- client/src/game/systems/auras/index.ts
- client/src/game/systems/index.ts
- client/src/game/systems/logic/door/index.ts
- client/src/game/systems/logic/tp/index.ts
- client/src/game/systems/trackers/index.ts
When removing a shape from a layer their `id` is dropped and the related systems have to be informed that any data they have might be stale.
> bug(Systems): Inform systems of id removal

- client/test/game/systems/auras/index.test.ts
One of the tests was failing due to some circular import shenanigans
> bug(Test): Fix circular import test

- CHANGELOG.md
- client/src/dashboard/AccountSettings.vue
When removing your account, the redirect to the login screen was not behaving properly.
> bug(Navigation): Fix account removal redirect not working

- client/src/game/models/initiative.ts
- client/src/game/ui/initiative/state.ts
Recently the concept of Global and Local ids was introduced and a mistake in the event types made it so that the initiative tool was using a global id thinking it was a local id, which doesn't work.
> bug(Initiative): Fix initiative not using the correct ids

- client/src/game/api/emits/initiative.ts
- client/src/game/ui/initiative/state.ts
The data the game sends to the server was using a local id, which has no meaning as soon as it leaves the client.
If you happen to have played around with initiative on a recent dev branch and have initiative entries you can't remove, use the following python script in the server folder to fix those:
```python
import json
from models import *
for initiative in Initiative.select():
data = json.loads(initiative.data)
modified = False
l = len(data)
for index, d in enumerate(data[::-1]):
if type(d["shape"]) != str:
data.pop(l - index - 1)
modified = True
if modified:
initiative.data = json.dumps(data)
initiative.save()
```
> bug(Initiative): Initiative data sent to server using local ids

- client/src/game/systems/auras/index.ts
- client/src/game/systems/trackers/index.ts
When creating new shapes adding trackers or auras was no longer possible until a refresh due to the shapes not being known to the tracker/aura systems, this is now resolved
> bug(Tracker): Fix tracker/aura init for new shapes

- client/src/game/api/events/shape/core.ts
- client/src/game/layers/variants/fowLighting.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/shapes/utils.ts
- client/src/game/shapes/variants/asset.ts
- client/src/game/shapes/variants/toggleComposite.ts
- client/src/game/tools/variants/draw.ts
- client/src/game/tools/variants/map.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/select.ts
- client/src/game/tools/variants/spell.ts
Using the spell tool was no longer possible since the global-local id changes due to a bug where the smarter shape re-use that spell tool does was not taken into account
> bug(Spell): Fix spell tool breaking screen

- CHANGELOG.md
- client/src/game/models/tools.ts
- client/src/game/tools/tool.ts
- client/src/game/tools/variants/draw.ts
- client/src/game/tools/variants/map.ts
- client/src/game/tools/variants/pan.ts
- client/src/game/tools/variants/ping.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/select.ts
While dragging a shape or point, sometimes the mouse would hover over the polygon edit UI icons and give funky behaviour.
Given that that UI cannot be used while moving, it is now hidden during this action.
> feat(Select): Hide polygon edit UI while moving

- client/src/core/geometry.ts
PA uses 'brands' to mimic nominal typing in typescript. For old types (i.e. GlobalPoint/LocalPoint) these brands were also present in the runtime variables. Newer types have moved to only specify brands during typing. This PR streamlines the Point types to also only specify brands on a type level.
All things considered this will probably have almost no noticeable impact, but it's a performance improvement without any downside anyway.
> feat(Performance): Remove brand types at runtime

- CHANGELOG.md
- client/src/core/components/RotationSlider.vue
The manual number input would update the client's direction, but not synchronise this change to the server. (The other direction input did sync correctly)
> bug(Aura): Fix aura direction input not syncing

- client/src/game/id.ts
With the Local/Global id system now in place, some potentially annoying bugs to find can be triggered by having id 0 be a valid id. This PR addresses this fact, by preventing this from ever happening.
> bug(Id): Prevent id 0 bugs

- CHANGELOG.md
- client/src/game/api/emits/initiative.ts
- client/src/game/api/emits/shape/core.ts
- client/src/game/api/emits/shape/toggleComposite.ts
- client/src/game/api/events.ts
- client/src/game/clear.ts
- client/src/game/id.ts
- client/src/game/systems/trackers/emits.ts
- client/src/game/ui/menu/MenuBar.vue
- client/src/game/vision/state.ts
- client/src/store/floor.ts
This PR fixes memory leaks related to changing/leaving a location.
Some things were not properly being cleared which means that memory was just sitting around no longer being used, but not being able to be garbage collected. Most noticeably the vision CDT information was not being cleared AND the floorId was not resetting to 0 which together meant that the vision information for all locations/sessions would stay in memory
> bug(Memory): Fix some memory leaks

- CHANGELOG.md
- client/src/game/api/events.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/utils.ts
- client/src/game/shapes/variants/asset.ts
- client/src/localStorageHelpers.ts
tl;dr at the bottom
When rendering user uploaded assets they can only be rendered once the image is actually downloaded by the browser, this is pretty obvious. PA would only draw these images once ready. This in itself is also pretty normal, but can actually cause some undesired behaviour when we add in floors.
Part of the render steps for floor based vision involves overlaying vision info from higher floors to allow light sources that come from up top through some hole.
If however the image that represents the upper area for that upper floor is not downloaded in time, it would just be transparent for the purpose of this thought exercise, which means that the light which is supposed to only come out of the small hole in the upper floor image, is now coming out from the entire ceiling.
So …
> bug(Rendering): Improve/Fix late image loading

- CHANGELOG.md
- server/api/socket/asset_manager/ddraft.py
When uploading ddraft files to the asset manager, the progress would become stuck. The file itself would still be uploaded to the server successfully though.
> bug(AssetManager): Fix ddraft uploads not progressing

- client/src/game/api/events/location.ts
- client/src/game/models/settings.ts
- client/src/store/settings.ts
Spawn locations were being sent by their local id to the server, which is meaningless.
This PR fixes this to send the proper global id to the server.
> bug(SpawnLocations): Fix spawn locations no longer saving properly

- CHANGELOG.md
- client/src/game/api/emits/asset.ts
- client/src/game/temp.ts
- server/api/socket/asset.py
This PR adds auto sizing of assets dropped on the map when the size can be inferred from the asset name.
The code looks for a sequence in the name matching YxY where Y is a number (can contain multiple digits). Some examples: 120x60, 30x50, 2x2.
The number will be interpreted as the number of grid cells it should occupy in the X and Y direction
This closes #906.
> feat(Assets): Auto infer asset dimension from name

- server/api/http/rooms.py
- server/config.py
- server/export/campaign.py
- server/models/asset.py
- server/models/campaign.py
- server/models/db.py
- server/models/label.py
- server/models/shape/__init__.py
- server/models/user.py
- server/planarserver.py
- server/save.py
- server/utils.py
There already was export/import code hidden in the codebase, but I wasn't really happy with it.
This is a redo and instead of exporting to a .json file, this exports a .sqlite file as well as the assets (which the previous version didn't do).
This combination is all you need to just run the campaign (together with the main server code of course), instead of having to import it again.
Importing in an existing server (i.e. adding to an existing save file) has not yet been written, and will be for another release. For this reason I will probably not promote it as a new thing in the release notes, but will just be a tool for me to help debug other people's saves.
_Also there were a bunch of things missing in the previous exporter I noticed_
> feat(Tooling): Add campaign exporter

- CHANGELOG.md
- server/export/campaign.py
When exporting a campaign, if some image in the campaign had a broken link to an asset it would fail.
This can happen if the campaign had images in play that were created before the asset-image link was added, or if something goes wrong with that link being created in the first place.
This might be cherry-picked if a fix release for 2022.1 would become necessary later down the line or otherwise will be scheduled for the regular next release.
> bug(Export): Fix campaign export - missing assets

- CHANGELOG.md
- server/export/campaign.py
LUO, short for LocationUserOptions, contains info on some user options specific to a location (e.g. zoom/pan/active layer etc).
This info was not properly being exported and when you open a save you would thus be reset to the default options.
> bug(Export): Fix LUO not exporting

- server/api/socket/location.py
- server/models/shape/__init__.py
With the recent export code being added, I revisited some of the older clone location code and found some things missing here. In particular shape access and location user options were not being copied.
Ultimately I should get rid of this code and merge it with the export code as it shares a lot of concepts and is just kinda duplicate atm in different styles.
> bug(Location): Fix clone location access/luo

- CHANGELOG.md
- client/src/game/api/emits/shape/options.ts
- client/src/game/api/events/shape/options.ts
- client/src/game/id.ts
- client/src/game/ui/settings/shape/ExtraSettings.vue
- client/src/store/activeShape.ts
- server/api/socket/shape/options.py
There were some logical bugs that could prevent attached svg (walls) information from being removed or new information from being uploaded.
Additionally this PR also fixes the extra settings UI to immediately update the svg state when uploading/removing, instead of having to close the settings and re-opening them.
> bug(Svg): Fix various svg related issues

- CHANGELOG.md
- client/src/game/systems/logic/tp/index.ts
When moving a shape to a position that happens to correlate with a tp zone on another floor, it would trigger.
This PR fixes that problem.
> bug(TpZone): Fix tp zones triggering on other floors

- CHANGELOG.md
- client/src/game/tools/variants/select.ts
When the redo operation was executed for a resize in which the relevant point was snapped, it would redo the resize to the non-snapped location at that time.
This is now fixed.
> bug(Redo): Fix resize redo for snapped point being off

- CHANGELOG.md
- client/src/assetManager/AssetManager.vue
- client/src/assetManager/socket.ts
When using the browser back/forward buttons (or some mouse/keyboard shortcuts for these actions), the Asset Manager would not properly update its UI.
This is now fixed.
> bug(AssetManager): Fix browser back/forward buttons not working

- CHANGELOG.md
- client/src/game/clear.ts
- client/src/game/client.ts
The DM Can optionally see the viewports of all connected clients and move them.
The rectangle representing such a viewport was not getting cleared when changing locations.
> bug(Client): Clear client viewports when changing location

- CHANGELOG.md
- client/src/game/ui/tools/DrawTool.vue
When returning to the dashboard from the game, the style of the navigation headers would be wrong. This has been rectified.
> bug(Dashboard): Fix dashboard nav header style

- CHANGELOG.md
- client/src/dashboard/SessionList.vue
The loading animation started when the route had been set. Depending on how fast the route changing happens, it could sometimes look like nothing is happening.
To remedy this, I'm showing the loading animation from the moment you click on launch.
> feat(UI): Show loading animation earlier

- .gitignore
- CHANGELOG.md
- Dockerfiles/server_config_docker.cfg
- server/api/socket/asset.py
- server/api/socket/asset_manager/__init__.py
- server/api/socket/connection.py
- server/api/socket/floor.py
- server/api/socket/groups.py
- server/api/socket/initiative.py
- server/api/socket/label.py
- server/api/socket/location.py
- server/api/socket/note.py
- server/api/socket/player.py
- server/api/socket/room.py
- server/api/socket/shape/__init__.py
- server/api/socket/shape/access.py
- server/api/socket/shape/utils.py
- server/logs.py
- server/models/shape/__init__.py
- server/planarserver.py
- server/routes.py
- server/server_config.cfg
- server/utils.py
The PA server outputs log info to both console and disk. This disk log was up to now never cleared/truncated by PA itself and thus relied on the server admin themselves to monitor the size of this file.
This PR adds log rotation in the form of Python's built-in [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler).
It can be configured in the server-config and defaults to 2kB files and 5 rotating backups.
> feat(Server): Add log rotation

- CHANGELOG.md
- server/api/http/rooms.py
- server/export/campaign.py
- server/models/campaign.py
- server/models/user.py
- server/routes.py
Further work on export internals.
The export all endpoint is `/api/rooms/<username>/export`.
The intention is to have UI to interact with all export related things in the future.
Bear in mind that this endpoint also packs all assets that you've uploaded, not just those that are linked to an active campaign.
> feat(Export): Add export all endpoint

- CHANGELOG.md
- client/src/core/components/modals/Modal.vue
- client/src/game/Game.vue
- client/src/game/ui/firefox.ts
Firefox does not properly implement the `dragEvent` handler. Reporting wrong clientX/clientY values in multiple cases.
A workaround has been found using the `drop` handler which does report the correct values.
> bug(UI): Fix modal handling on firefox

- CHANGELOG.md
- client/src/core/components/ColourPicker.vue
The saturation panel (the top part) of the color picker would sometimes reset to the red spectrum after changing the hue (the color slider).
In particular this happens if the hsv is set to 0,0,0. This PR fixes that case
> bug(ColorPicker): Fix saturation panel background sometimes reverting to red

- CHANGELOG.md
- client/src/game/tools/variants/draw.ts
When drawing shapes the draw tool will add the "shape creation" operation to the undo stack, so that you can ... undo that operation.
Before finalising a shape however the drawtool checks if the shape is valid. At the moment this means, checking if the shape has more than one point, because a single point usually refers to an accidental draw.
In this case the shape is cancelled, but the code was still trying to add this shape to the undo stack, which caused errors to appear in the console even though it didn't end up breaking anything.
> bug(DrawTool): Fix invalid shape undo errors

- CHANGELOG.md
- client/src/game/shapes/variants/polygon.ts
When adding a new point to a polygon, the new point would not be snappable by other shapes until a refresh.
Similar bugs were also fixed for removing a point and cutting polygons
> bug(SelectTool): Fix polygon edit UI operations not updating snap points

- CHANGELOG.md
- client/src/game/shapes/shape.ts
Shape badges now take the size of the shape into account instead of having a fixed size.
> feat(Badge): Render shape badges better

- CHANGELOG.md
- Dockerfile
The admin client was not being built in the Dockerfile, making it unusable.
> bug(Docker): Build admin client in docker

- CHANGELOG.md
- client/src/core/components/ColourPicker.vue
- client/src/core/components/store.ts
- client/src/game/api/emits/user.ts
- client/src/game/api/events.ts
- client/src/game/api/events/client.ts
- client/src/game/api/events/user.ts
- client/src/game/models/settings.ts
- server/src/api/socket/__init__.py
- server/src/api/socket/user.py
- server/src/models/user.py
- server/src/save.py
The colour picker will now remember the last 20 used colours on a per user basis (across all campaigns).
> feat(ColourPicker): Add colour memory

- CHANGELOG.md
- client/src/core/components/ColourPicker.vue
When using the saturation panel (the coloured rectangle on the top of the colour picker), the opacity would always be reset to 1.0, instead of keeping the current opacity.
> bug(ColourPicker): Fix hsv color input resetting opacity

- CHANGELOG.md
- client/src/game/ui/settings/shape/LogicPermissions.vue
For some reason a `null` value can sneak into the permissions object causing the logic permissions modal to show an error.
I've not yet identified the root source of this problem, but applied a bandaid fix so that the permissions modal does not error out.
> bug(Logic): Bandaid fix for null permissions

- CHANGELOG.md
- client/src/game/ui/menu/AssetNode.vue
- client/src/game/ui/menu/AssetParentNode.vue
This PR changes the rendering of the in-game asset list in the menu bar.
This reduces the amount of active event listeners that are running drastically (scaled directly with the amount of assets you have in your asset manager).
This will however not likely have any visual performance improvement.
> feat(Tech:AssetList): Change rendering

- server/requirements.txt
- server/src/app.py
I only now realised that jinja2 is still a dependency of the server, while that has no longer be needed for more than 3 years at least.
> chore(Tech:Dependencies): Remove jinja2 from codebase

- CHANGELOG.md
- client/src/dashboard/SessionList.vue
When leaving or deleting a campaign, a modal pops up asking for confirmation.
For some reason I decided in the past to not show the "No" option and only show the "yes" option.
I have no idea why, so "no" is back in town with this PR.
> feat(UI): Show no in leave room modal

- CHANGELOG.md
- server/src/api/socket/asset_manager/__init__.py
When communicating with the PA server, the client uses websockets (or socket.io to be specific).
The most used socket connection is the game socket, but there is also a dedicated socket for asset related stuff (e.g. asset manager, setting a campaign logo, ...).
This last connection was not cleaning itself up properly when closed. This is now done.
> bug(AssetManager): Cleanup asset socket connection data

- client/src/auth/Login.vue
Due to the documentation website (https://planarally.io) recently restructuring, the urls for the videos that play on the landing page no longer were correct.
> bug(LandingPage): Fix video urls

- client/src/core/socket.ts
- client/src/game/api/socket.ts
- client/test/setup.ts
The new dashboard socket seemingly messes with the game socket's query option manipulation.
This PR makes sure the game socket is using a completely separate manager.
> bug(Tech:Socket): Fix game socket query options not going through

- client/src/dashboard/Dashboard.vue
When an import completes the client will now move to the run section, which should then list the imported campaign among the other campaigns that you already run.
> feat(Import): Open the Run section when an import completes

- CHANGELOG.md
- client/src/game/operations/undo.ts
Undo or Redo operations related to movement or rotation would correctly update on the client and be synced to other players, BUT would not actually persist on the server, causing a reload to return to the original position.
> bug(Undo): Fix undo/redo not persisting for movement/rotation

- CHANGELOG.md
- server/src/models/campaign.py
- server/src/save.py
When joining a new Location, the default zoom level was set to 1.0, which is as zoomed out as it can go.
This meant the grid would just be very dense which is pretty unappealing, so I changed it to a more sensible value. (0.2)
> feat(Zoom): Change the default zoom level

- CHANGELOG.md
- client/src/assetManager/AssetManager.vue
It apparently hasn't been possible for a while now to move an asset in the asset manager to its parent folder by dropping it on the "..".
This fixes #969
> bug(AssetManager): Fix assets not being able to move up

- CHANGELOG.md
- server/src/models/shape/__init__.py
- server/src/save.py
When dropping shapes on the map they remember which asset they were made from.
When removing an asset that has a link to at least 1 such shape, an error would be thrown on the server, preventing the removal of the asset.
This fix now removes the link, allowing the asset to be removed.
Fixes #968
> bug(AssetManager): Fix asset removal not possible when linked to shape

- CHANGELOG.md
- client/src/game/ui/tools/DrawTool.vue
Since the addition of the door logic feature and especially its integration with the draw tool, drawing maps has been even easier (or at least for me :D).
One thing that however tends to happen is that maybe you've used the draw tool with door integration enabled 20 minutes ago, and you're about to draw something new, but forgot it was still configured as a door and thus end up drawing a bunch of doors.
To "fix" this, the logic tab will now light up with an orangered colour if door logic has been enabled, so that it should be noticeable if this was not desirable.
Similarly the vision tab will also light up if at least 1 of the two block properties has been toggled on.
> feat(DrawTool): Add reminder colour to draw tool tabs if active

- CHANGELOG.md
- client/src/game/tools/variants/vision.ts
- client/src/game/ui/tools/VisionTool.vue
The vision tool has an orangered background colour if not all vision is taken into account.
This alert state was correctly changing if the vision sources were changed from within the vision tool.
If however an external source changed the vision sources, the alert state would not change.
> bug(VisionTool): Fix vision tool alert state

- CHANGELOG.md
- client/src/game/Game.vue
- client/src/game/api/events/logic.ts
- client/src/game/input/keyboard/down.ts
- client/src/game/input/keyboard/up.ts
- client/src/game/shapes/shape.ts
- client/src/game/systems/logic/door/index.ts
- client/src/game/systems/logic/door/state.ts
- client/src/game/tools/tool.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/tools/variants/select/state.ts
- client/src/game/ui/settings/shape/LogicSettings.vue
- client/src/game/ui/tools/SelectTool.vue
- client/src/main.ts
- client/src/router/bootstrap.ts
- client/src/router/index.ts
This fixes #980.
When players had free access to toggle doors, the server was rejecting these changes because the player usually has no access to toggle the block properties.
It now behaves similarly to the Request mode where the request is routed through the DM invisibly, who does have permission.
> bug(Door): Fix player door interactions not persisting

- CHANGELOG.md
- client/src/game/systems/auras/index.ts
- client/src/game/systems/trackers/index.ts
- client/src/game/ui/settings/shape/TrackerSettings.vue
When removing a shared tracker or aura, the tracker would not be removed in the UI until a refresh of the game session.
> bug(Trackers): Fix shared tracker removal not immediately updating UI

- client/src/game/systems/access/index.ts
- client/src/game/systems/index.ts
A bug in my recent big refactor caused the access state to be dropped on a simple deselect, causing all kind of shenanigans, one of which was flagged by a user.
This fixes #991
> bug(Access): Fix access state dropping on deselect

- client/src/game/systems/client/index.ts
When trying to exit to the dashboard from a game session, the game is cleared.
The cleaning of client rectangles depended on the floor system still being loaded, which since recent refactors is no longer guaranteed to be the case.
As a fix the cleanup of the client rectangles will no longer actively be done, as they will be removed automatically when the floor system cleans up anyway.
> bug(Game): Fix exit to dashboard not always working

- client/src/game/floor/server.ts
- client/src/game/layers/variants/fow.ts
- client/src/game/layers/variants/fowLighting.ts
- client/src/game/layers/variants/fowVision.ts
- client/src/game/layers/variants/grid.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/rendering/core.ts
- client/src/game/systems/README.md
- client/src/game/systems/floors/index.ts
- client/src/game/systems/floors/state.ts
Some of the render internals were accessing floor state through reactive APIs, this PR adds a raw access lookup for performance critical paths.
Also a long overdue change was made to re-order the fow layers the moment they are added the first time, instead of doing some extra bookkeeping in the render loop.
> feat(Perf): Add raw floor state lookup for perf

- client/src/game/layers/variants/layer.ts
A check that hides FOW shapes unless you're on the FOW layer, was no longer working correctly, making the fow shapes also invisible while on the FOW layer.
> bug(FOW): Fix fow layer shapes being invisible

- CHANGELOG.md
- client/src/core/components/PluginContainer.vue
When a prompt modal appears and the value inserted was invalid, the actual error message was no longer visible.
> bug(Prompt): Fix prompt errors not being shown

- CHANGELOG.md
- client/src/game/systems/access/index.ts
- client/test/game/systems/access/index.test.ts
The idea of the vision tool is to toggle vision so that you only see what certain tokens can see.
As a DM this would however not toggle the private light auras of tokens you deselect.
You could go through the DM settings and activate 'fake player', but if you want to do a quick check that is a bit cumbersome.
Hence from now on, the vision tool will also hide private light auras from the DM if they have that token deselected in the vision tool.
> feat(VisionTool): Hide private light auras for DM

- client/src/store/settings.ts
This PR is related to #1001, in which I fixed the reset behaviour of location settings.
I did miss a bug with those settings that consist of multiple words behind the scenes (e.g. full fow), as these are cased differently on server and client. (server: snake_case, client: camelCase).
The client will now send the appropriate casing to the server.
> bug(Location): Fix location options reset sync event casing

- CHANGELOG.md
- client/src/assetManager/socket.ts
When using the subpath server setup, the AssetManager was automatically redirecting to a wrong path, in practice making the asset manager functionally useless.
This fixes #1006
> bug(AssetManager): Fix assetmanager when using subpath setup

- client/src/game/api/events.ts
- client/src/game/input/keyboard/down.ts
- client/src/game/layers/floor.ts
- client/src/game/layers/variants/fow.ts
- client/src/game/layers/variants/fowVision.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/rendering/core.ts
- client/src/game/shapes/utils.ts
- client/src/game/systems/README.md
- client/src/game/systems/floors/index.ts
- client/src/game/systems/state.ts
- client/src/game/ui/settings/FloorSettings.vue
- client/src/game/vision/state.ts
- client/src/store/client.ts
- client/src/store/settings.ts
The new unified state system had a small bug in it :D
The `.readonly` state was not properly updating, whereas all other states where properly updating.
This was due to unpacking the state together with the non-reactive state in a new object.
The non reactive properties will now be available as `.mutable` and `.readonly`, whereas the reactive properties will be available as `.reactive`, `.mutableReactive` and `.raw`. The raw view is readonly and no mutable direct view in the state is available in order to prevent subtle bugs due to skipping the reactivity system
> bug(State): Fix readonly state not properly updating

- CHANGELOG.md
- server/server_config.cfg
- server/src/api/socket/asset_manager/__init__.py
- server/src/api/socket/asset_manager/common.py
- server/src/api/socket/asset_manager/ddraft.py
- server/src/config.py
- server/src/routes.py
- server/src/utils.py
A new server config option has been added `General.assets_directory` this should be a path to the directory where the raw asset files should be stored/served.
> feat(Server:Assets): Add alternate assets location

- CHANGELOG.md
- client/src/game/api/events.ts
- client/src/game/clear.ts
- client/src/game/systems/index.ts
- client/src/game/systems/players/index.ts
- client/src/game/ui/menu/MenuBar.vue
- server/src/api/socket/location.py
The player system was being cleared on every location change.
This mostly impacted the DM causing among other things:
- the location bar to lose info on where players are
- the DM general info panel to lose which players are part of the campaign
A refresh would fix the issue, but this PR fixes it in general :)
> bug(System:Players): Fix player state clearing on location change

- client/src/game/api/events/client.ts
- client/src/game/input/keyboard/down.ts
- client/src/game/position.ts
- client/src/game/tools/variants/pan.ts
- client/src/store/client.ts
There were several separate functions for X and Y pan related options, which just causes a bunch of duplicate code for no reason.
Definitely because at this point in time there is not a single instance where only 1 of the 2 is modified.
> refactor: Unify pan functions

- client/src/core/conversions.ts
- client/src/game/api/emits/client.ts
- client/src/game/api/events.ts
- client/src/game/api/events/client.ts
- client/src/game/layers/variants/grid.ts
- client/src/game/layers/variants/map.ts
- client/src/game/position.ts
- client/src/game/shapes/variants/rect.ts
- client/src/game/tools/variants/pan.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/ui/UI.vue
- client/src/store/client.ts
Some aspects of the zoom information were being calculated in a reactive fashion, but were exclusively being used in a lot of the critical render loop, which touches no UI and thus was just wasting some cpu cycles.
> refactor: Move zoom things out of reactive state

- CHANGELOG.md
- client/src/game/api/emits/shape/core.ts
- client/src/game/ui/initiative/state.ts
- server/src/api/socket/initiative.py
- server/src/models/initiative.py
- server/src/save.py
- server/src/state/game.py
This PR covers a couple of fixes related to initiative.
A first set of fixes is related to making sure that bugs in the client code should have less chance to brick the initiative state. There is a bug somewhere that causes shapes that don't exist on the server to be added to the initiative list, which can cause a whole plethora of shenanigans.  The server will now reject any request that pertains a shape it doesn't know about.
A second set of fixes is related to bugs where the active initiative participant would change when this was not expected. This happened when for example a new shape was added to the initiative with an initiative higher than the current actor. Similar behaviour exists when changing the sort order.
This PR also updates the save_version, because it does a complete …
> bug(Initiative): Various fixes

- client/src/game/api/events/client.ts
- client/src/game/api/events/location.ts
- client/src/game/api/events/player/players.ts
- client/src/game/systems/access/index.ts
- client/src/game/systems/access/state.ts
- client/src/game/systems/client/index.ts
- client/src/game/systems/players/index.ts
- client/src/game/tools/variants/draw.ts
- client/src/game/tools/variants/ping.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/tools/variants/spell.ts
- client/src/game/ui/LabelManager.vue
- client/src/game/ui/menu/LocationBar.vue
- client/src/game/ui/settings/shape/ExtraSettings.vue
- client/src/game/ui/tokendialog/CreateTokenDialog.vue
- client/src/store/location.ts
The client store PR refactor assumed a certain order of players arriving, which is not guaranteed.
This just makes it so the currentPlayer function returns undefined instead of throwing an error if the current player info is not yet loaded.
> bug(Tech: Players): Make currentPlayer return undefined

- CHANGELOG.md
- client/src/game/api/events/player/options.ts
- client/src/game/layers/canvas.ts
- client/src/game/layers/variants/fow.ts
- client/src/game/layers/variants/fowVision.ts
- client/src/game/rendering/core.ts
- client/src/game/systems/floors/index.ts
- client/src/game/systems/settings/players/helpers.ts
- client/src/game/systems/settings/players/index.ts
- client/src/game/systems/settings/players/models.ts
- client/src/game/systems/settings/players/state.ts
- client/src/game/ui/settings/client/ClientSettings.vue
- client/src/game/ui/settings/client/PerformanceSettings.vue
- client/src/game/ui/settings/client/categories.ts
- client/src/locales/en.json
- server/src/models/user.py
- server/src/save.py
The floor system adds a lot of fun immersive options. This comes at the cost of performance however, which depending on the player's hardware can be an issue.
This PR adds a first Performance oriented client option to disable rendering of all other floors.
> feat(Performance): Add client option to limit floor rendering to active floor

- CHANGELOG.md
- client/src/game/ui/menu/LocationBar.vue
Location menu has a typo in the archived locations section.
> Fix typo in location menu

- CHANGELOG.md
- client/src/core/components/modals/AssetPicker.vue
The in-game asset picker modal had some UI "bugs" like content overflowing into areas where it shouldn't be visible etc.
This PR is a simple cleanup of some of these issues.
> bug(UI): Fix AssetPicker UI problems

- CHANGELOG.md
- client/src/core/plugins/modals/prompt.ts
When the last prompt modal you opened had an error message, this message will appear in any following prompt you open instead of being properly cleared.
> bug(Prompt): Fix prompt modal not clearing error message

- client/src/game/api/events/client.ts
- client/src/game/api/events/player/players.ts
- client/src/game/systems/client/index.ts
- client/src/game/systems/settings/location/index.ts
- client/src/game/systems/settings/location/state.ts
- server/src/api/socket/location.py
Due to an oversight during a recent refactor, the settings of the active location were not properly being sent to players causing things like fog of war suddenly disappearing at the player side but not the DM side.
> bug(LocationSettings): Fix location settings not being sent to players

- client/src/game/layers/floor.ts
When loading a location that has floors, lower floors would not immediately be shown until you change floors once.
_This is a regression due to the renderAllFloors performance option_
> bug(Floors): Fix initial load not showing lower floors

- CHANGELOG.md
- client/src/game/ui/tools/DiceTool.vue
- client/src/game/ui/tools/DrawTool.vue
- client/src/game/ui/tools/FilterTool.vue
- client/src/game/ui/tools/MapTool.vue
- client/src/game/ui/tools/RulerTool.vue
- client/src/game/ui/tools/SelectTool.vue
- client/src/game/ui/tools/SpellTool.vue
- client/src/game/ui/tools/Tools.vue
- client/src/game/ui/tools/VisionTool.vue
The detail panel for specific tools (e.g. colour selection etc) was not properly positioned on the y-axis when using the new icons. This is now fixed.
Additionally I also simplified/cleaned the css logic for this detail panel and it should now also no longer be in the wrong location. This could happen in the past when changing tool mode or when another tool would be enabled/disabled.
> bug(Tools): Fix toolbar detail position

- CHANGELOG.md
- client/src/game/drag.ts
- client/src/game/input/keyboard/up.ts
- client/src/game/interfaces/shape.ts
- client/src/game/layers/variants/fowLighting.ts
- client/src/game/layers/variants/fowVision.ts
- client/src/game/rendering/auras.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/variants/asset.ts
- client/src/game/shapes/variants/baseRect.ts
- client/src/game/shapes/variants/circle.ts
- client/src/game/shapes/variants/circularToken.ts
- client/src/game/shapes/variants/line.ts
- client/src/game/shapes/variants/polygon.ts
- client/src/game/shapes/variants/rect.ts
- client/src/game/shapes/variants/simple/asset.ts
- client/src/game/shapes/variants/simple/boundingRect.ts
- client/src/game/shapes/variants/text.ts
- client/src/game/shapes/variants/toggleComposite.ts
- client/src/game/systems/client/index.ts
- client/src/game/systems/logic/tp/core.ts
- client/src/game/systems/logic/tp/index.ts
- client/src/game/tools/variants/map.ts
- client/src/game/tools/variants/ping.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/tools/variants/spell.ts
- client/src/game/ui/initiative/state.ts
- client/src/game/ui/settings/shape/GroupSettings.vue
- client/src/game/ui/toasts/LogicRequestHandlerToast.vue
- client/src/store/game.ts
The center point of shapes are being calculated on the fly.
Most shapes however don't actively move that often if at all, so we're kinda wasting CPU cycles on calculating the center whenever we need to render it. This PR changes that to instead keep the center in memory.
We're basically using more memory to gain more performance.
_The implementation is the same idea as the now closed #850 but that PR was no longer up to date with a lot of the recent changes, so I just decided to create a fresh PR._
> feat(Tech: Performance): Memorize shape centers

- client/.dependency-cruiser.js
- client/src/game/interfaces/shape.ts
- client/src/game/layers/variants/fowVision.ts
- client/src/game/rendering/auras.ts
- client/src/game/shapes/shape.ts
- client/src/game/systems/floors/index.ts
- client/src/game/systems/floors/state.ts
- client/src/game/systems/position/index.ts
- client/src/game/vision/state.ts
Shapes have to calculate their vision frequently. Usually we're only moving a couple shapes a time (if we're even moving any shapes at all). Recalculating the vision polygon for those shapes that are not moving is thus wasting cpu cycles as the result will be the same (unless we're moving vision blockers).
This PR thus caches the vision polygon for each shape that requires it (shapes marked with isToken and LOS enabled or shapes with a light aura).
_the PR is a bit messy atm as it was rebased onto the center() changes from latest dev, I'll clean this up in the short future_
> feat(Tech: Performance): Cache vision polygons

- client/src/game/Game.vue
Recent changes to the css made it so that the dice area could be slightly higher than the rest of the main game UI, causing a scrollbar to appear on some devices.
> bug(UI): Fix dice area adding scrollbar

- client/src/game/tools/variants/select/index.ts
When deselecting shapes, there would appear some errors in the browser console.
These were harmless in nature, but have been addressed.
> bug(Select): Fix harmless console errors

- server/src/api/socket/initiative.py
Recent initiative fixes were made to make sure that when removing a shape, the initiative entry is also removed. These checks however wrongly assumed that every location always has an initiative entry causing the call to fail.
> bug(Select): Fix shape removal not working if no initiative is present

- CHANGELOG.md
- client/src/game/dice/environment.ts
As reported in #1044, the diceroller was not working when the server is using subpath serving.
> bug(Dice): Fix diceroller not working on subpath server

- client/src/game/interfaces/shape.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/shapes/shape.ts
When moving a shape to a different floor and visiting that floor, the vision would of that shape would not be recalculated until you move it or interact in another way that triggers vision recalculation.
This has been resolved.
> bug(Vision): Fix vision not properly updating on shape floor change

- CHANGELOG.md
- client/src/game/ui/SelectionInfo.vue
This fixes #944: The selection info has a lot of extra whitespace for the second column (with the tracker values).
> bug(UI: SelectionInfo): Trim white space in selection info

- CHANGELOG.md
- client/src/game/ui/initiative/state.ts
- client/src/game/ui/toasts/LogicRequestHandlerToast.vue
- client/src/store/game.ts
When using initiative camera-lock to automatically center the camera on the next character, the logic would not check if that character was on a different floor.
Similar logic errors were fixed for 'jump to marker' and 'preview area' for logic doors/tp.
> bug(Camera): Fix multiple center-on-shape calls not checking for floor change

- CHANGELOG.md
- client/src/game/interfaces/layer.ts
- client/src/game/interfaces/shape.ts
- client/src/game/layers/variants/fow.ts
- client/src/game/layers/variants/fowLighting.ts
- client/src/game/layers/variants/fowVision.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/variants/simple/boundingRect.ts
- client/src/game/systems/position/index.ts
- client/src/game/systems/position/state.ts
- client/src/game/ui/UI.vue
- client/src/game/vision/state.ts
Sometimes you may find yourself somewhere on the infinite canvas with nothing familiar in sight. For power-users familiar with PA this is usually quickly resolved with a couple of methods. This is however not info easily figured out by novice players/dms. Additionally some of these methods can only be accessed with keyboard, excluding another batch of users.
This PR introduces a simple UI element that pops up on the bottom of the screen when your screen is no longer seeing something interesting. By clicking on the new UI element you will return to a place where you can see something and hopefully be able to figure out where you wanted to be.
Depending on the vision-modes enabled there are 3 different approaches that PA uses to return to content (as well as detect the out-of-bounds …
> feat(out-of-bounds): Add out-of-bounds checks

- CHANGELOG.md
- client/src/game/floor/server.ts
A while ago (>2 years) I changed the direction in which the layers are drawn. As the lighting layer depends on the vision layer, I had to do a small modification to make sure they were still drawn in the correct order.
The way this was implemented was by moving the vision layer to the end of the draw stack. Which caused the draw layer to now be below the fog layer which in turn means that things like the ruler or ping tool would appear below the fog and thus are currently not visible.
I'm slightly confused how this has flown below my radar for so long. So if this was reported and I somehow ignored it, it was not on purpose!
> bug(Layers): Fix Draw layer order

- CHANGELOG.md
- client/src/game/shapes/utils.ts
Another bug that has been here for at least 2 years O_O.
When removing a shape on a floor that is not the lowest floor, the vision system would receive a call to refresh the wrong floor, _if_ the lowest floor was _not_ the initial floor loaded upon loading the campaign.
> bug(Vision): Fix vision bug when removing shapes in multi-floor setup

- client/src/game/systems/position/index.ts
As a DM you actually can see things through fog, so some of the extra checks the out-of-bounds detection does, was overkill for the DM and was showing a "return to content" button while there was content.
> bug(Out-of-Bounds): Do a more relaxed oob checks for the DM

- CHANGELOG.md
- client/src/core/components/modals/AssetPicker.vue
The AssetPicker is a Modal window that appears when selecting assets. (e.g. campaign logo selection, shape variants, ...)
Modals are centered on the screen the moment they appear based on their current height, which for the AssetPicker was very tiny as the data still had to be fetched. Causing the final visual appearance of the modal to be way too low, with the buttons potentially off-screen.
This has now been fixed.
> bug(UI: AssetPicker): Fix asset picker appearing too low

- CHANGELOG.md
- client/src/game/models/tools.ts
- client/src/game/tools/events.ts
- client/src/game/tools/tool.ts
- client/src/game/tools/variants/select/index.ts
The polygon edit UI is part of the select tool in build mode. When you use a panning shortcut while the polygon edit UI is visible, parts of the UI would stay on the same (x,y) location on the screen while the shape is being moved around.
This is visually not very pleasing. This PR solves the issue by hiding the polygon UI during pan and show it again when the panning stops.
We could go the extra mile and update the polygon UI position continuously during the pan, but given that it can't be interacted with anyway during a pan, it only adds clutter.
> bug(UI: Polygon Edit): Fix polygon edit UI during panning

- CHANGELOG.md
- client/src/game/ui/menu/MenuBar.vue
When enabling "fake player" modus, the DM enters a mode where some of their DM abilities are stripped down to mimic players. The left menubar however would also listen to these changes and no longer show DM entries.
One of these entries, the DM Settings, however is pretty crucial as without access to the DM Settings you can't disable the fake player mode again.
The menu entries have now been granted an exception to still operate in DM mode while fake player mode is active.
> bug(UI: Menu): Fix Fake Player hiding menu entries

- client/src/game/id.ts
- client/src/game/systems/position/index.ts
When there are no shapes at all, it is pretty silly to show a "return to content" box.
> bug(UI: Out-of-Bounds): Don't do OOB check when there is nothing

- CHANGELOG.md
- client/src/game/shapes/variants/polygon.ts
When moving a polygon point with the select tool, the entire shape would move funky if the shape had a rotation applied.
> bug(Select: Resize): Fix polygon point move under rotation

- client/src/game/api/emits/initiative.ts
- client/src/game/api/events/initiative.ts
- client/src/game/models/initiative.ts
- client/src/game/ui/contextmenu/ShapeContext.vue
- client/src/game/ui/initiative/Initiative.vue
- client/src/game/ui/initiative/state.ts
- client/src/game/ui/tools/toolPosition.ts
Since the introduction of the `LocalId` vs `GlobalId` concept, initiative has had a bunch of issues.
I thought most of these issues were resolved, but recently I hit some bugs again making me inspect the initiative code again. And I don't know what past me was thinking.
The initiative client state has been rewritten slightly to handle ids more robustly in the case of unknown shapes, which should make everything work correctly again.
That said:
- a hacky fix that was made previously hid entries that were unknown, these will re-appear as a `?`, but now should actually be properly removable by the DM, which was a problem in the past.
- I may have overlooked something, so small fixes here and there may still be necessary, but the overall structure is in a much better shape now
> bug(Initiative): Make initiative id handling more robust

- .circleci/config.yml
- server/PA.spec
PyInstaller has been our trusty goto tool to create the windows builds (.exe files) for those people out there that are less technical.
I sadly recently got a handful of people complaining that kaspersky flags it as a virus.
This is extremely likely a false positive, but well I took some time to investigate it an couldn't get anything else to work, until I tried nuitka, which virustotal gives 0 detections for.
Nuitka is pretty slow compared to PyInstaller (~15 minutes compared to 1), but we only need it for release builds, so that doesn't happen that often anyway.
I'll have to monitor people using the new exes (starting with 2022.3) to see if there is any noticeable difference with the previous versions.
> bug(CI: Windows Build): Change PyInstaller for Nuitka

- client/src/game/rendering/core.ts
- client/src/game/systems/position/index.ts
- client/src/game/systems/position/state.ts
- client/src/game/ui/TokenDirections.vue
Out of bound checks were being ran a bit too early, possibly still showing a "return to content" button after already having returned to said content.
(they were fired after layer invalidation, but not explicitly waiting on the layers to actually be re-drawn)
> bug(OOB): Wait with OOB check until layer draw

- CHANGELOG.md
- client/src/game/Game.vue
- client/src/game/api/events/player/options.ts
- client/src/game/systems/settings/players/helpers.ts
- client/src/game/systems/settings/players/index.ts
- client/src/game/systems/settings/players/models.ts
- client/src/game/systems/settings/players/state.ts
- client/src/game/tools/events.ts
- client/src/game/ui/settings/client/BehaviourSettings.vue
- client/src/locales/en.json
- server/src/models/user.py
- server/src/save.py
This PR adds a ClientSetting to decide which mouse buttons initiate pan mode.
It defaults to middle & right, but can be modified to either or none.
It can be found under the behaviour->mouse gestures section.
This closes #1104.
> feat(ClientSettings): Add setting to set mouse pan behaviour

- client/src/game/ui/Floors.vue
- client/src/game/ui/menu/LocationBar.vue
- client/src/game/ui/settings/shape/LogicPermissions.vue
The draggable templates are by default untyped, this PR adds explicit types to the variables.
> chore(Typing): Add typing to all draggable templates

- client/src/game/layers/variants/fowLighting.ts
- client/src/game/systems/position/index.ts
Shapes drawn with the reveal/hide draw modifiers were not taken into account for the out-of-bounds checks
> bug(OOB): Take preFogShapes into account for OOB

- CHANGELOG.md
- client/src/game/ui/dice/DiceResults.vue
Currently PA shows the total + subtotal per die type when throwing dice (e.g. 6d6+2d4 will show you something like 13 (10 + 3)).
It can be important for various systems to see the individual die results instead (e.g. the 2d4 above subtotal to 3 because you rolled a 1 and a 2).
> feat(Dice): Show individual die results

- CHANGELOG.md
- client/src/game/input/keyboard/down.ts
The select tool has a rotation helper (in build mode) that was not moving along if a shape was moved with the keyboard.
> bug(Select): Fix rotation helper not moving with keyboard movement

- client/src/dashboard/games/ExportGame.vue
The `window.open` method that I was using is not guaranteed to work, as the browser might prevent this from happening for privacy/security reasons.
A fallback url has been provided to display.
> bug(Export): Show a url as fallback download

- CHANGELOG.md
- client/src/game/tools/variants/spell.ts
When a shape is selected, spell-tool shapes should originate from the selection center. This was broken for a bit and should now be resolved.
> bug(SpellTool): Fix spell tool no longer working for selections

- client/src/game/tools/tool.ts
- client/src/game/tools/variants/draw.ts
- client/src/game/tools/variants/map.ts
- client/src/game/tools/variants/pan.ts
- client/src/game/tools/variants/ping.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/tools/variants/spell.ts
Tools all share a same interface. Some of the tools require these methods to be async, whereas others don't care.
In the past I used some eslint ignores, but I've restructured it to return `Promise.resolve()` in that case.
> chore: Cleanup sync tool calls

- CHANGELOG.md
- client/src/game/tools/tools.ts
- client/src/game/tools/variants/spell.ts
The fill colour of the spell tool shape is supposed to be 70% opacity of the border colour (which is the main colour you define). If you modify the opacity of that colour picker however, the fill colour suddenly can be any random colour as something incorrect was going on in the code.
This has been rectified.
> bug(SpellTool): Fix spell tool fill colour jank

- CHANGELOG.md
- client/src/game/models/tools.ts
- client/src/game/tools/events.ts
- client/src/game/tools/tool.ts
- client/src/game/tools/variants/draw.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/tools/variants/spell.ts
The SpellTool on right-click cancels the current draw operation and that's all it's supposed to do.
It was however also triggering the context menu on opening. This has been resolved.
> bug(SpellTool): Fix contextmenu opening on right-click

- CHANGELOG.md
- client/src/game/tools/tools.ts
Once the spell tool has been used (either by left or right click), the select tool should be activated.
This however was no longer happening properly.
> bug(SpellTool): Fix spell->select activation

- CHANGELOG.md
- client/src/game/models/tools.ts
- client/src/game/tools/tool.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/spell.ts
- client/src/game/ui/tools/SpellTool.vue
The spell-tool has had a size and a range property since the beginning. The latter only being available when you have a shape selected.
From experience however players tend to be confused by which value is meant to represent what and in most cases it's a bit of a hassle to configure the range in advance.
So this PR removes the range from the spell tool UI and instead shows a ruler between your selected shape and the spell you're drawing. This conveys the same information with less effort!
> feat(SpellTool): Rework range concept

- CHANGELOG.md
- client/src/game/api/emits/shape/asset.ts
- client/src/game/api/events.ts
- client/src/game/api/events/shape/asset.ts
- client/src/game/shapes/variants/asset.ts
- client/src/game/ui/settings/shape/PropertySettings.vue
- server/src/api/socket/shape/__init__.py
- server/src/api/socket/shape/data_models.py
- server/src/models/shape/__init__.py
Sometimes you just want to change the current character art for something else. PA offers some fancy things like variants to swap between art, but this is all very overkill if the sole purpose is to change the art without the desire to change back in the near future.
A simple button has been added to the Shape property settings to change the asset currently used. (This is thus only available to shapes that were made from assets in the first place)
> feat(Shape): Add change asset button

- CHANGELOG.md
- client/src/game/ui/settings/shape/ShapeSettings.vue
- client/src/locales/de.json
- client/src/locales/dk.json
- client/src/locales/en.json
- client/src/locales/es.json
- client/src/locales/it.json
- client/src/locales/ru.json
- client/src/locales/tw.json
- client/src/locales/zh.json
The edit dialog header has been saying "Edit asset" for ages. Which is incorrect use of the terminology established in the docs.
This has been rectified and now properly says "Edit shape".
The language keys in translated languages has been reset for this property and should thus be adjusted separately. (Translations is something I need to look back into some time as well)
> lang: Change edit dialog header

- CHANGELOG.md
- client/src/game/ui/tools/Tools.vue
A new UI region is being added to quickly toggle some things on or off without having to go into some setting menu.
The first addition is "Fake Player", something that has been requested a couple of times in the past and is in an awful setting location atm to quickly play with.
Bear in mind that there are some lingering issues with FakePlayer that I hope to also address in the near future. This should also open up its use to more people, which in turn should bring up some more edge cases probably.
Expect another addition to this new bar soon, so don't worry about FP being lonely ;)
> feat(UI): Add quick access toggle bar + fake player toggle

- CHANGELOG.md
- client/src/game/api/emits/initiative.ts
- client/src/game/api/events/initiative.ts
- client/src/game/api/events/player/options.ts
- client/src/game/models/initiative.ts
- client/src/game/systems/settings/players/helpers.ts
- client/src/game/systems/settings/players/index.ts
- client/src/game/systems/settings/players/models.ts
- client/src/game/systems/settings/players/state.ts
- client/src/game/ui/initiative/state.ts
- client/src/game/ui/settings/client/InitiativeSettings.vue
- client/src/game/ui/tools/Tools.vue
- client/src/locales/en.json
- server/src/api/socket/initiative.py
- server/src/models/initiative.py
- server/src/models/user.py
- server/src/save.py
Initiative never had a real concept of "active". You could have the initiative UI open or closed regardless of whether something is actually happening with initiative.
This hampers some things (e.g. the Initiative setting "lock vision" is in a semi-broken state due to this), so I'm adding it in this PR.
I considered regarding whether the initiative UI is open to be an implicit representation of whether initiative is active, but felt that that was not adequate from my own experience in how I use this UI.
This toggle will join the recently added status toggle bar and join the "Fake Player" toggle.
This also makes it a bit easier to access initiative instead of going through a right click.
The active state is saved on the server, so this is remembered when you refresh the page.
It is …
> feat(Initiative): Add new Initiative "active" state

- client/src/core/components/slider/SliderComponent.vue
Firefox must have changed something to their css engine as it was adding some extra whitespace causing scrollbars to appear were it didn't before. The element in question hasn't been touched for at least 18 months either so ¯\\\_(ツ)\_/¯.
I've added some extra padding to the zoom slider, which seems to resolve it.
> bug(Css): Some weird firefox css change fix

- client/src/game/ui/UI.vue
- client/src/game/ui/contextmenu/DefaultContext.vue
- client/src/game/ui/contextmenu/ShapeContext.vue
- client/src/game/ui/initiative/Initiative.vue
- client/src/game/ui/initiative/state.ts
When a player adds initiative, the server sends a request back which also contains the active state of the initiative and based on that info was setting the initiative UI visibility. If the initiative state was not active, this could cause a funky experience if you tried to interact with the initiative UI while the initiative state was not active.
As mentioned in the PR for the initiative state, this is not the intention and has been rectified.
> bug(Initiative): Fix initiative UI immediately closing when not active in certain cases

- CHANGELOG.md
- client/src/core/components/modals/Modal.vue
- client/src/core/components/modals/PanelModal.vue
- client/src/game/ui/LabelManager.vue
- client/src/game/ui/ModalStack.vue
- client/src/game/ui/NoteDialog.vue
- client/src/game/ui/UI.vue
- client/src/game/ui/dice/DiceResults.vue
- client/src/game/ui/initiative/Initiative.vue
- client/src/game/ui/settings/FloorSettings.vue
- client/src/game/ui/settings/client/ClientSettings.vue
- client/src/game/ui/settings/dm/DmSettings.vue
- client/src/game/ui/settings/lg/LgSettings.vue
- client/src/game/ui/settings/location/LocationSettings.vue
- client/src/game/ui/settings/shape/LogicPermissions.vue
- client/src/game/ui/settings/shape/ShapeSettings.vue
With the addition of #1135 there now is a concept of topmost modal.
This PR adds the ability to close the topmost modal by pressing the escape key.
This closes #1062. Although that request wanted to close all open modals, I personally see more value in more fine-grained close mechanics. Definitely given that there aren't that many modals you probably have open anyway, so pressing escape once or twice more shouldn't be a huge deal.
> feat(UI): Close modals with escape

- CHANGELOG.md
- client/src/game/floor/server.ts
- client/src/game/layers/variants/dm.ts
The goal of the fake-player view is to have a sense of what players would see.
The DM layer is obviously not part of that and is from now-on no longer shown while FP is active.
> bug(FakePlayer): Hide DM layer when fake-player is active

- CHANGELOG.md
- client/src/game/api/events/location.ts
- client/src/game/operations/movement.ts
- client/src/game/systems/settings/location/index.ts
- client/src/game/systems/settings/location/models.ts
- client/src/game/systems/settings/location/state.ts
- client/src/game/ui/initiative/state.ts
- client/src/game/ui/settings/location/VariaSettings.vue
- client/src/locales/en.json
- server/src/models/campaign.py
- server/src/save.py
This PR adds a new optional DM setting to limit movement during initiative.
The setting can be found in the `Varia` category.
When enabled, only the shape that is currently acting in the initiative tracker can be moved.
This rule is intended to keep some players in check who might move around too much when they aren't supposed to.
Do note that DMs themselves are not restricted by this rule.
Also important to note is that this rule only applies when "initiative is active". (see #1132)
> feat(Initiative): Limit movement during initiative

- CHANGELOG.md
- client/src/game/systems/players/index.ts
- server/src/api/socket/player.py
This closes #1144
The last DM was able to demote themselves to player, causing the campaign to become unmanageable.
> bug(AdminSettings): Fix removing last DM being possible

- CHANGELOG.md
- client/src/game/shapes/variants/asset.ts
The default colour for assets was no longer properly set since the introduction of the propertiesSystem.
This affected things like the badge background which uses this colour.
This fixes #1143
> bug(Assets): Fix asset default stroke colour being set wrongly

- CHANGELOG.md
- client/src/game/ui/tools/DiceTool.vue
The area in the dice tool UI where the dice to roll are being prepared (e.g. 2d20 + 1d10), was being implicitly sized (in height). Which causes a janky jump of the other dice controls when the first die is added, which is kinda annoying.
This PR fixes this by just setting a minimum height to that UI element.
> feat(Dice): Add min-height to dice tool UI

- CHANGELOG.md
- client/src/core/components/ColourPicker.vue
- client/src/core/components/RotationSlider.vue
- client/src/game/ui/SelectionInfo.vue
- client/src/game/ui/settings/shape/TrackerSettings.vue
This fixes #1150.
Some tracker/aura related settings did not do proper access checks on the client side, allowing players to edit some public tracker/aura information for shapes they otherwise don't have access to.
These changes however were always rejected by the server and thus never reached other players.
> bug(Trackers): Fix some missing client-side access checks

- client/src/game/ui/menu/MenuBar.vue
- client/src/game/ui/tools/Tools.vue
A recent refactor to reason about `dm` and `fakePlayer` mode, was incorrectly checking this value in 2 components causing them to be visible to players.
this fixes #1152
> bug(UI): Fix some DM elements being visible to players

- CHANGELOG.md
- client/src/core/plugins/modals/prompt.ts
The prompt modal is used to prompt for several info bits in PA.
An optional validation function can be passed along so that the prompt can stay open and show an error message if an invalid response is given.
When opening a prompt without a validation function, there was nothing resetting the validation function if one was assigned previously.
> bug(Prompt): Fix validation function cache

- client/src/assetManager/socket.ts
- client/src/assetManager/state.ts
This is a fix for an innocent bug that caused an error log to appear in the console when using the asset manager.
An additional iteration of some code was being done due to an extra "/" at the end that was not being handled. The extra iteration however would always fail due to an index error and there was nothing else to do after the iteration so in practice nothing terrible happened.
> bug(AssetManager): Fix asset path handling

- CHANGELOG.md
- client/src/game/shapes/variants/baseRect.ts
When a rotated rectangle shape is resized with its bottom-right corner, the shape does funky things.
This fixes #1160.
> bug(Resize): Fix botright resize while rotated

- CHANGELOG.md
- client/src/game/ui/TokenDirections.vue
- client/src/game/ui/UI.vue
- client/src/game/ui/menu/MenuBar.vue
The token direction UI (showing the direction of tokens that are offscreen) was getting priority over all other UI elements causing sometimes a jump to a token to happen instead of a UI element to open.
The behaviour has now changed so that the token direction UI should always have the last priority.
This fixes #1165
> bug(UI): Fix token direction UI trigger

- CHANGELOG.md
- client/src/game/ui/Floors.vue
The floor details would stay in the same place if the side menu was opened.
This fixes #1166
> bug(UI): Fix floor detail positioning when menu is open

- CHANGELOG.md
- client/src/game/shapes/shape.ts
Trackers have a `display on token` property to show the tracker visually above the token in a rectangular bar.
This bar was not showing up if the tracker happened to be shared among all variants.
This fixes #1167
> bug(Tracker): Fix shared for all variants tracker not being able to use display on token

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
When unlocking a shape, after having attempted to move it, the shape snaps to your cursor and follows it as if you had started dragging it.
This fixes #1168
> bug(Select): Fix locked shape snapping

- client/src/game/ui/TokenDirections.vue
A recent change from #1165 unintentionally caused the token direction UI to render as all red rather than displaying a preview of the token. This change reverts that side effect.
result of #1165:
after this fix:
> bug(UI): Fix token direction UI rendering

- CHANGELOG.md
- client/src/game/input/keyboard/down.ts
The `x` keybind (to set defeated state) and `ctrl+l` keybind (to toggle the locked state) where not checking for access at the client-side.
They were checked and rejected at the server side, so no other players would ever see the changes, but for the client attempting the change it would seem like it worked.
> bug(Access): Fix keybinds not checking access

- client/src/game/systems/groups/index.ts
When creating a new group, most UI elements would report the shapes as not being in a group until you refreshed.
This fixes #1164
> bug(Groups): Fix group creation not immediately adding members

- client/src/game/ui/contextmenu/ShapeContext.vue
Selecting a group of shapes all belonging to the same group would show a context menu entry to "merge" the groups instead of "remove".
> bug(Groups): Fix shape context menu using wrong way to calculate group size

- CHANGELOG.md
- client/src/assetManager/AssetContext.vue
Scrolling after opening the context-menu (right click) on an item in the asset manager was not moving the context-menu along with the rest of the content.
This PR resolves this visual annoyance by closing the context-menu if a scroll action is done.
Fixes #1169
> bug(AssetManager): Close contextmenu on scroll

- CHANGELOG.md
- client/src/game/ui/contextmenu/ShapeContext.vue
When adding multiple shapes at once to initiative, regardless of the group setup, a prompt would appear to ask how to handle shapes that belong to the same groups.
When shapes that have no groups are added to initiative, this is irrelevant and an annoying extra step.
Fixes #1179
> bug(Initiative): Fix adding multiple shapes to initiative always prompting for group handling

- CHANGELOG.md
- client/src/assetManager/context.ts
If you're scrolled down in the asset manager and try to open the context-menu on an item, it appears in the wrong location.
Fixes #1169
> bug(AssetManager): Fix context menu appearing in wrong location when scrolled

- server/src/api/socket/shape/__init__.py
- server/src/api/socket/shape/access.py
- server/src/models/access.py
- server/src/transform/shape.py
As reported in #1187 some access was granted to people who had explicit access rules but no access set.
This was caused by some oversights into places where the presence of an access rule for a person was assumed to equal access, which is wrong.
Additionally modifying the access rights of a user who already had explicit access rules, would sometimes not properly update until a refresh.
This has been rectified.
Fixes #1187
> bug(Access): Fix various errors with access

- CHANGELOG.md
- client/src/router/index.ts
This PR fixes an error in the client-side auth routing flow. The error has no impact on security, but is purely a UX issue.
In some cases when visiting a page that requires the user to be logged in, the client was not properly redirecting to the login view, but instead would show the target page but without any data (e.g. the game listing would be empty) as the server side would reject all client requests.
This meant the user had to manually visit the login page in these cases.
> bug(Auth): Fix a logic error in the auth routing flow

- CHANGELOG.md
- client/src/game/models/templates.ts
Templates are a way to save a shape with some settings pre-filled for later re-use. Since introducing templates, they haven't been updated to match new features and are thus missing some data that one would expect to be saved.
The following data is now also saved:
- Annotation public visibility
- Trackers:
- Display on token
- Colors for display on token
- Auras:
- Whether the aura is enabled
- The stroke colour
- The angle and direction
While revisiting these keys, I've also removed some settings that are **no longer** saved.
The settings I've removed felt too situational to be saved as a general setting.
Ideally at some point while saving a template, you would get the option to choose which things are saved on a more fine-grained level, allowing you to save these after all for specific …
> bug(Templates): Fix missing settings + remove some settings

- CHANGELOG.md
- client/src/game/layers/variants/fowVision.ts
- client/src/game/rendering/auras.ts
- client/src/game/systems/auras/index.ts
In the last release we  fixed shapes on the DM layer no longer being rendered when in fake player mode.
As pointed out by #1203 however, I forgot to take into account potential auras as well as the minimal vision that shapes with `isToken` receive.
This is now resolved.
Fixes #1203
> bug(FakePlayer): Fix auras and isToken rendering

- CHANGELOG.md
- client/src/game/ui/tools/Tools.vue
The vision and filter tools are only shown if there is some extra condition relevant. This condition was only evaluated when changing tool mode. This meant that upon opening these tools were not visible in play mode even when they should have been until you swapped to build mode and back.
Fixes #1201
> bug(Tool UI): Fix visible tools on first render

- CHANGELOG.md
- client/src/game/ui/settings/shape/AccessSettings.vue
- client/src/game/ui/settings/shape/ExtraSettings.vue
When you have a shape's edit UI open and someone alters the access rights you have for that shape, the UI would not update accordingly until you deselected and then reselected the shape in some cases.
> bug(Access): Fix edit shape UI not live updating to access changes

- CHANGELOG.md
- client/src/game/systems/access/index.ts
For shapes that have no alterations to the access state, the default access values could be wrongly displayed in the edit shape access UI if a shape has previously been selected that differed from the default values for default access.
> bug(Access): Fix default access UI not always accurate

- CHANGELOG.md
- client/src/game/systems/access/index.ts
DMs have implicit edit access to all shapes. It is not possible to add explicit access for DMs using the access UI as this could potentially be confusing if you try to revoke certain access rights from a DM.
During the creation of some shapes(e.g. basic tokens) DMs would still be explicitly granted access and thus show up in the access UI.
This PR now actively prevents any `addAccess` call to work for DMs.
> bug(Access): Prevent DMs from having explicit access

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/api/emits/players.ts
- client/src/game/api/events.ts
- client/src/game/ui/contextmenu/DefaultContext.vue
- server/src/api/models/players/__init__.py
- server/src/api/socket/player.py
The "Bring Players" feature has always changed the receiving players' zoom level to that of the DM.
Since its introduction I've actually felt it to be more of a pain than a boon so I'm changing this behaviour to just change the position and not touch the zoom level.
Players might be zoomed out or in depending on their monitor setup, and the zoom drastically changing to some arbitrary vision that the DM happens to be using, makes little sense.
> feat(BringPlayers): No longer adjust players' zoom to DM zoom

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/api/emits/players.ts
- client/src/game/systems/logic/tp/core.ts
- server/src/api/models/players/__init__.py
- server/src/api/socket/player.py
If a player has the 'Move player(s) when a token they own changes location' setting enabled, when a shape the player owns is moved to a different floor due to a teleport zone, their view would not move along.
The wording of the setting specifically mentions a location change, which in PA terms is actually not happening, but the intent of the setting is to move the camera along if a token changes position suddenly as is the case here.
Fixes #1213
> bug(TpZone): Fix floor change not causing player view to move along

- client/src/game/tools/variants/draw.ts
After the API rework, shape creation was momentarily broken and that was fixed. Polygon creation in draw mode was still broken apparently, this fixes that :)
> bug(Draw): Fix polygon draw no longer working [dev]

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/api/emits/logic.ts
- client/src/game/api/events/logic.ts
- client/src/game/id.ts
- client/src/game/systems/logic/common.ts
- client/src/game/systems/logic/door/index.ts
- client/src/game/systems/logic/door/models.ts
- client/src/game/systems/logic/models.ts
- client/src/game/systems/logic/tp/index.ts
- client/src/game/systems/logic/tp/models.ts
- client/src/game/systems/players/index.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/ui/toasts/LogicRequestHandlerToast.vue
- server/src/api/models/logic/request.py
- server/src/api/socket/logic.py
The logic permission "Request" was not properly being validated and instead behaved as "Enabled" instead.
Logic requests coming from players are routed through the DM to make sure they are valid and the Request check was not checking the original requester but instead always validating against DM which resulted in the Enabled behaviour.
Fixes #1214
> bug(Logic): Fix Request mode behaving as Enabled mode

- CHANGELOG.md
- client/src/game/shapes/variants/asset.ts
- client/src/game/ui/initiative/Initiative.vue
- client/src/game/ui/settings/shape/PropertySettings.vue
The subpath setup is a niche setup and thus from time to time happens to have some small issues.
This PR fixes two such issues:
- Initiative images not loading
- The new "Change asset" feature was taking subpaths into account, but in a wrong fashion
This fixes #1217
> bug(Subpath): Fix two issues with image rendering on subpath setup

- server/src/db/all.py
The database signals were no longer being triggered since the API rework.
> bug(Server): Fix database signals no longer triggering [dev]

- client/src/core/components/modals/SelectionBox.vue
- client/src/core/iter.ts
- client/src/dashboard/Assets.vue
- client/src/game/input/keyboard/up.ts
- client/src/game/interfaces/shapes/asset.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/variants/asset.ts
- client/src/game/systems/access/index.ts
- client/src/game/systems/access/models.ts
- client/src/game/systems/client/index.ts
- client/src/game/systems/groups/index.ts
- client/src/game/systems/labels/index.ts
- client/src/game/ui/contextmenu/ShapeContext.vue
- client/src/game/ui/initiative/Initiative.vue
- client/src/game/ui/menu/AssetNode.vue
- client/src/game/ui/menu/MenuBar.vue
- client/src/game/ui/settings/shape/AccessSettings.vue
- client/src/game/ui/tools/MapTool.vue
- client/src/game/ui/tools/VisionTool.vue
- client/src/game/vision/iterative.ts
- client/test/game/systems/access/index.test.ts
In certain places I have iterators on which I would like to map or filter, but have to convert them to an array first, causing an extra iteration without any use.
There is an active TC39 working group around this, but that has not yet landed in main ts, so I've just added some snippets until it's available in plain ts.
> chore(Tech): Add some iterator helpers

- CHANGELOG.md
- client/src/game/ui/TokenDirections.vue
The set of active tokens limited by the vision tool was ignored for the token directions UI. Instead it was always showing all owned tokens.
> bug(TokenDirections): Fix token directions showing filtered tokens

- client/src/game/api/events/location.ts
- server/src/api/socket/location.py
- server/src/api/socket/shape/options.py
Some API calls operate on the basis of only sending/receiving the changed values.
When checking the validity of input, the other fields are set to None values, which when transferred back to the client can cause some havoc when it starts updating all provided values to null.
This fixes tracker and aura updates as well as location option updates.
Fixes #1232
> bug(Tech: Api): Fix some api calls expecting partial data to receive full object

- client/src/core/components/modals/SelectionBox.vue
The selectionbox was returning an iterator where the consumers where expecting an array.
Fixes #1233
> bug(Tech: SelectionBox): Fix selection box return type [dev]

- CHANGELOG.md
- client/src/game/systems/auras/index.ts
To reduce the amount of shapes that multiple render-related functions have to check, PA orders the scene in sectors and keeps track of which shapes are visible in which sectors.  A shape is visible in a sector if the shape itself or any of its active auras extend into a sector.
When modifying aura properties (the range being the most important here), the shape's sectors were not being recalculated.
This caused lights that became public to players or increased in range to not be visible in the new sectors it's supposed to be visible. They would be shown to their full extent if any of the original shape sectors were in view, but not if (only) any of the new sectors were.
In the other direction a shape that disappeared or shrank in size would still be checked in sectors it should no longer …
> bug(Aura): Fix aura changes not updating shape sectors

- CHANGELOG.md
- client/src/game/systems/access/index.ts
- client/test/game/systems/access/index.test.ts
Fake player mode was receiving full access rights in certain situations.
This was responsible for things like showing invisible shapes even though no access was provided. (Fixes #1240)
Bear in mind that in the past (due to a bug) the DM user sometimes would be given explicit access to a shape, in order to have invisible shapes _not_ show up in fake player mode, you must ensure that your DM user does not have an explicit access rule for the shape. If there is a rule, just remove it.
> bug(Access): Remove Fake player full access

- CHANGELOG.md
- client/src/game/systems/groups/index.ts
- client/src/game/ui/settings/shape/GroupSettings.vue
The shape group settings UI had several issues:
- Active group info (e.g. members) was no longer visible
- Create new group button was always visible
This has now been resolved so that it is showing the proper info again.
Additionally the creation and removal of a group should immediately update in the UI for a shape instead of only updating once deselected and reselected again.
> bug(Groups): Shape group setting UI issues

- CHANGELOG.md
- client/src/game/layers/variants/layer.ts
- client/src/game/systems/floors/index.ts
Higher layers are rendered with a 0.3 opacity filter to make it clear that they are not in the current view.  This opacity was however only set when changing layers and not part of the main render logic. This caused a bug where resizing the screen, which does some internal changes, caused the opacity information to be lost.
This PR moves the transparency check to be a proper part of the render logic itself and not of the UI.
Fixes #1246
> bug(Rendering): Fix layer transparency

- client/src/game/api/events/logic.ts
- client/src/game/systems/logic/tp/core.ts
In #1224 we fixed some aspects of the teleport zones no longer working when initiated by players.
That PR properly fixed the "Request" mode, but apparently did not do a proper job as the "Enable" mode was not fixed.
This PR should fix the "Enable" mode as well. Fixes #1245
> bug(TpZone): Fix player initiated TP Zones (again)

- CHANGELOG.md
- client/src/game/ui/toasts/LogicRequestHandlerToast.vue
When a player requests the use of a TP zone, the DM has the option to view the area of the related request.
Up until now the area shown was the target of the teleport zone and not the teleport zone itself.
This PR changes this behaviour and instead shows the teleport zone itself, allowing the DM to properly see which shapes are about to teleport.
> feat(TpZone): Change view area behaviour

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
The rotation helper was not being resized properly while zooming as reported in #1244.
> bug(Select): Fix rotation helper UI size while zooming

- CHANGELOG.md
- client/src/core/iter.ts
- client/src/game/layers/variants/fowLighting.ts
- client/src/game/systems/access/index.ts
- client/src/game/systems/access/models.ts
- client/src/game/systems/access/state.ts
- client/src/game/systems/auras/index.ts
This PR hopefully tackles most fake player related issues once and for all.
Most previous fake-player related fixes were patches to very specific routines which as has been shown makes it easy to miss a bunch of cases. I've taken some time this weekend to actually properly look at the root issue of most fake player related code and _think_ I've fixed it.
This change fixes a bunch of things that were not behaving as they should.
**Rendering Changes**
Shapes that have default vision access or auras that are marked as public _should_ be visible as normal, shapes and auras that are however **not** public by default (including invisible shapes etc) will only be rendered **if and only if** there is some player with `vision` access to the shape **and** the vision tool has that shape selected. …
> bug(FakePlayer): Fix access handling in fake player mode

- CHANGELOG.md
- client/src/game/systems/access/index.ts
When updating vision access for a shape or changing the vision-tool set of active tokens, the shapes' layer would not be immediately re-rendered. Only the Light & Vision layers would re-rendered immediately.
> bug(Rendering): Fix some cases where vision access changes where not immediately rerendering

- CHANGELOG.md
- client/src/game/ui/menu/LocationBar.vue
The drag handle (the square with which you can drag locations around) was not always having the full CSS width as intended, making dragging the location harder. This happened when a location's name was split over multiple lines.
Fixes #1253
> bug(LocationBar): Fix multiline location drag handle

- CHANGELOG.md
- client/src/game/layers/variants/grid.ts
The grid was not rendering all the way down if the screen had a larger Y size than X size.
Fixes #1254
> bug(Grid): Fix rendering when screen is taller than it is wide

- client/src/game/layers/variants/layer.ts
- client/src/game/shapes/create.ts
- client/src/game/temp.ts
- server/src/db/models/polygon.py
A change was made to the way polygons are sent along the websocket and 1 function was not changed to take this into account, doing a wrong operation on the polygon data, breaking its representation in the database.
This PR fixes that function. It also adds some more safeguards to handle invalid shape data at the client side so that it doesn't completely crash, but skip the shape instead.
> bug(Polygon): Fix creation of new polygons breaking [dev]

- client/package-lock.json
- client/package.json
- client/src/game/ui/settings/shape/AccessSettings.vue
- client/src/game/ui/settings/shape/ShapeSettings.vue
- client/src/game/ui/settings/shape/TrackerSettings.vue
- client/vite.config.ts
When you select a shape, the data that is displayed in the shape settings UI's various panels is already being loaded. This allows the dialog to open immediately showing data without having to wait for this data to load. It does however also mean that just swapping between some shapes performs these loads every time even when not used.
This PR changes the logic slightly to only grab the data of the active tab and wait with fetching more data until the relevant tab is opened. This retains the quick loading of the shape settings modal window with a smaller cost.
That said, this change will be mostly unnoticeable for most people.
> feat(Performance: ShapeSettings): Delay loading of most shape settings UI data

- CHANGELOG.md
- client/src/game/api/events/shape/options.ts
When toggling the "Is Invisible" property of a shape, it is not updated live for all other connected clients until they refresh.
Fixes #1262
> bug(Shape): Fix invisible sync

- CHANGELOG.md
- client/src/game/systems/auras/index.ts
The vision lock setting in the initiative settings was no longer functioning properly.
It's intended to only show things the current active initiative participant can see (if it's a token the user controls) and this check was no longer being applied.
> bug(Initiative): Fix initiative vision lock

- CHANGELOG.md
- client/src/game/api/events/initiative.ts
- client/src/game/ui/initiative/state.ts
- server/src/api/socket/initiative/__init__.py
When the active initiative actor is the last entry in the initiative and is removed, the turn order was not being updated accordingly, causing the internal initiative tracker to point to an undefined entry.
Attempts to advance/rewind initiative would fail as these do some sanity checks that were now failing.
This PR fixes the issue and also adds a sanity check to turn updating to catch faulty internal state and fix it.
> bug(Initiative): Fix entry removal breaking turn logic in edge case

- CHANGELOG.md
- client/src/game/vision/cdt.ts
When drawing vision (e.g. using the polygon tool) there was a very rare edge-case that could be triggered which could cause an infinite loop, resulting in a frozen page.
> bug(Vision): Fix infinite loop edge case in marchLocate2D

- CHANGELOG.md
- client/src/game/shapes/variants/polygon.ts
- client/src/game/tools/variants/draw.ts
_I'm unsure whether I would classify this as a change or a bugfix :D._
The brush mode in the draw tool has been an eye sore for a _loong_ time.
It exists, but is a performance hog which means you probably should avoid it at almost all times.
The reason for that performance issue was with how the shape is stored internally.
Behind the scenes it's exactly the same kind of structure as a shape drawn with the polygon tool,
but the difference is in their creation.  In polygon mode, you dictate the points with clicks, whereas in brush mode your mouse drag dictates the polygon.
Long story short, the mouse drag was adding _a lot_ of points. This PR implements an algorithm that will during a drag simplify the polygon by trying to remove points that contribute close to nothing to the actual shape. …
> feat(DrawTool): Reduce the number of points when using brush mode

- CHANGELOG.md
- client/src/game/api/events.ts
Due to silliness the (socket) event listeners for all things groups related were no longer active. This happened due to some refactoring that I didn't pay proper attention to.
In practice this means that updates related to groups were not being received until you did a refresh.
> bug(Groups): Fix missing groups event listeners

- CHANGELOG.md
- client/src/dashboard/Assets.vue
Somehow I never realized that since the incorporation of the asset manager into the dashboard UI, the progress bar never made it along.
> feat(AssetManager): Re-introduce progressbar

- CHANGELOG.md
- client/src/App.vue
Firefox does not set the font-weight for the `<strong>` element. This is the element used by the markdown library to render bold text.
The combination of the above and a font-weight setting that PA applied a long time ago, made it so that bold markdown was not being rendered properly in firefox.
This fixes #1255.
This PR removes the global font-weight being set by the PA application. Another approach would be to set font-weight to bold for the strong element. I might have to revision this in the future, but this addresses the issue for now.
> bug(Annotation): Fix markdown bold rendering

- client/src/assetManager/state.ts
A technical oversight, in the recently added drop on the gameboard addition, that affects drops of larger images that are uploaded in separate slices.
> bug(Assets): Fix multi-slice upload behaviour

- CHANGELOG.md
- client/src/game/Game.vue
- client/src/game/ui/menu/MenuBar.vue
On touch devices (and mostly mobile devices), the browser handles scrolling the UI differently and will try to slide the entire screen to the top or bottom which looks jarring in the context of PA.
This PR just adds some css rules to prevent the browser from handling touch input as well on the board itself as well as the side menubar.
It does _not_ initiate fullscreen stuff as mentioned in #1155 however.
> feat(UI): Prevent out of screen scrolling with touch

- CHANGELOG.md
- client/package-lock.json
- client/package.json
- server/VERSION
-   Drop new assets on the game directly
-   Scroll-like touch gestures no longer attempt to scroll the gameboard out of bounds
-   Templates no longer save certain settings
-   Bring players no longer changes the zoom level of the players
-   TpZone: When a player TP request arrives, the view area action will bring the DM to the trigger location and not to the target location
-   Group: No longer sending group info for each member (just once)
-   Group: Shape group settings fixes
-   Create group button was not properly behaving
-   Remove group button was not immediately updating the UI until a reselection
-   Group: Fix socket events no longer being listened to; Fixes multiple things that were resolved when you refreshed
-   Auth: A logic error in the auth routing code - in some cases …
> release: 2023.2

- CHANGELOG.md
- server/server_config.cfg
- server/src/export/campaign.py
Campaign exports that contained notes would no longer work due to a couple of lines being duplicated at the end of the export function by a conflict between 2 formatting extensions in my editor.
> bug(Export): Fix campaign export with notes failing

- CHANGELOG.md
- server/src/api/socket/location.py
- server/src/db/models/player_room.py
PA uses websockets (i.e. socket.io) for communication between client and server. When a player enters a game they join a sio room for the game as a whole as well as a room for the specific location they are currently in. When changing locations they're supposed to leave the room associated with the previous location as events for that location are no longer interesting to the client. (e.g. shape movements)
This was however no longer behaving correctly, causing you to receive messages from all locations you visited (in the current browsing session).
> bug(Socket): Fix location change not properly leaving sio room

- server/src/db/models/shape.py
The `Shape.group` foreign field had no `on_delete` configured, meaning it defaults to `NO_ACTION` which is incorrect.
In practice this never was an issue as the `Group.Remove` event already sets the group to `null` for all relevant shapes.
Nonetheless this PR cleans up this technical error.
> bug(Tech: DB): Correct Shape.group on_delete

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/api/emits/location.ts
- client/src/game/ui/contextmenu/ShapeContext.vue
- server/src/api/models/common.py
- server/src/api/models/location/__init__.py
- server/src/api/models/location/spawn_info.py
- server/src/api/socket/location.py
- server/src/api/socket/shape/__init__.py
- server/src/db/models/base_rect.py
- server/src/db/models/line.py
- server/src/db/models/shape.py
- server/src/db/models/shape_type.py
The socket event `Location.Spawn.Info.Get` was receiving all shape information for the related spawn objects, although only the location and some id/name info was needed.
This PR also cleans up a couple of related concepts:
- The aforementioned socket event no longer uses a separate return event, but uses the event callback that socket.io provides
- server Shape now has a proper getter and setter for center
- server Shape subtype center offset no longer requires unused x,y arguments
- PositionTuple uses floats instead of ints
> feat(Tech: Spawn): Reduce amount of data passed in spawn info requests

- CHANGELOG.md
- server/src/api/http/admin/users.py
- server/src/api/socket/room.py
- server/src/api/socket/shape/__init__.py
- server/src/db/models/user.py
- server/src/db/typed.py
- server/src/planarserver.py
The typing wrapper we provide for peewee (the orm used by PA), was not correct for the `get_or_none` function. This fixed a couple of small mistakes here and there.
It also happened to fix a logic bug in the code responsible for kicking players, allowing the Co-DM to kick the main DM.
> bug(Tech: Types): Fix typing of database get_or_none

- client/src/dashboard/Assets.vue
My latest refactor of some internals, left the `..` folder always visible. This PR fixe that.
> bug(AssetManager): Fix the .. folder always being visible

- CHANGELOG.md
- server/src/api/socket/asset_manager/core.py
- server/src/api/socket/shape/__init__.py
When removing an asset from the asset manager a check is done to see if the actual image that is stored on disk has to be removed.
This check only looked at whether any other asset was still using the image. This could result in the issue where you drop an asset in a campaign, then remove the asset and the shape can no longer be rendered because the disk-image was removed as part of the asset removal procedure.
This PR fixes this, by also checking if any shapes are still depending on the image before removing it. Additionally when removing a shape with an image, the same cleanup check is also run now.
> feat(Asset): Improve asset disk removal conditions

- CHANGELOG.md
- client/src/dashboard/Assets.vue
When changing folders both a `Folder.Get` and a `Folder.GetByPath` call would be sent to the server. Only one of these has to happen as they return the same information.
> feat(AssetManager): Reduce server calls on folder change

- client/src/apiTypes.ts
- client/src/assetManager/AssetContext.vue
- client/src/assetManager/AssetShare.vue
- client/src/assetManager/emits.ts
- client/src/assetManager/events.ts
- client/src/assetManager/index.ts
- client/src/assetManager/state.ts
- client/src/assetManager/utils.ts
- client/src/core/components/modals/AssetPicker.vue
- client/src/dashboard/Assets.vue
- client/src/fa.ts
- server/src/api/helpers.py
- server/src/api/models/asset/__init__.py
- server/src/api/models/asset/share.py
- server/src/api/socket/__init__.py
- server/src/api/socket/asset_manager/core.py
- server/src/api/socket/asset_manager/ddraft.py
- server/src/api/socket/asset_manager/share.py
- server/src/db/all.py
- server/src/db/models/asset.py
- server/src/db/models/asset_share.py
- server/src/db/typed.py
- server/src/save.py
- server/src/transform/to_api/asset.py
This PR adds the capability to share assets with other users on the same server.
Either singular files or entire folders can be shared.
These are shared in either a "view only" or an "edit" mode. In the latter mode users can fully modify the contents of a folder including addition as well as removal of assets, so be warry with this right.
In view mode, the only thing the user can do is see the contents of the folder and drop the assets in their campaigns.
When a campaign is shared it appears in the root folder of the receiving user in the form of `${ownerName}-${assetName}` with a special icon signifying it was shared with you.  You're free to rename and move this asset around and it won't affect anything for the original user. This is purely a n anchor to link into the real asset when …
> feat(Asset): Add asset sharing

- CHANGELOG.md
- client/src/dashboard/games/CreateGame.vue
- client/src/dashboard/games/GameList.vue
- client/src/dashboard/games/types.ts
- client/src/fa.ts
This PR tackles some low hanging fruit: sorting the game listing in the dashboard.
Up until now the shown campaigns were always ordered in whatever order the database spit them out, which is usually not really useful.
This PR modifies this behaviour to sort by most recently used and also offers the option to sort alphabetically in both directions.
At this moment these choices are not remembered in any way.
> feat(Dashboard): Add campaign sorting

- server/src/api/http/mods.py
This fix creates a mods folder if it doesn't exist yet.
> bug(Mods): Fix missing mods folder crashing server

- CHANGELOG.md
- client/src/game/interfaces/shape.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/variants/circle.ts
- client/src/game/vision/state.ts
The vision system uses points to do its magic. Given that a circle by definition has infinite points, this was originally "solved" by just approximating it with a bounding box, resulting in all circle-based light-blockers to appear as squares.
This is obviously not ideal and has lead me to use polygons for all things circle based.
This PR sets out to fix this discrimination against circles by approximating them with a polygon based on the radius of the circle. it will not be a 100% perfect overlap, but it should be close enough for your traditional needs.
> feat(Circle): Approximate circle with polygon for vision

- server/src/api/socket/character.py
The server was fine with creating characters for shapes that already have a character. Causing invalid state for the previous character as it no longer points to a shape.
> bug(Character): Fix server not rejecting character creation for shape already with character

- client/src/game/systems/characters/index.ts
Internally PA uses a reactive variable `activeCharacterId` for some character related things. One of these things is to show the `Create Character` line in the shape context menu. Which should dissappear if the aformentioned variable has a value.
This variable was only being set when the active selection changed, which means that when creating a character using the shape context-menu this property was not being set as the selection didn't change.
> bug(Character): Fix activeCharacterId not immediately updating upon character creation time

- CHANGELOG.md
- client/src/game/layers/variants/fowLighting.ts
I'm somewhat confused by this one. As I have the feeling this didn't use to happen, but I can't immediately find something in the code that refutes this.
Either way, it's fixed now.
> bug(Lighting): Fix empty auras lighting up the entire map

- CHANGELOG.md
- server/src/api/socket/shape/__init__.py
A change in the last release broke the teleport functionality slightly.
Teleports still work correctly, but the event to remove them from the old location on active sessions is no longer being sent. This is fixed on a refresh of the page.
> bug(Teleport): Fix teleport remove event no longer being sent

- CHANGELOG.md
- client/src/game/shapes/variants/polygon.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/ui/tools/SelectTool.vue
When a polygon is rotated, the edit UI was still showing as if the shape had no rotation.
This is fixed. The various edit options (add point, cut polygon, remove point) have also been updated to take the rotation into account.
This fixes #1318
> bug(Polygon UI): Fix polygon edit UI not taking rotation into account

- CHANGELOG.md
- client/src/game/ui/tools/DiceTool.vue
I found that client sent zero results when player clicked `GO` botton in the dice tool due to an empty dice list. This would cause a little confusion when players accidentally click `GO` multiple times. 
A length check on diceArray would easily fix this issue. I have also add one line in the CHANGELOG.
> Add length check for diceArray

- CHANGELOG.md
- server/src/api/socket/shape/__init__.py
When using a ruler, the server log was getting flooded with some messages about unknown shapes.
This was due to a change in the code a couple of months ago that did not take temporary shapes into account.
In principle this is not ruler exclusive, but it's the biggest offender.
This had no effect on the users or actual play.
> bug(Ruler): Fix server log spam

- client/src/game/api/events.ts
- client/src/game/clear.ts
- client/src/game/systems/characters/index.ts
- client/src/game/systems/index.ts
- client/src/game/systems/modals/index.ts
- client/src/game/systems/players/index.ts
- client/src/game/systems/position/index.ts
- client/src/game/systems/settings/location/index.ts
- client/src/game/systems/settings/players/index.ts
- client/src/game/ui/menu/MenuBar.vue
After the small enhancements to modals I did earlier, something potentially broke when leaving a campaign.
This is now fixed.
> bug(Modal): Clear modal state on exit

- server/src/save.py
Fix number 2 for the save migration for notes. I was using sqlite syntax that the sqlite version on Docker was not yet familiar with. As there is no special requirement on this new syntax I've changed it to use an older syntax.
> bug(Notes): Don't use newer sqlite syntax

- server/src/save.py
There was a small mistake causing the migration to fail if you had any shape with notes attached to a character that is not on the map currently.
> bug(Notes): Fix save migration for hidden character shapes with notes

- client/src/game/shapes/templates.ts
For the new vision mode a change was made from boolean to number representation to accomodate multiple types.
When dropping assets on the map this was not taken into account. This PR fixes this with a bandaid.
A more proper patch system for templates should be made.
> bug(Template): Fix vision_obstruction migration

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/api/emits/location.ts
- client/src/game/api/events/location.ts
- client/src/game/dropAsset.ts
- client/src/game/shapes/templates.ts
- client/src/game/systems/settings/location/index.ts
- client/src/game/systems/settings/location/models.ts
- client/src/game/systems/settings/location/state.ts
- client/src/game/ui/settings/location/GridSettings.vue
- server/src/api/models/location/settings.py
- server/src/api/socket/location.py
- server/src/db/models/location_options.py
- server/src/save.py
**[This performs a database migration]**
This is a new feature that at the same time also is a bugfix.
It adds a new setting to the location grid setting.
context:
PA has an option to auto scale assets when dropped if they have a specific format in their name. For example goblin_1x1 should in normal circumstances fit exactly 1 grid cell, dragon_3x3 should be resized to 3 by 3 grid cells.
The existing implementation was erroneously using a method to do this based on the common 5ft system to automatically adjust this when a location had a bigger size (e.g. 10ft maps would automatically make something_2x2 fit in 1 cell)
This however completely breaks for everything that does not use the 5ft system, be it because you use SI units or because your system uses something custom or you enjoy …
> feat(LocationSettings): Add drop ratio to grid settings

- CHANGELOG.md
- client/src/game/dropAsset.ts
- client/src/game/interfaces/shapes/toggleComposite.ts
- client/src/game/shapes/variants/toggleComposite.ts
- client/src/game/systems/characters/index.ts
- client/src/game/ui/contextmenu/ShapeContext.vue
- client/src/game/ui/settings/shape/VariantSwitcher.vue
- server/src/api/socket/shape/__init__.py
- server/src/db/models/composite_shape_association.py
Variants/ToggleComposites are a common source of issues and the character system wanted to experience this as well.
This PR closes a bunch of bugs related to the use of shapes with variants as characters.
Variants are completely separate shapes behind the scenes currently and only one of them is getting marked as a character, which ended up causing funky bugs when another variant is active and you try to interact with the character system. This ranged from not being able to move a character by dropping it using the menu to actually removing shapes when deleting them instead of preserving them for later use.
This PR mostly prevents issues with shapes that are not bugged yet.  So if you have some weird shenanigans already going on, you might have to remake the shape/character and get rid of …
> bug(Character): Fix multiple variant bugs

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/dice/state.ts
- client/src/game/tools/variants/dice.ts
- client/src/game/ui/tools/DiceTool.vue
- server/src/api/models/dice/roll.py
Resolves #1327
Resolves #1328 
Note that in `client/src/game/dice/state.ts`, I just use the first element of result list because I don't quite understand why the list always contains only one result item. Using the first item just works well.
> feat(DiceTool): Resolve #1327, #1328

- CHANGELOG.md
- client/src/game/ui/SelectionInfo.vue
Replace the original quick edition of aura values with quick toggling and rotating.
RotationSlider is only shown when angle<360.
The toggling function is copied from TrackerSetting.vue. I thought it would be better if there is a unified function to access these states (also useful for mod API). It works at present though.
btw, I noticed that the orbit of RotationSlider's "slider" is actually larger than the rendered one. would that be a bug?
> feat(SelectionInfo): Quick toggle or rotate for auras

- CHANGELOG.md
- client/src/core/components/RotationSlider.vue
The rotation slider component, currently unique to auras, had a desync issue that if multiple are tracking the same aura.
This did not occur before, because that situation never happened before, but since the changes of #1352 this behaviour became apparent.
> bug(RotationSlider): Fix (de)sync issues

- CHANGELOG.md
- client/src/core/components/RotationSlider.vue
The anchor that shows the current angle on the rotation slider would not stick properly to the rail for certain angles.
> bug(RotationSlider): Fix anchor position

- client/src/fa.ts
- client/src/game/ui/SelectionInfo.vue
- client/src/game/ui/notes/NoteDialog.vue
- client/src/game/ui/notes/NoteEdit.vue
- client/src/game/ui/notes/NoteList.vue
The icon used for note popouts has been changed, as I found the previous version to imply too much that a completely new window would open (which is something that I want to add later).
The quick info icon for opening the note manager has also changed to a cog wheel, and the order of the two icons has changed.
Additionally the [share with players] action in the note dialog is removed as it did nothing and it feels somewhat out of place for that view.
> feat(Notes): Change icons used for popouts

- client/src/core/components/toasts/SingleButtonToast.vue
- client/src/game/systems/notes/events.ts
When gaining access to a note, you'll now receive a notification in the top right of the screen with a quick open action.
This helps with flows where a note is shared with the players after a discovery. Asking the players to manually open the note manager and searching for it, is quite a bother.
> feat(Note): Show notification on note share

- client/src/game/ui/SelectionInfo.vue
The quick info section for notes provides a toggle to expand/collapse notes.
If there are no notes however it was still showing the cursor as a pointer, which can be confusing.
> style(Notes): Don't show pointer if there are no notes in quick info

- server/src/api/socket/location.py
It was possible for a note to appear twice in the selection info.
This was caused by the server sending some notes multiple times if certain conditions were met. (e.g. being the creator of the note but also having default view access)
> bug(Notes): Fix duplicate note listings in selection info

- client/src/game/ui/tools/DiceTool.vue
Since the changes to the dice tool history UI, all other dice UI was being stretched quite heavily.
It still looks somewhat odd, but this PR addresses it somewhat.
A cleaner dice tool UI is in the works anyway.
> style(DiceTool): Don't stretch other dice UI elements when history is wide

- client/package-lock.json
- client/package.json
- client/src/core/components/modals/MarkdownModal.vue
- client/src/core/components/modals/SelectionBox.vue
- client/src/game/ui/Annotation.vue
- client/src/shims/vue3-markdown-it.ts
The note system uses a different markdown dependency (vue-markdown-render). This PR replaces usages of the previous dependency (vue3-markdown-it) and removes the dependency itself.
> chore(Deps): Remove old markdown dep

- CHANGELOG.md
- client/src/core/math.ts
- client/src/game/interfaces/shape.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/variants/baseRect.ts
- client/src/game/shapes/variants/circle.ts
- client/src/game/shapes/variants/line.ts
- client/src/game/shapes/variants/polygon.ts
- client/src/game/shapes/variants/text.ts
- client/src/game/shapes/variants/toggleComposite.ts
- client/src/game/tools/variants/draw.ts
- client/src/game/tools/variants/select/index.ts
Resize snapping (i.e. resizing a shape with snapping mode on) was no longer behaving smoothly due to the point being moved snapping to itself.
I'm not sure how long this behaviour was faulty, as I have snapping mode on by default.
> bug(Select): Fix resize snapping

- CHANGELOG.md
- client/src/game/shapes/variants/polygon.ts
Two bugs were fixed in this code.
The below image shows a blue polygon with in red what the contains check was actually going through.
The contains code was wrongly using code that filters out duplicate points, causing 2 edges to be completely skipped and a direct line being drawn between two vertices that are not connected.
Additionally the first and last points were also being connected even though the polygon is not closed.
> bug(Polygon): Fix code that checks if a certain point is on the polygon

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
The polygon edit UI shows a circle on the selected polygon to highlight where on the polygon you're currently tracing.
This circle would on first render seemingly cause a visual glitch by first appearing on (0, 0) before snapping to the polygon.
> bug(Select): Fix polygon edit UI visual glitch

- CHANGELOG.md
- client/src/game/systems/floors/index.ts
- client/src/game/systems/floors/state.ts
_This is a technical internal change_
An oversight on my end caused floors, layers and shapes to all become reactive, which isn't intended as this induces extra overhead that we aren't even using anywhere.
This PR changes the floorSystem state to only make the array holding floors and layers reactive, but not the individual items.
> bug(Reactivity): Fix floors, layers, shapes becoming reactive

- CHANGELOG.md
- client/src/game/interfaces/layer.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/systems/logic/tp/core.ts
- client/src/game/temp.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/ui/contextmenu/ShapeContext.vue
The Select Tool was fetching all shapes on a layer instead of only those in view which is obviously more performant.
> feat(Select): Update SelectTool to use onlyInView when fetching shapes

- CHANGELOG.md
- client/src/core/math.ts
- client/src/game/tools/variants/draw.ts
Similar to an earlier PR where this behaviour was fixed for the SelectTool resize, the drawtool was also having janky behaviour with snapping while dragging.
I thought I had fixed this together with the SelectTool stuff, but I only fixed it for polygon drawing, so this PR cleans it up for general shape drawing.
> bug(Draw): Fix draw resize snapping

- client/src/game/tools/variants/draw.ts
I forgot to handle the pointerUp event as well, oops.
> bug(Draw): Fix draw resize snapping part II

- client/src/core/grid.ts
- client/src/core/utils.ts
- client/src/game/interfaces/layer.ts
- client/src/game/rendering/basic.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/ui/tools/RulerTool.vue
- client/src/game/vision/te.ts
_WIP_
This PR adds an extra option called 'grid mode' to the ruler tool (and as a result the select tool as well when it's in ruler mode).
In grid mode the ruler calculates the distance between 2 points in terms of the number of grid cells it has to traverse (e.g. the number of squares in a square grid setup).
This results in something like:
Showing a total of 21 cells traversed which equals 105ft (with 1 grid = 5ft settings).
> feat(Ruler): Add grid mode

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/api/events/player/options.ts
- client/src/game/systems/settings/players/index.ts
- client/src/game/systems/settings/players/models.ts
- client/src/game/systems/settings/players/state.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/ui/settings/client/AppearanceSettings.vue
- client/src/locales/en.json
- server/generate_types.sh
- server/src/api/models/user/__init__.py
- server/src/db/models/user_options.py
- server/src/save.py
This PR adds a new client setting to configure the label format used for the ruler in grid mode.
It can be configured to only show the number of cells, only show the total distance or both.
This closes #777
> feat(ClientSettings): Add format for ruler label in grid mode

- CHANGELOG.md
- client/src/game/layers/variants/layer.ts
Moving a shape to the front or back was not immediately updating the screen until a second click or another event happened that updated the view.
This is a bug introduced with the sector system a while back.
This closes #1388
> bug(Move Front/Back): Fix delayed move layer order

- CHANGELOG.md
- client/src/core/grid.ts
- client/src/game/rendering/basic.ts
- client/src/game/shapes/shape.ts
- client/src/game/tools/variants/map.ts
- client/src/game/ui/tools/MapTool.vue
Another update in the recent chain of hex-grid improvements.
Previous PRs already fixed the most important aspects that also relate to the map tool,
but some small extra changes were necessary.
When resizing a square grid it's easy to determine a number of cells in both directions, for hex grids this is usually easy in 1 direction but less straight forward in the other. Additionally maps will rarely be cutoff cleanly in at least 1 of the 2 directions for the hex case, which can mess up the assumptions used by the map tool.
As a result I strongly recommend to ensure your dominant axis is counted properly and not worry too much about the auxiliary axis. Your dominant axis should be resized correctly, the other will very likely need some additional manual resizing, but that is just over 1 …
> feat(MapTool): Improve hex grid support

- client/src/game/shapes/shape.ts
When toggling the new oddHexOrientation property, the value is properly saved to the backend, but during loading it is not properly processed causing it to fall back to the default on the client.
> bug(Properties): Fix oddHexOrientation not loading properly

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/api/emits/shape/options.ts
- client/src/game/api/events/shape/options.ts
- client/src/game/interfaces/shape.ts
- client/src/game/shapes/shape.ts
- client/src/game/systems/properties/index.ts
- client/src/game/systems/properties/state.ts
- client/src/game/ui/settings/shape/GridSettings.vue
- client/src/game/ui/settings/shape/PropertySettings.vue
- client/src/game/ui/settings/shape/ShapeSettings.vue
- client/src/game/ui/settings/shape/categories.ts
- server/src/api/models/shape/shape.py
- server/src/api/socket/shape/options.py
- server/src/db/models/shape.py
- server/src/save.py
- server/src/transform/to_api/shape.py
To snap a shape to the grid, PA needs to know how many grid cells something is supposed to represent.
PA does this by doing a best effort guess from the width/height of the shape.
This can however for multiple reasons be wrong (e.g. it might be an asset with a lot of transparency causing the width to be inflated).
This PR adds a new option to manually configure the size instead.
It should be noted that this is a single number that applies in all directions.
A known bug right now is that the UI will not update the inferred size if you resize a shape while the UI is open.
> feat(Shape): Add manual size hinting

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/core/grid/hex.ts
- client/src/core/grid/index.ts
- client/src/core/grid/types.ts
- client/src/game/api/emits/shape/options.ts
- client/src/game/api/events/shape/options.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/rendering/grid.ts
- client/src/game/shapes/shape.ts
- client/src/game/systems/properties/index.ts
- client/src/game/systems/properties/state.ts
- client/src/game/ui/settings/shape/GridSettings.vue
- server/src/api/models/shape/shape.py
- server/src/api/socket/shape/options.py
- server/src/db/models/shape.py
- server/src/save.py
- server/src/transform/to_api/shape.py
This PR adds another entry to the new grid tab in the Edit Shape dialog.
It adds a toggle called 'show cells' along with a couple of configuration settings when toggled on.
When enabled an outline of the grid cells the shape occupies will be shown below it.
e.g.
The asset itself is just the image of the mech, the shown hex behind it is rendered by this new feature.
> feat(Shape): Add Shape.showCells

- CHANGELOG.md
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/spell.ts
- client/src/game/ui/settings/location/GridSettings.vue
I realized that PA doesn't allow decimal numbers as a grid unit size while trying to make a regional map for use in an army combat scenario. I wanted to make hexes each 0.1 miles, and the UI appeared to let me, but it was silently being rejected.
I thought that it wouldn't hurt anything to allow such grid measurements, even if not very applicable to most situations. I feel like with the hex grid now working much smoother, it allows for more regional or overworld style map usage, at least in games like Pathfinder.
While I was working on this, I needed to make the 'Grid Mode' of the ruler tool function and noticed a couple bugs in the distance shown on screen. I fixed those issues while I was in working on that file since they were rather straightforward. Those being
- Measuring from a …
> Feat(Ruler): Allow grid unit steps less than 0. Also fixes incorrect counting of cells in grid mode.

- CHANGELOG.md
- client/src/game/ui/notes/NoteList.vue
The filter that ensure that only notes related to the shape or shown was not rerunning when you changed shapes until some other filter was applied. This caused the shape note listing to sometimes show notes from the previous shape.
> bug(Notes): Fix ghost notes for shapes

- CHANGELOG.md
- client/src/game/ui/notes/NoteList.vue
When opening the note UI in shape filter mode, it's supposed to remain open on the shape that was initially selected.
When selecting another shape with the selection tool, the name of the shape shown in the note UI would update to the newly selected shape, while the actual note listing would still show the notes of the originally selected shape.
This has been rectified so that the shape name does not update.
> bug(Notes): Fix note shape name changes

- client/src/game/ui/settings/shape/GridSettings.vue
The oddHexOrientation property is only relevant for hex grids, and is thus appropriately placed in the Hex Settings.
The check to show those fields was however only being applied to the title and not the actual oddHexOrientation row, woops.
> bug(GridSettings): Only show oddHexOrientation for hex grids

- CHANGELOG.md
- client/src/game/systems/README.md
- client/src/game/systems/groups/index.ts
- client/src/game/systems/groups/models.ts
- client/src/game/systems/groups/state.ts
- client/src/game/systems/properties/index.ts
- client/src/game/ui/settings/shape/GroupSettings.vue
The Groups tab in the 'Edit Shape' dialog historically had some issues with certain things not immediately updating in the UI until a fresh reselect was done of the shape.
In a recent update however the UI became broken in general, always showing the leftmost options in the settings regardless of the actual option set.
This PR handles all of the above at once. Original behaviour for the settings has been restored and the areas that were not responsive should now update on the spot properly.
> bug(Groups): Fix shape edit groups UI

- CHANGELOG.md
- server/src/api/socket/initiative/__init__.py
Fixed a query in sockets.initiative.
PeeWee allows just providing an id to it's query methods, such as get_or_none, but that requires the id to be an int. Since the Shape table has guid/string ids, the single argument was instead being passed as the entirety of the WHERE clause in the sql query.
This caused Sqlite to cast it to an int by only any digits at the start of the id. The result was if the id started with a non-zero digit, the query evaluated to True, and would return a shape, allowing the initiative to be updated. But if the id started with a letter, it would evaluate to false, so the query would return no results, which was interpreted as an invalid Shape. 
In searching the rest of the code base, it does seem like the other queries are correctly using keyword args, so this …
> Fixed query when checking for valid Shape on initiative change

- CHANGELOG.md
- client/src/game/systems/floors/index.ts
- client/src/game/systems/floors/state.ts
This fixes #1411 
In #1382 a change was made to prevent some things from becoming reactive when they shouldn't. Layers and Shapes being the prime targets, but Floors were also included, and that ended up being a mistake.
This caused the floor UI to no longer update, this is now reverted for Floors specifically.
> bug(Floors): Fix floor UI no longer being reactive

- client/src/game/interfaces/shape.ts
- client/src/game/shapes/shape.ts
Resizing points to snap to the grid was not working correctly for rotated shapes.
This fixes #1405
> bug(SelectTool): Fix resize to grid for rotation

- client/src/game/systems/notes/events.ts
In #1413, the Note.Shape.Add event was properly handled so that clients saw the changes immediately. I noticed that Note.Shape.Remove events were still not being received properly.
Turns out it wasn't implemented client-side. This PR implements handling of these events. Finishes closing #1410
> bug(Notes): Implement client handling of Note.Shape.Remove events

- CHANGELOG.md
- client/src/game/api/events/shape/core.ts
- client/src/game/interfaces/layer.ts
- client/src/game/interfaces/shape.ts
- client/src/game/layers/variants/layer.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/utils.ts
- client/src/game/systems/notes/index.ts
- client/src/game/temp.ts
Note icons are currently drawn as an ordinary shape which works in most ways. Since they are lumped in with all other shapes in a given layer, there exist some problems such as #1406 when it comes to rendering priority. The shape could become obscured by the shape it is supposed to be attached to.
This PR introduces a new class of shapes in a layer called dependent shapes. These are treated as shapes that depend on another 'parent' shape to exist and are therefore always drawn on top of the parent shape but still remain underneath other overlapping shapes as one would expect. This new class can be utilized to allow drawing of other icons such as an invisibility indicator in the future.
This solves #1406.
> Set note icons into their own category of shape for rendering

- CHANGELOG.md
- client/src/game/ui/Annotation.vue
While basic markdown was working as it should, annotations were rendering HTML elements within notes as raw text, while the note view would properly render the same note.
I believe this bug was created with commit  [80c6549](https://github.com/Kruptein/PlanarAlly/commit/80c6549447486697b6bd0e4949016d7a3b2da6b0) though I didn't thoroughly check to be sure. I did verify that this issue was present in release 2024.1 and updated the changelog accordingly.
> Fix annotations not correctly handling HTML in markdown notes

- CHANGELOG.md
- client/src/game/interfaces/shape.ts
- client/src/game/interfaces/shapes/asset.ts
- client/src/game/shapes/shape.ts
- client/src/game/shapes/types.ts
- client/src/game/shapes/variants/asset.ts
- client/src/game/systems/notes/index.ts
- client/src/game/temp.ts
This fixes #1408
As mentioned in the ticket, the position of the note icon on the map is pretty random if your shape is not a nice 1x1. It was using a hardcoded (0, -30) vector compared to the refPoint of the related shape, which makes little sense if the shape starts having bigger dimensions.
The current fix is to always render using the bounding box bottom left corner of the shape and by applying a scaling factor based on the same bbox to adjust the size of the note icon based on the size of the related shape. This functions similarly to what badges currently do.
This allows it to work decently with rectangles and circles. It's still pretty wonky for polygons and text shapes, but I'm honestly not sure if there really is a decent use case for attaching a note with a specific icon to …
> bug(Note): Fix note position when drawn on shape

- CHANGELOG.md
- client/src/game/systems/notes/index.ts
When removing a shape, it would still appear in related notes' "Shapes" tab until a refresh.
This fixes 1 part of the issue mentioned in #1416
> bug(Notes): Fix shape note removal

- .github/workflows/codeql-analysis.yml
- .github/workflows/docker.yml
- .github/workflows/pull_request.yaml
These were still using node 16 runtimes, they have been updated to the latest versions using node 20
> chore: Update gh action versions

- CHANGELOG.md
- client/src/game/systems/position/index.ts
The various client settings to modify the grid (e.g. physical board, grid pixel size) would upon modification seemingly not do anything. Only when a refresh or a zoom change happened would the screen readjust.
This PR fixes this behaviour.
> bug(Grid): Fix grid client settings not immediately updating the screen

- client/src/game/tools/variants/draw.ts
Another fix to draw tool snapping in this release cycle introduced another bug; When drawing multiple shapes after each other the pointer would not snap to the most recently drawn shape. There was a workaround by swapping between tools, but it has now been properly fixed in this PR.
> bug(DrawTool): Fix no longer snapping to most recently drawn shape

- CHANGELOG.md
- client/src/game/tools/variants/draw.ts
When snapping is enabled the draw tool would snap the endpoint of for example a rectangle to the grid on release. It would however not do the same for the first mouse press. This has been rectified.
> bug(DrawTool): Fix initial mouse press not snapping

- CHANGELOG.md
- client/src/game/shapes/variants/baseRect.ts
- client/src/game/tools/variants/draw.ts
If while drawing a rectangle you move over an axis (e.g. you move the cursor left of the current left rectangle border) some funky small changes to points could occur, causing the cursor to no longer be attached to the rectangle.
> bug(DrawTool): Fix small issues with rectangle drawing when crossing over an axis

- CHANGELOG.md
- client/package-lock.json
- client/package.json
- client/src/apiTypes.ts
- client/src/game/api/events.ts
- client/src/game/clear.ts
- client/src/game/systems/characters/index.ts
- client/src/game/systems/chat/emits.ts
- client/src/game/systems/chat/events.ts
- client/src/game/systems/chat/image-loader.ts
- client/src/game/systems/chat/index.ts
- client/src/game/systems/chat/md.ts
- client/src/game/systems/chat/models.ts
- client/src/game/systems/chat/state.ts
- client/src/game/systems/index.ts
- client/src/game/systems/modals/index.ts
- client/src/game/systems/models.ts
- client/src/game/systems/players/index.ts
- client/src/game/systems/settings/location/index.ts
- client/src/game/ui/Chat.vue
- client/src/game/ui/Floors.vue
- client/src/game/ui/UI.vue
- server/src/api/models/__init__.py
- server/src/api/models/chat.py
- server/src/api/socket/__init__.py
- server/src/api/socket/chat.py
This adds a collapsible simple chat feature to the bottom left of the screen.
The initial scope is small on purpose.
It currently offers the ability to send basic text based chats. There is markdown support, but no HTML can be used directly. (e.g. `**test**` will show up bold `<b>test</b>` won't.)
URLs will automatically be clickable without using the normal markdown syntax for urls, and will open in a new tab.
Image URLs specifically will automatically be converted to images in the chat container and can be clicked to see them in larger scale.
A later PR will arrive that allows you to disable this feature entirely on a campaign level if it's something you don't need.
> feat(Chat): Add a simple ephemeral chat experience

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/api/events.ts
- client/src/game/systems/room/emits.ts
- client/src/game/systems/room/events.ts
- client/src/game/systems/room/index.ts
- client/src/game/systems/room/state.ts
- client/src/game/ui/Chat.vue
- client/src/game/ui/UI.vue
- client/src/game/ui/settings/dm/DmSettings.vue
- client/src/game/ui/settings/dm/FeatureSettings.vue
- client/src/game/ui/settings/dm/categories.ts
- client/src/game/ui/tools/Tools.vue
- client/src/locales/en.json
- server/src/api/models/room/info/__init__.py
- server/src/api/socket/location.py
- server/src/api/socket/room.py
- server/src/db/models/room.py
- server/src/save.py
This adds a new tab to the DM settings called 'Features'.
It's used to enable or disable certain features for the entire campaign (i.e. all locations).
Currently this is limited to two features:
- chat
- dice
Both of these will be configured to be enabled by default for all existing and new campaigns.
It's my intention to have some setup/start screen when making a new campaign in which you would preconfigure more things like these features.
> feat(DM-Settings): Add Features tab

- CHANGELOG.md
- client/src/game/Game.vue
- client/src/game/input/keyboard/up.ts
- client/src/game/models/shapes.ts
- client/src/game/models/tools.ts
- client/src/game/operations/movement.ts
- client/src/game/systems/selected/collapse.ts
- client/src/game/systems/selected/index.ts
- client/src/game/tools/events.ts
- client/src/game/tools/tool.ts
- client/src/game/tools/variants/draw.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/select/index.ts
- client/src/game/ui/contextmenu/ShapeContext.vue
This PR adds a new feature to PA tentatively called "selection collapsing".
When moving a selection of multiple shapes around, it can often be a pain to navigate tight corridors or corners, due to some shapes in your selection colliding with walls.
This is an approach to help you as a DM or even player to circumvent these issues.
While you have a selection and are actively dragging it (e.g. your left mouse is down) you can hold the "c" key (c for collapsing; not to be confused with ctrl+c!).
While this key is down, the selection will collapse to your currently selected shape. When you release the key the shapes will expand out again.
An alternative is to right click on a shape in your selection and choose the new context menu item "Collapse". Later on you can right click the shape again …
> feat(Select): Add collapse selection support

- CHANGELOG.md
- client/src/game/rendering/grid.ts
- client/src/game/shapes/variants/hex.ts
- client/src/game/tools/variants/spell.ts
- client/src/game/ui/tools/SpellTool.vue
When in hex grid mode, it makes more sense to have the spell tool output hexes instead of squares.
It's mostly still WIP for two reasons:
- FA does not have a free hexagon icon, I'm currently just using the square icon, but that might be confusing
- It basically duplicates code for hex rendering from somewhere else, but to make it a Polygon shape instead of direct canvas calls
The latter should be unified
> feat(Spell): Render hexes in spell tool when using hex grids

- client/src/game/ui/tools/SpellTool.vue
My earlier hex-grid spell change was supposed to also change it so that the step-size for the size input would not jump by 5 but by 1.
I did a last minute refactor of something though and forget to adapt the step size accordingly :)
> bug(Spell): Fix stepsize for hex grids

- CHANGELOG.md
- client/src/game/tools/variants/ruler.ts
When using grid mode and pressing spacebar to start a new ruler, the ruler end snaps to the center of the current cell before starting the new ruler. This snap was not sent over the socket to other clients, causing the rulers to look disjointed for other clients.
> bug(Ruler): Fix spacebar ruler snap in grid mode

- CHANGELOG.md
- client/src/game/tools/variants/ruler.ts
This is a small change that changes the default settings to share rulers with other users.
In practice most rulers I or my players draw are shared with each other, so changing this makes more sense.
> feat(Ruler): Default to share with other users

- CHANGELOG.md
- client/src/game/ui/tools/SelectTool.vue
Having to swap to the ruler tool to configure visibility and then back to the select tool is an awkward setup.
It's not clear while you're in the select tool whether or not the ruler will be shared unless you first check the ruler tool.
This PR adds all the ruler UI toggles to the select tool, so that no swapping is required.
These toggles are synchronized with the ones in the ruler.
> feat(Select): Add ruler settings to select UI

- CHANGELOG.md
- client/src/game/ui/tools/DrawTool.vue
When clicking on the "blocks movement" label in the vision settings of the draw tool, the related checkbox was not being toggled.
> bug(Draw): Fix draw tool movement block label toggle

- client/src/game/ui/tools/Tools.vue
The core reason for this PR is to fix the dice tool not remembering what you selected if you swap tools.
This PR changes all tools to use `v-lazy-show` over `v-if` which ensures the tools are not loaded until they are first selected, at which time they will remain loaded.
> bug(Dice): Fix dice tool state resetting

- CHANGELOG.md
- client/src/game/ui/notes/NoteEdit.vue
This fixes #1476 
As outlined in the issue, the note manager remembers the tab you had open when switching notes.
If you switch to a note that you only have view-access to, you're supposed to only see the view tab,
but instead if another tab was last visited, you see that tab.
This leaves you with no way to go to the view tab as all tabs are hidden in view mode.
Additionally you are given access to edit tabs, though interacting with any of them would not result in changed data as the server still rejects your changes, so no harm was possible here.
> bug(Notes): Fix edit tabs being leaked

- CHANGELOG.md
- client/src/game/ui/menu/MenuBar.vue
I noticed that as a player, you cannot access the NoteManager from the MenuBar like you can as the DM. The player has access to the NoteManager in other ways (eg right click menu of shape), so I feel like it would be nice to have a consistent way to open for them. This would also allow them access if there are only notes without shapes attached.
> feat(Notes): Add Notes button to player's MenuBar

- CHANGELOG.md
- client/src/game/systems/notes/index.ts
Fixes #1480 
When changing locations the note manager could get stuck in an unusable state when it had a note open previously that should not be shown in the new location.
For now the resolution is just to change back to the list view when changing locations.
> bug(Notes): Reset node manager to list mode on location swap

- CHANGELOG.md
- client/src/assetManager/index.ts
- server/server_config.cfg
- server/src/api/socket/asset_manager/core.py
- server/src/db/models/user.py
This PR adds 2 server configuration options to control the limits of assets uploaded to the server by users.
A configuration to limit the max size of single files is present as well as a limit to the total amount of bytes a user has uploaded.
Both of these limits default to 0, which means unlimited. It's up to individual server admins to decide whether they want to limit this and by how much.
There is no visual indication as to how much storage you have left currently, but an error popup will appear if you exceed any of the two thresholds while uploading assets.
These limits only apply to newly uploaded assets. So users who are already exceeding the limits when these settings change, will not be affected.
As a server admin you can check the total size a specific user is occupying in the …
> feat(Assets): Add asset upload limits

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
This fixes #1484 
PA tracks internally which shapes are currently selected and the most prominent location of changes of this selection occur when you use the select tool to click on other shapes or deselect the active shape.
Before this PR, the select tool would immediately update the selection state when the `mouseDown` event is fired.  This PR changes this behaviour to wait until `mouseMove` or `mouseUp`.
When you're editing for example the name of a shape and you directly click on another shape or even just the map (causing a deselect), a bunch of browser events are fired. First the `mouseDown` event fires, which until now changed the selection info immediately, then the `change` event fires, which indicates that the name input field changed content and finally `mouseUp` is fired.
As …
> bug(Shape): Fix some properties not persisting correctly when modified

- CHANGELOG.md
- client/src/game/ui/notes/NoteList.vue
When there are enough notes for multiple pages to be present, the note filter was not resetting the page to 1, potentially causing the user to end up with seemingly no matching notes because they were on a different page.
This fixes #1485
> bug(Notes): Fix note filtering potentially giving blank page

- CHANGELOG.md
- client/src/core/components/modals/Modal.vue
When dragging modals around, they were not being brought to the foreground like happens when you click on a modal.
This is expected behaviour and is now fixed.
This fixes #1496
> bug(Modals): Fix modal drag not focusing

- CHANGELOG.md
- client/src/game/ui/notes/NoteEdit.vue
In NoteEdit.vue, the default edit permission for notes was not being handled, making it effectively non-functional, unless your username was 'default' ;). This change makes the NoteManager check for default edit permission as well as per-user.
I also noticed that the hard-coded string was in a few places in the NoteEdit file, so since I was going to add another instance of it, I decided to make it a constant and reuse it in multiple places instead. Hope that's alright to include in this.
> bug(NoteManager): Fix default edit access not working on notes

- client/src/game/tools/variants/select/index.ts
Fixes #1499 
While doing the select refactor in #1487 I accidentally changed a `.focus` call to act as if it was a `.set` call, causing the selection to be limited to the clicked shape instead of focusing on the shape without affecting the selection.
This caused multi drag no longer to work as it was always resetting the selection to just the clicked shape.
> bug(Select): Fix multi drag no longer working

- CHANGELOG.md
- client/src/game/ui/notes/NoteList.vue
Fixes #1495
The note manager search bar would overlap over other modals that are on top.
I'm not sure why it had a z-index to begin with as I generally dislike those, but I couldn't see a specific visual change when removed.
> bug(Notes): Fix search bar overlapping other modals

- CHANGELOG.md
- client/src/game/ui/notes/NoteEdit.vue
If the main note manager had a note open and your access levels for that note change such that you're no longer allowed to view it, the note manager would become an empty line that is no longer useable until you find a way to force load another note.
This PR changes it so that the View/Edit note UI will always return to list view when it can't render it's current note.
> bug(Notes): Return to list view if view access to open note is lost

- CHANGELOG.md
- client/src/game/ui/notes/NoteEdit.vue
- server/src/api/socket/location.py
- server/src/api/socket/note.py
Notes can be shared with other players using the access tab. Sometimes you just want to quickly share with all players and the 'default' access row that we currently have is very nice for that.
For local notes this is very intuitive. It shares whatever access rights the default row has with all players in the campaign.
For global notes this is less intuitive, because there is no real link to a campaign and thus to a set of default players.  The global note might be used in multiple campaigns with a variety of players. It has no home campaign.
This leads us to the present day where a global note with default access actually is shared with _all_ users on the server. This is not really ideal, so this PR removes the default access row for global notes. Where necessary share global notes with …
> bug(Notes): Remove default access level from global notes

- CHANGELOG.md
- server/remove-broken-shape-links.py
- server/requirements.txt
The last release upgraded the version of the db framework which seems to have introduced a bug in certain remove calls.
In practice this affects PA when a user removes a Character (note: Character is a specific concept, it's not about shapes in general). When this happens there is a chance for some data to be corrupted related to the character's shape. Any attempt to load a location with that shape will fail.
A script to remove shapes that are in this broken state has been added. See the CHANGELOG for details.
> hotfix(2024.3.1): Downgrade peewee + script to remove broken shape states

- CHANGELOG.md
- client/src/game/ui/notes/NoteDialog.vue
Fixes #1498 
The note popouts did not do a check to see if the client had edit access and thus allowed clients to locally edit a note.
The server rejected all of these edits, so they never were saved or shown to other clients.
> bug(Notes): Fix note popouts no longer editable without edit rights

- client/src/game/tools/variants/select/index.ts
A recent change to the internals of the select tool changed some things in regards to active selection tracking.
This was not properly propagated everywhere in the select tool. As such the mouse was not properly changing to the resize cursor when hovering over a point in build mode and the rotation UI would sometimes show up delayed (e.g. after moving the shape).
> bug(Select): Fix delay on resize and rotate UI indicators [dev]

- CHANGELOG.md
- client/src/fa.ts
- client/src/game/ui/notes/NoteList.vue
This adds an 'X' button on the right side of the searchbar in the NoteManager which will clear the current search query. It's never been a huge issue to not have it, but it's a pretty common feature for search boxes that I've gotten used to. This is just a minor change that I would like to see.
> feat(NoteManager): add a clear button to the searchbar

- client/src/game/ui/UI.vue
While working on locations, I noticed that the radial menu in the top left of the UI is drawn underneath the locations settings bar if it's open. This is only really noticable if you hover over the locations toggle of the radial menu, but I still felt like fixing it. Turned out to be a super easy change.
before | after
:---: | :---:
> style(UI): Fix radial menu showing under location settings bar

- client/src/fa.ts
- client/src/game/systems/notes/types.ts
- client/src/game/ui/notes/NoteList.vue
- client/src/game/ui/notes/TagAutoCompleteSearch.vue
This is one of the ideas I was talking about in https://github.com/Kruptein/PlanarAlly/pull/1500#issuecomment-2466251120.
I tried my hand at revamping the NoteManager's tag searching capabilities. I went through several ideas before deciding on this solution. I tried integrating tag bubbles in the search bar, tried implementing an autocomplete feature to the main search bar, and several other ideas that seemed good in concept but fell flat in reality.
This PR makes a few changes. Firstly the new functionality: Tag filtering is separate from the search bar entirely. I believe that this makes the search bar feel more accurate because it will by default only search for titles, which is what I want most of the time. Tags are instead handled in the "Filter" section just below the search bar. …
> feat(NoteManager): Improve filtering by tags in note search

- client/src/game/tools/variants/select/index.ts
_This issue was reported on discord._
The internal selection clear happened just 1 operation too early, causing the select UI to disappear on mouse up.
> bug(Select): Fix select tool UI disappearing [dev]

- client/src/core/components/modals/PanelModal.vue
- client/src/game/systems/ui/mods.ts
- client/src/game/systems/ui/state.ts
- client/src/game/ui/settings/client/ClientSettings.vue
- client/src/game/ui/settings/dm/DmSettings.vue
- client/src/game/ui/settings/location/LocationSettings.vue
- client/src/game/ui/settings/shape/ShapeSettings.vue
- client/src/mods/models.ts
The i18n PR added translated names to all PanelModal tabs which is nice, but not handy when we want to programmatically swap tabs to a specific one.
To ensure this is possible, this PR adds a specific new property to each tab called category that has an enum that can be used for programmatic reference regardless of locale
> chore: Add category to PanelModal tabs

- CHANGELOG.md
- client/src/assetManager/utils.ts
- client/src/core/components/modals/AssetPicker.vue
- client/src/core/models/types.ts
- client/src/dashboard/Assets.vue
- client/src/game/dropAsset.ts
- client/src/game/ui/menu/AssetNode.vue
- client/src/game/ui/settings/shape/PropertySettings.vue
- client/src/game/ui/settings/shape/VariantSwitcher.vue
- server/requirements.txt
- server/src/api/socket/asset_manager/core.py
- server/src/db/models/asset.py
- server/src/planarserver.py
- server/src/save.py
- server/src/thumbnail.py
When browsing assets in the asset manager, the full images are used as that's the only data we currently have.
This can become quite heavy if a lot of images are shown.
This PR adds support for thumbnails which are 200x200 in size. They are generated in webp and jpeg formats and are stored in the new special `thumbnails` folder in the assets directory. (default is `server/static/assets/`)
The first server boot after this change will start a background task to generate thumbnails for all existing assets. This might spit out some errors for some assets that could not be converted for some reason.  For those assets the full image will be used as a fallback when showing assets. The main reasons for this to fail is that either the image on disk no longer exists or that the image is too big.
> feat(Assets): Generate & Use thumbnails for assets

- server/src/api/socket/asset_manager/core.py
Small oversight in #1526 caused the storage of new files in hash subfolders that don't yet exist to fail.
> bug(Assets): Fix new assets not always saving due to missing folders

- CHANGELOG.md
- server/src/api/socket/shape/__init__.py
When moving shapes to a different location, the client sends which shapes to move and the server will move them and inform any client still on the old location which shapes to remove.
The server will check for each shape whether it's part of a toggle composite and move all variants along as well. It will also the variants to the list of shapes it sends to clients on the old location to remove.
The client however can sometimes also include the list of variants already in its original move request and the server was not handling this correctly, resulting in multiple requests to remove the same variants to be sent to some clients which would throw an error when they have to remove something a second time when it's already removed.
TL;DR The server now takes into account shapes already …
> bug(ToggleComposites): Fix server delete composite handling

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
When moving the point of an existing shape with the select tool you can snap to a point or the grid.
Snapping to points happens during the drag move as a visual indicator. These snaps would however sometimes be overridden on mouse up to be snapped to the grid instead.
This is inconsistent with the behaviour of the draw tool and also just not nice, so it's fixed.
> bug(Select): Fix resize snapping not respecting earlier snap

- CHANGELOG.md
- client/src/dashboard/games/GameList.vue
When clicking on a session that shares a name with another session, they would all expand as if clicked on.
> bug(GameList): Fix multiple sessions expanding

- CHANGELOG.md
- client/src/game/tools/variants/draw/index.ts
When using the draw tool in polygon mode, the vision redraw was only done at the very end of the shape completion (i.e. when right click is pressed)
It will now re-render on every point.
_I'm slightly confused as to when this broke as this is something that I use frequently and can't remember no longer behaving like this, oh well :D_
> bug(Draw): Fix polygon draw vision delay

- CHANGELOG.md
- client/src/game/layers/variants/fowLighting.ts
- client/src/game/layers/variants/fowVision.ts
- client/src/game/systems/access/index.ts
- client/src/game/systems/position/index.ts
- client/src/game/systems/settings/location/helpers.ts
- client/src/game/systems/settings/location/index.ts
- client/src/game/systems/settings/location/state.ts
- client/src/game/ui/tools/Tools.vue
- client/src/locales/en.json
This adds a quick toggle to the DM side to enable/disable LoS (line-of-sight) rendering, but only for the DM. (i.e. players will always see the LoS render if that location setting is enabled).
This allows DMs to easier check if their light setups are correct without having to add temporary shapes or play with the location settings potentially forgetting about it and spoiling things for the players.
> feat(LoS): LoS quick toggle for DM only

- client/src/game/ui/tools/Tools.vue
To prevent confusion, the new LoS DM quick toggle will only show up when LoS is enabled for the campaign/location.
> feat(Vision): Only show DM LoS toggle when relevant

- client/src/game/shapes/shape.ts
- client/src/game/shapes/variants/asset.ts
- client/src/game/tools/variants/select/index.ts
An update to the select code was a bit too strict and limited the DM itself also to vision access requirements for select purposes which we don't want.
> bug(Select): Fix DM not being able to select shapes without vision access

- client/src/game/systems/access/index.ts
When toggling access rights the sync to the server happens correctly, but the internal state was updated at a wrong time causing the old data to be used and ultimately the wrong visual render to happen.
> bug(Access): Fix access toggles not correctly updating

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
The select tool's draw box was being rendered on the same layer as the user is active. Which means that it will often be below the fog and thus partially invisible.
This can be pretty unintuitive for players when they have limited vision and just want to drag a simple big box.
It's now drawn on the draw-layer instead ensuring it's always visible.
> feat(Select): Render selection box over fog

- client/src/game/shapes/utils.ts
- client/src/game/tools/variants/ping.ts
- client/src/game/tools/variants/ruler.ts
- client/src/game/tools/variants/select/index.ts
I noticed the tools that have UI helpers (select/ruler/ping) were also re-rendering non-draw layers while nothing is really going on on the other layers. This was due to some generic vision update code in the access code. Though these tools don't really need access rights anyway.
This is ultimately a small tweak that won't contribute to any noticeable speed improvement, but can help me with debugging things.
> feat(Render): Remove render calls on non-draw layers for some tools

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
The rotation UI was obscured by fog, which is inconvenient for players.
> feat(Select): Move select rotation UI over fog

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
This bug was introduced with the improvements to selection sync handling in the last release.
> bug(Select0: Fix select rotation UI not showing when toggling mode

- client/package-lock.json
- client/package.json
A bug in the algorithm for handling multiple d100 rolls in the pa-dice library was resolved in version 0.7.1.
This fixes #1552
> bug(Dice): Multiple d100 rolls don't work properly

- .github/workflows/pull_request.yaml
We use tj-actions to detect if files were changed in either client or server and only run the proper actions. The action was apparently compromised though, so this first fix is to disable it.
> chore: disable tj-actions for now

- server/src/planarserver.py
When stopping the server, sometimes it would hang for a bit and another ctrl+c was necessary.
It turns out the db was never explicitly closed in the shutdown sequence.
> bug(DB): Properly close the db on shutdown

- CHANGELOG.md
- server/src/app.py
- server/src/planarserver.py
- server/src/state/__init__.py
- server/src/state/asset.py
- server/src/state/auth.py
- server/src/state/dashboard.py
- server/src/state/game.py
This cleans up the server shutdown sequence a bit.
- DB close is now ran in the on_cleanup hook instead of the on_shutdown hook.
- The dashboard sockets were not being cleaned up explicitly
- The asset socket was being cleaned up with the wrong namespace
- A text is printed on shutdown to ensure that the shutdown process started
> chore(Server): Update server shutdown sequence

- server/src/api/helpers.py
- server/src/api/socket/asset_manager/core.py
- server/src/api/socket/asset_manager/share.py
- server/src/api/socket/character.py
- server/src/api/socket/location.py
- server/src/api/socket/note.py
- server/src/api/socket/shape/__init__.py
logger.warn was long deprecated and does no longer exist in python 3.13
> chore: Use logger.warning instead of logger.warn

- CHANGELOG.md
- client/src/dashboard/Settings.vue
- client/src/locales/en.json
There is no visual indication whatsoever that informs you that a change to the email actually did something in the dashboard settings UI.
I was even under the impression that modification was actually not possible, but it turns out any change is saved. This PR adds a small notification popup to ensure this is slightly more obvious.
> chore(Settings): Success notification on email change

- client/src/core/components/modals/PanelModal.vue
This is a purely internal technical change that passes a computed prop to the panel tabs so that they can act on being specifically selected.
> chore(Tech: Modals): Add a prop to PanelModal tabs to learn if they're selected

- CHANGELOG.md
- client/src/core/components/slider/SliderDot.vue
- client/src/game/ui/SelectionInfo.vue
- client/src/game/ui/UI.vue
When modals are open and in the top-right, there is the odd behaviour of the selection info and the zoom bar overlapping the dialog which is kinda jarring.
This PR changes those elements to be lower in the UI stack. For the selection info however it will still pop-over the active dialog if you hover over a visible section of it.
> chore(UI): Move zoom & selection info UI behind modals

- server/src/__init__.py
This fixes some cases where the database could be opened before the config was read. This could mean the wrong `save_path` was being used.
This primarily affects non-default server usage. (e.g. using a python shell)
> bug(Config): Ensure config is always loaded before database setup

- server/src/db/models/user.py
- server/src/save.py
Hi,
This merge will address https://github.com/Kruptein/PlanarAlly/issues/1589 by adding a `unique` constraint to usernames.  After setting up my dev environment, I attempted to create two `admin_test` users and it failed as expected:
```bash
>>> from src.db.all import User;
>>> User.create_new('admin_test', 'change_me')
2025-05-05 12:25:36,251 - CRITICAL - Uncaught exception (logs.py:33)
Traceback (most recent call last):
File "/home/egg/code/PlanarAlly/server/.venv/lib/python3.13/site-packages/peewee.py", line 3322, in execute_sql
cursor.execute(sql, params or ())
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: user.name
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<python-input-2>", line …
```
> fix: Add unique constraint to usernames

- CHANGELOG.md
- client/src/core/components/contextMenu/ContextMenuSection.vue
A bug in the context menu handling wiped the selection state, causing the remove action to no longer be functional.
> bug(Assets): Fix asset context menu remove action no longer working

- CHANGELOG.md
- client/src/dashboard/Assets.vue
The dashboard's asset context menu styling was being applied to the in-game asset context menu when the dashboard asset manager was opened first.
Closes #1586
> bug(Assets): Fix asset context background being wrong in some cases

- CHANGELOG.md
- client/src/dashboard/Assets.vue
I'm confused that linting didn't catch this tbh, the import was straight up missing.
> bug(Assets): Fix asset upload bar missing in dashboard

- CHANGELOG.md
- client/src/assets/ui/drag.ts
Dropping an asset that you only have shared-view permission over on the map was no longer working. The drag handler was a bit too strict, this has been resolved.
> bug(Assets): Fix shared asset map drop not working

- CHANGELOG.md
- client/src/game/systems/properties/index.ts
We generally do not trigger re-renders when movement blockers are toggled as they tend to do nothing visually.
In 2025.1 however we introduced default draw colours which can change the colour of a door when it's open or closed. If a door is toggled and it is a movement only toggle, the colour of the door would not immediately change until something else caused a rerender (e.g. some mouse interaction).
This would not happen if the vision was also toggled as that already causes a re-render.
This PR now also re-renders on movement toggles. This will likely have an almost invisible impact on performance.
> bug(Doors): Fix movement only door toggle not re-rendering

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
When another system causes shape deselect (e.g. keyboard shortcut) the select tool UI would not pick up on that and linger around which is odd as it seems that something somewhere is selected.
> bug(Select): Fix select tool UI sometimes lingering around

- client/src/game/Game.vue
- client/src/mods/index.ts
Mods were not properly cleaned up when leaving a campaign, making it possible to have duplicate entries when leaving and rejoining a session.
> bug(Mods): Ensure mods are removed when leaving a campaign

- CHANGELOG.md
- server/src/api/common/rooms/create.py
- server/src/api/http/auth.py
- server/src/api/socket/connection.py
- server/src/config/types.py
- server/src/db/all.py
- server/src/db/models/constants.py
- server/src/db/models/stats.py
- server/src/db/models/user.py
- server/src/planarserver.py
- server/src/save.py
- server/src/stats/__init__.py
- server/src/stats/anonymize.py
- server/src/stats/data.py
- server/src/stats/events.py
A question I often receive is how many users PA actually has and I can never actually answer this or even estimate this.
There is no official PA server that I can base myself on for some estimates, I only have some vague numbers like github stars or discord users, but those don't really say anything about actual users and if they're any indication at all they're more likely to represent server owners than players.
In order to get a feeling for what's actually going on out there I'm introducing a stats collection thingy on the server.
Although it would be nice to get some metrics into usage of various features of PA to see if things are actually used or not, this PR will focus on just 2 metrics. (And I don't expect other metrics being added anytime soon)
- Server total size: Get the total …
> feat(Stats): Add stats collection

- .github/workflows/pull_request.yaml
- server/pyproject.toml
- server/src/api/socket/location.py
- server/uv.lock
We're already using ruff for linting, no point really in sticking with black for formatting if ruff can do it as well but faster.
> chore(formatting): Drop black in favour of ruff

- CHANGELOG.md
- client/src/game/ui/initiative/Initiative.vue
This fixes #1619. The initiative effect input element lost focus after a single character press.
This must have broken due to the use of a newer Vue version as no actual change to the logic was made.
It's due to the name being used as part of the key, which is indeed wrong, but interestingly enough only posed a problem now. (It's been in the code for 3 years)
> bug(Initiative): Fix initiative effect renaming

- CHANGELOG.md
- client/src/game/tools/variants/select/index.ts
This fixes #1617. This is related to the selection bugfix changes in 2025.1
It was no longer possible to directly select a locked shape. You had to make a selection box around the shape as a workaround.
> bug(Select): Fix locked shapes not being selectable directly

- CHANGELOG.md
- client/src/game/systems/access/index.ts
- client/src/game/systems/access/state.ts
- client/test/game/systems/access/index.test.ts
The new access logic had a flaw causing DM only auras to no longer render unless they're set to public.
It is resolved by granting the access if there are no players associated at all with the shape.
This fixes #1616
> bug(Access): Fix DM only auras no longer rendering

- CHANGELOG.md
- server/src/stats/data.py
Limit amount of stat entries to 1000 per export to prevent stat server from rejecting the data.
> bug(Stats): Ensure stat export is chunked

- CHANGELOG.md
- server/src/db/models/stats.py
- server/src/save.py
- server/src/stats/data.py
- server/src/stats/events.py
If someone with an unstable connection connects to your server, the stats can be flooded with a lot of useless campaign_connected campaign_disconnected messages.
The server now checks if there is less than a minute between the connect and disconnect, in which case it will not track those stats.
> bug(Stats): Prevent stat flooding with unstable connections

- CHANGELOG.md
- client/src/game/layers/variants/grid.ts
Sometimes the last line on the X or Y axis would be skipped when rendering the grid.
This happens in specific cases where the pan value for that given axis is negative. In this case we were also drawing an extra line out of screen on the other side.
Image of the issue:
> bug(Grid): Fix square grid render sometimes skipping last line

- CHANGELOG.md
- client/src/game/input/mouse.ts
At low zoom levels (i.e. zoomed-in very far) using the mouse scroll can cause some drastic jumps in zoom level. This is not nice and although you can get more fine-grained zooming for those cases with the slider at the top right, this can be a bother if you're using an external monitor like a tv screen.
It should just work properly, so this PR adjusts the mouse zoom behaviour and smooths out the zooming at low levels.
> feat(Zoom) Smooth zoom behaviour when zoomed-in a lot

- CHANGELOG.md
- client/src/apiTypes.ts
- client/src/game/api/emits/initiative.ts
- client/src/game/api/events/initiative.ts
- client/src/game/models/initiative.ts
- client/src/game/ui/initiative/Initiative.vue
- client/src/game/ui/initiative/state.ts
- server/src/api/models/initiative/__init__.py
- server/src/api/socket/initiative/__init__.py
This PR fixes a number of smaller issues in the handling of turn changes and round changes. I'll address each individually:
When going to a previous turn in initiative, the effects attached to an entry would decrement as though you had gone to the next turn. I decided to add navigation direction to the calls to `setTurnCounter` in the client and `update_initiative_turn` in the server. It was otherwise impossible to tell which direction (forward or backward) the initiative was moving when only 2 entries were present. This information allows us to decrement the effect counters of an entry only when going forward.
I also thought that *incrementing* the effect counters when going in reverse seemed desirable. Imagine accidentally advancing and going back causing the effect timers to be …
> bug(Initiative): Fix issues related to round/turn handling

- .gitignore
I use an editor that places .swp files alongside the original while a file is open. These swp should never be included in the repository, but git happily adds them when I use `git add .` or similar. The client already has a dedicated gitignore which handles these temporary files. This PR simply makes `.sw?` files ignored throughout the whole repository rather than just in the client.
Checking with `find -iname '*.sw*'`, no files would be affected by this change.
> chore: Add *.sw? to .gitignore

- CHANGELOG.md
- client/src/assets/search.ts
There apparently was no debounce on the asset search, which is just inefficient.
> feat(Assets): Add debounce to asset search

- client/src/game/systems/customData/components/DiceFormat.vue
- client/src/game/systems/dice/dx.ts
- client/src/game/systems/dice/index.ts
- client/src/game/systems/dice/state.ts
- client/src/game/tools/variants/dice.ts
- client/src/game/ui/tools/dice/DiceCore.vue
This is a technical PR that re-organizes some logic regarding dice input handling.
There is both a string representation and an array parts presentation which are used for different aspects of the UI/logic, but kept each-other in sync.
This caused some annoyances with upcoming work and was also not well laid out from an architectural standpoint.
The string representation is now the main source of truth and also kept in the main dice state, allowing easier access to modify this by places outside of the dice tool.
The array logic is now contained with the dx helper file, which is were it always should have resided as its specialized logic that's not relevant for the main dice tool.
> chore(Dice): Re-organize dice tool input handling

- client/src/game/api/events.ts
Everything was there except the actual import.
As a result custom data sync events were being ignored, requiring a refresh for updates to be visible in other clients.
> bug(CustomData): Fix custom data events not being listened to
