Kruptein/PlanarAlly

PlanarAlly/templates/login.jinja2, PlanarAlly/templates/rooms.jinja2
Fixes #38 
Signed-off-by: Jakob Sinclair <sinclair.jakob@mailbox.org>
=> Remove jQuery CDN and use local files instead

CHANGELOG.md
Signed-off-by: Jakob Sinclair <sinclair.jakob@mailbox.org>
=> Fix spelling mistake and formatting

Dockerfile, Dockerfiles/server_config_docker.cfg
For some reason, I removed the dockerfiles in the old pr.
=> Add actual Dockerfiles

client/src/game/ui/dmsettings.vue, client/src/game/ui/menu/menu.vue, client/src/game/ui/note.vue, client/src/game/ui/selection/selection_info.vue
Fix $refs having wrong paths introduced in the eslint PR
=> Fix broken refs

client/src/game/ui/initiative/initiative.vue, client/src/game/ui/initiative/store.ts
Fix some issues with initiative since the recent split-off of the initiative store
=> Fix issues with initiative since store split-off

client/src/assetManager/manager.vue, client/src/assetManager/socket.ts, client/src/assetManager/store.ts, client/src/router.ts, server/api/socket/asset_manager.py, server/models/asset.py
Update the asset manager URLs while clicking around.
This allows you to access a certain folder immediately from your browser history or via a url share.
=> Update assetmanager URLs dynamically. Closes #198

README.md
Make sure to do your PR on the `dev` branch and NOT on the `master` branch.  This repo uses gitflow which only uses the master branch as a release branch.
Make sure to update the `CHANGELOG`.
=> Update readme slightly

CHANGELOG.md, client/src/auth/login.vue, client/src/core/store.ts, client/src/router.ts, server/api/http/__init__.py, server/api/http/auth.py, server/api/http/version.py, server/planarserver.py
For #216.
Just a simple API endpoint from the server. Currently pulling and displaying on the login prompt's legend. I figured there were other places better suited for this but wanted input before throwing them around.
Let me know what you think!
=> Display version on client

client/src/game/layers/utils.ts
This PR fixes issue #206.
The layer manager was not properly informed of floor removals.
=> Fix layermanager not being informed of floor removals

client/src/game/layers/utils.ts
Fix issue #231 by removing canvas elements on floor removal.
=> Remove canvas elements on floor removal

client/src/game/comm/types/shapes.ts, client/src/game/layers/layer.ts, client/src/game/shapes/asset.ts, client/src/game/shapes/circle.ts, client/src/game/shapes/circulartoken.ts, client/src/game/shapes/line.ts, client/src/game/shapes/polygon.ts, client/src/game/shapes/rect.ts, client/src/game/shapes/shape.ts, client/src/game/shapes/text.ts, client/src/game/shapes/utils.ts, client/src/game/ui/selection/edit_dialog.vue, server/api/socket/shape.py, server/models/shape.py, server/save.py
This PR starts work on issue #235 . It adds the notion of shape badges that show a token number with auto increment on copy paste.
=> Shape badges

CHANGELOG.md, client/src/game/layers/utils.ts, client/src/game/shapes/baserect.ts, client/src/game/shapes/circle.ts, client/src/game/shapes/line.ts, client/src/game/shapes/polygon.ts, client/src/game/shapes/shape.ts, client/src/game/shapes/text.ts, client/src/game/ui/tools/select.vue, client/src/game/visibility/te/draw.ts
For a longer time I suspected something to be wrong with the select drag operation. Definitely as dragging a group of multiple tokens often resulted in a jarring initial jump.
This is fixed in this PR
=> Select improvements

README.md
Just some small changes to the README, so the latest version and a donate button are more prominent.
=> Add more shields

CHANGELOG.md, client/src/game/game.vue, client/src/game/ui/floors.vue, client/src/game/ui/menu/asset_node.vue, client/src/game/ui/menu/menu.vue, client/src/game/ui/tools/tools.vue, client/src/game/ui/ui.vue
The css to position the UI is currently kinda all over the place and has some annoyances:
* the layer bar does not move when the menu opens
* the menu bar and the location bar overlap
This PR fixes this.
=> Reworking UI css

CHANGELOG.md, client/src/core/components/inputCopy.vue, client/src/game/shapes/polygon.ts, client/src/game/ui/dmsettings.vue, client/src/game/ui/dmsettings/permissions.vue, client/src/game/ui/floors.vue, client/src/game/ui/initiative/initiative.vue, client/src/game/ui/labels.vue, client/src/game/ui/menu/menu.vue, client/src/game/ui/note.vue, client/src/game/ui/selection/edit_dialog.vue, client/src/game/ui/selection/selection_info.vue, client/src/game/ui/tools/draw.vue, client/src/game/ui/ui.vue
This PR adds tooltip hovers to all icons in planarally.
=> feature(tooltips): Add tooltips to icons used throughout PA

server/app.py
This fixes a typo in section name. See diff
=> Fix cors_allowed_origins section

.github/workflows/pull_request.yaml, client/.eslintrc.js, client/package.json, client/src/game/comm/types/general.ts, client/src/game/ui/dmsettings/permissions.vue
In CI eslint should properly error and not autofix stuff as that does not actually accomplish anything
=> fix(eslint): Error in CI context

CHANGELOG.md, client/src/game/api/events.ts, client/src/game/events/keyboard.ts, client/src/game/geom.ts, client/src/game/store.ts, client/src/game/ui/selection/shapecontext.vue
By pressing spacebar you cycle between your owned tokens. (i.e. center the screen on the token)
=> feature(Token): Cycle owned tokens with spacebar

CHANGELOG.md, client/.eslintrc.js, client/src/game/ui/tools/draw.vue, client/src/game/ui/tools/filter.vue, client/src/game/ui/tools/map.vue, client/src/game/ui/tools/pan.ts, client/src/game/ui/tools/ping.ts, client/src/game/ui/tools/ruler.ts, client/src/game/ui/tools/select.vue, client/src/game/ui/tools/tool.vue, client/src/game/ui/tools/tools.vue, client/src/game/ui/tools/utils.ts, client/src/game/ui/tools/vision.vue
Redesigned the map tool UX.
*   Now gives a bit more information on how to use it
*   After making a selection you can adjust it to better fit your needs
*   Choose the X/Y numbers after selecting the shape
=> feature(MapTool): UX redesign

CHANGELOG.md, client/src/assetManager/contextMenu.vue, client/src/assetManager/manager.vue, client/src/assetManager/socket.ts, client/src/assetManager/store.ts
A progress bar is finally added to the asset manager!
Along with this addition are two bugfixes:
-   Asset manager not showing uploaded files until refreshed due to socket reconnect
-   Asset manager contextmenu not rendering correctly when scrolling down
=> feature(AssetManager): progress bar

CHANGELOG.md, server/api/socket/shape/__init__.py, server/models/shape/__init__.py
It was possible to create polygons that could brick a session.
=> bugfix(Polygon): Session breaking error due to polygon init

CHANGELOG.md, server/state/game.py
There was an error with cleanup of temporary shapes on disconnect which resulted in a lot of server spam
=> bug(Server): JSON decode error server spam

CHANGELOG.md, client/src/game/api/events.ts, client/src/game/api/events/access.ts, client/src/game/api/events/shape.ts, client/src/game/api/socket.ts, client/src/game/comm/types/shapes.ts, client/src/game/events/keyboard.ts, client/src/game/layers/layer.ts, client/src/game/manager.ts, client/src/game/shapes/owners.ts, client/src/game/shapes/shape.ts, client/src/game/ui/selection/edit_dialog/access.vue, client/src/game/ui/selection/selection_info.vue, client/src/game/ui/tools/createtoken_modal.vue, client/src/game/ui/tools/draw.vue, client/src/game/ui/tools/ping.ts, client/src/game/ui/tools/ruler.ts, client/src/game/ui/tools/select.vue, server/api/socket/shape/__init__.py, server/api/socket/shape/access.py, server/models/shape/__init__.py, server/save.py
This PR adds a specific access permission for movement to shapes. (closes #261)
Additionally this also fixes an issue with the access dialog not always rendering correctly in edge cases.
=> feat(Access): Movement access/permission

CHANGELOG.md, client/src/game/ui/initiative/initiative.vue, server/api/socket/initiative.py, server/models/shape/access.py
This PR fixes multiple issues with initiative synchronization
=> bug(Initiative): Multiple sync fixes

client/src/game/ui/ui.vue
add noopener and noreferrer to urls to prevent some possible vulnerabilities.
=> Prevent phising attacks on urls

client/src/assetManager/manager.vue, client/src/auth/login.vue, client/src/core/components/inputCopy.vue, client/src/core/components/modals/MarkdownModal.vue, client/src/core/components/modals/PanelModal.vue, client/src/dashboard/main.vue, client/src/game/ui/floors.vue, client/src/game/ui/initiative/initiative.vue, client/src/game/ui/labels.vue, client/src/game/ui/menu/locations.vue, client/src/game/ui/menu/menu.vue, client/src/game/ui/note.vue, client/src/game/ui/selection/edit_dialog/access.vue, client/src/game/ui/selection/edit_dialog/dialog.vue, client/src/game/ui/selection/selection_info.vue, client/src/game/ui/settings/GridSettings.vue, client/src/game/ui/settings/VisionSettings.vue, client/src/game/ui/tools/draw.vue, client/src/game/ui/ui.vue
This is a recommended practice.
=> bug(Aria): Add aria-hidden to all font awesome icons

client/src/core/components/modals/prompt.vue, client/src/game/ui/note.vue, client/src/game/ui/tools/createtoken_modal.vue
Fix some padding rules that get overwritten
=> bug(CSS): Fix unexpected shorthand padding

client/src/game/layers/utils.ts, client/src/game/shapes/aura.ts, client/src/game/shapes/text.ts, client/src/game/shapes/utils.ts, client/src/game/visibility/te/tds.ts, server/api/socket/shape/access.py, server/save.py, server/utils.py
Cleanup of varia bugs/smells reported by sonarcloud
=> fix(Varia): Sonarcloud cleanup

CONTRIBUTING.md
=> Adding translation guide to CONTRIBUTING.md

CHANGELOG.md, client/src/locales/zh.json
Continuous PR, merge without closing branch.
Ready to be merged for
- Chinese localization file and translations
- Update CHANGELOG for localization
=> feat(I18n): Continuous localization for Chinese

client/src/game/ui/menu/locations.vue
=> Fix location bar by using $t instead of v-t

CHANGELOG.md, client/src/locales/de.json
This entails German (DE-de, informal) translation for PlanarAlly. It's called "basic" and "prone to future changes in terminology" as some technical terms (e.g. "Asset" or "Tracker") are still english for (current) lack of appropriate translations. This should, however, blend in well with German-speaking users until appropriate German words are found.
=> I18n lang de

client/src/game/ui/settings/VisionSettings.vue
=> Fix vision mode setting

client/src/locales/de.json
=> (i18n) updated de.json

CHANGELOG.md, client/src/core/components/languageDropdown.vue, client/src/locales/de.json, client/src/locales/en.json, client/src/locales/ru.json, client/src/locales/zh.json
This adds russian translation of the client.
=> Add russian translation

CHANGELOG.md, client/src/core/components/languageDropdown.vue, client/src/locales/de.json, client/src/locales/dk.json, client/src/locales/en.json, client/src/locales/ru.json, client/src/locales/zh.json
Added a danish translation to the client
=> Add danish translation

CHANGELOG.md, client/src/core/components/languageDropdown.vue, client/src/locales/de.json, client/src/locales/dk.json, client/src/locales/en.json, client/src/locales/es.json, client/src/locales/ru.json, client/src/locales/zh.json
Added a spanish translation to the client.
Compiled and tested it for an hour or so, tried to clean up any tipos I found. 
If there's any issues or things I forgot I'm also on the discord as bigmen.
=> Add spanish localization

client/package-lock.json, client/package.json, client/public/index.html, client/src/App.vue, client/src/assetManager/manager.vue, client/src/auth/login.vue, client/src/core/components/inputCopy.vue, client/src/core/components/modals/MarkdownModal.vue, client/src/core/components/modals/PanelModal.vue, client/src/dashboard/main.vue, client/src/game/ui/floors.vue, client/src/game/ui/initiative/initiative.vue, client/src/game/ui/labels.vue, client/src/game/ui/menu/locations.vue, client/src/game/ui/menu/menu.vue, client/src/game/ui/note.vue, client/src/game/ui/selection/edit_dialog/access.vue, client/src/game/ui/selection/edit_dialog/dialog.vue, client/src/game/ui/selection/selection_info.vue, client/src/game/ui/settings/GridSettings.vue, client/src/game/ui/settings/VisionSettings.vue, client/src/game/ui/tools/draw.vue, client/src/game/ui/ui.vue, client/src/main.ts
Most icons in PA are font-awesome icons.  Up until now all icons were included by sideloading the fontawesome js and css code.
With this PR that is changed to vue specific components that are tree-shakeable.
=> feat(Icons): Change icon bundling method

client/src/game/ui/tools/select.vue
When snapping is enabled, the rotation tool will now snap to clean 45 degree angles on release.
This is prevented just like all other snap related actions by:
- using the alt modifier
- inverting snapping/alt behaviour in the user settings
=> feat(Rotation): Snap to 45 degree angles

client/src/locales/zh.json
=> Update Chinese translation for toggle_visibility

client/src/locales/de.json
updated german translation for floor user-visibilty toggle
=> Update German translation for (floor) toggle_visibility

client/src/locales/es.json
=> Added spanish translation for game.ui.floors.toggle_visibility

client/src/game/ui/tools/ping.ts, server/api/socket/shape/__init__.py, server/models/shape/access.py
This PR fixes a small issue where the server would throw errors while moving shapes.
=> bug(Movement): Fix some issues with temporary shape updates

client/src/game/ui/selection/selection_info.vue, client/src/locales/en.json
=> Add i18n for change value dialog

CHANGELOG.md, client/src/locales/zh.json
=> Update Chinese translation

client/src/game/comm/types/shapes.ts, client/src/game/shapes/polygon.ts, client/src/game/shapes/utils.ts, server/save.py
Recent optimization changes to shape movement did not properly account for some polygon aspects.  To accomodate this the polygon db representation has slightly changed.
=> bug(Polygon): Fix polygon position update

client/src/game/ui/tools/ruler.vue
I18n changes: use localized numbers.
Draft, while finding all the numbers need localization.
=> Use localized numbers

CHANGELOG.md, client/src/game/api/events/floor.ts, client/src/game/layers/store.ts, client/src/game/ui/floors.vue, client/src/locales/en.json, server/api/socket/floor.py
This PR closes #462 and adds the ability to rename existing floors.
=> feat(Floor): Add rename floor functionality

client/src/locales/de.json
include rename floor UI translation
=> update German translation

client/src/game/input/keyboard.ts, client/src/game/layers/layer.ts, client/src/game/shapes/utils.ts, client/src/game/ui/selection/selection_info.vue, client/src/game/ui/tools/map.vue, client/src/game/ui/tools/select.vue
In some cases the rotation/selection UI would stick around, this is now resolved.  This closes #489
=> bug(UI): Fix lingering rotation ui

CHANGELOG.md, client/src/game/visibility/te/cdt.ts, client/src/game/visibility/te/tds.ts, client/src/game/visibility/te/triag.ts
This PR implements a missing case that is rarely hit during vision calculation.
It also cleans up some terrible error messages
=> feat(Vision): Implement convex hull insertion for 1D case

client/src/core/components/modals/SelectionBox.vue
This PR adds the ability to choose which spawn location a shape should be sent to when a location contains more than one spawn location.
=> feat(SpawnLocation): Allow multiple spawn locations

CHANGELOG.md, Dockerfile
This PR changes the running user of the docker container from root to uid 9000. This is a preventive security measure as suggested by @donicrosby. This closes #499.
=> bug(Docker): Make sure docker container is run as non-root

client/src/locales/de.json
=> update german language file

CHANGELOG.md, client/src/core/components/languageDropdown.vue, client/src/locales/de.json, client/src/locales/dk.json, client/src/locales/en.json, client/src/locales/es.json, client/src/locales/ru.json, client/src/locales/tw.json, client/src/locales/zh-tw.json, client/src/locales/zh.json
Make sure to do your PR on the `dev` branch and NOT on the `master` branch.  This repo uses gitflow which only uses the master branch as a release branch.
Make sure to update the `CHANGELOG`.
=> locales: zh-tw

CHANGELOG.md, client/public/index.html, client/src/App.vue, client/src/assetManager/socket.ts, client/src/core/utils.ts, client/src/dashboard/main.vue, client/src/game/api/events/client.ts, client/src/game/api/socket.ts, client/src/router.ts, client/vue.config.js, server/planarserver.py
This PR adds support for hosting PA on a subpath (not to be confused with a subdomain).
This closes #70
=> feat(Server): Base subpath support

CHANGELOG.md, client/src/core/components/languageDropdown.vue, client/src/locales/de.json, client/src/locales/dk.json, client/src/locales/en.json, client/src/locales/es.json, client/src/locales/it.json, client/src/locales/ru.json, client/src/locales/tw.json, client/src/locales/zh.json
Added the italian language to the project, I've forked from dev and I've updated the changelog.
=> Add italian locale

client/src/assetManager/manager.vue, client/src/assetManager/socket.ts, client/src/auth/login.vue, client/src/game/layers/utils.ts, client/src/game/shapes/utils.ts, client/src/game/ui/menu/asset_node.vue, client/src/game/ui/menu/menu.vue, client/src/game/ui/tools/defaultcontext.vue, client/src/game/ui/ui.vue
This fixes some untouched urls that were not yet subpath aware.
=> bug(Tech): Fix a bunch of missed cases for subpath urls

client/src/game/ui/tools/map.vue
The recent change to map input validation, broke some valid input cases.
=> bug(Map): Fix input validation bug

CHANGELOG.md, client/src/auth/login.vue, client/src/core/utils.ts, client/src/dashboard/main.vue, client/src/settings/account.vue
Addresses https://github.com/Kruptein/PlanarAlly/issues/247.
I was able to validate the login, and registration error messages, but I'm not sure how to trigger an error on either of the other two that I changed. If you've got any guidance on that, I'd be happy to do some more testing on this.
=> Read Error messages from response body

CHANGELOG.md, client/src/game/ui/selection/edit_dialog/PropertySettings.vue, server/api/socket/shape/options.py, server/models/shape/__init__.py
=> bug(Shape): Fix private shape names showing up as ? for users with access

CHANGELOG.md, client/src/game/ui/tools/tools.vue
=> bug(Annotations): Fix annotations from other floors being shown

CHANGELOG.md, Dockerfile, client/package-lock.json, client/package.json, client/public/index.html, client/src/App.vue, client/src/assetManager/socket.ts, client/src/core/utils.ts, client/src/game/api/socket.ts, client/src/router.ts, client/src/utils.ts, server/VERSION, server/app.py, server/planarserver.py, server/routes.py
This hotfix addresses some issues with the relative path logic.
=> hotfix(0.23.1)

CHANGELOG.md, client/src/game/api/events/location.ts, client/src/game/comm/types/settings.ts, client/src/game/layers/grid.ts, client/src/game/settings.ts, client/src/game/ui/settings/GridSettings.vue, client/src/locales/en.json, server/api/socket/location.py, server/models/campaign.py, server/save.py
This PR introduces both hexagon variants (flat and pointy top) as a grid type that can be selected in the DM grid settings or location settings.
This closes #136
=> feat(Grid): Support hexagons

CHANGELOG.md, client/src/game/ui/initiative/initiative.vue, server/api/socket/initiative.py, server/models/initiative.py, server/save.py
When non-numeric input is encountered it is no longer attempted to decrement its value.
This closes #389
=> bug(UI): Initiative effects becoming NaN for non-numeric inputs

CHANGELOG.md, server/api/socket/initiative.py, server/api/socket/shape/__init__.py, server/models/shape/access.py
=> bug(Movement): Fix default movement access not working

CHANGELOG.md, client/src/game/layers/layer.ts, client/src/game/ui/initiative/initiative.vue, server/api/socket/shape/access.py
=> bug(Initiative): Fix various bugs with initiative permission updates

CHANGELOG.md, client/src/game/shapes/aura.ts
=> Set a minimum of 0 when drawing Auras

CHANGELOG.md, client/src/game/ui/tools/createtoken_modal.vue
This PR autofocuses the input field of the create token modal and now also allows you to press enter to submit while the input field is focussed.
=> feat(CreateToken): UX improvements

client/src/game/api/events.ts
A change from sync to async code with the group update yesterday, caused floor loading to sometimes throw errors.
This has been fixed
=> bug(Floors): Fix maps with floors potentially not loading

client/package-lock.json, client/package.json, client/src/assetManager/manager.vue, client/src/auth/login.vue, client/src/core/components/contextmenu.vue, client/src/core/components/languageDropdown.vue, client/src/core/components/modals/PanelModal.vue, client/src/core/components/modals/SelectionBox.vue, client/src/dashboard/main.vue, client/src/game/ui/floors.vue, client/src/game/ui/initiative/initiative.vue, client/src/game/ui/labels.vue, client/src/game/ui/menu/asset_node.vue, client/src/game/ui/menu/locations.vue, client/src/game/ui/menu/menu.vue, client/src/game/ui/note.vue, client/src/game/ui/selection/edit_dialog/ExtraSettings.vue, client/src/game/ui/selection/edit_dialog/GroupSettings.vue, client/src/game/ui/selection/selection_info.vue, client/src/game/ui/selection/shapecontext.vue, client/src/game/ui/tools/defaultcontext.vue, client/src/game/ui/tools/draw.vue, client/src/game/ui/tools/map.vue, client/src/game/ui/tools/ruler.vue, client/src/game/ui/tools/tool.vue, client/src/game/ui/tools/tools.vue, client/src/game/ui/tools/vision.vue, client/src/game/ui/ui.vue, client/src/settings/account.vue, client/src/settings/settings.vue
This PR changes some of the css code to make use of scss
=> feat(Styling): Use Scss

CHANGELOG.md, client/src/game/Game.vue, client/src/game/api/emits/shape/core.ts, client/src/game/api/events/shape/core.ts, client/src/game/layers/layer.ts, client/src/game/ui/selection/shapecontext.vue, client/src/game/ui/tools/draw.vue, client/src/game/ui/tools/ruler.vue, client/src/game/ui/tools/select.vue, client/src/game/ui/tools/tool.vue, client/src/game/ui/tools/tools.vue, server/api/socket/shape/__init__.py, server/api/socket/shape/data_models.py
When using the ruler you can now press 'space' to start a new ruler from your mousepoint.
The ruler length will move with you to the new ruler and display the total length of all rulers currently shown
=> feat(Ruler): MultiRuler

CHANGELOG.md, client/src/game/api/emits/shape/options.ts, client/src/game/comm/types/shapes.ts, client/src/game/shapes/shape.ts, client/src/game/ui/ActiveShapeStore.ts, client/src/game/ui/selection/edit_dialog/ExtraSettings.vue, client/src/locales/en.json, server/api/socket/shape/options.py, server/models/shape/__init__.py, server/save.py
This closes #635 and adds a toggle to the annotation settings to make annotations publicly visible.
=> feat(UI): Add show annotation toggle

CHANGELOG.md, client/src/core/components/RotationSlider.vue, client/src/core/components/modals/PanelModal.vue, client/src/game/comm/conversion/aura.ts, client/src/game/comm/types/shapes.ts, client/src/game/layers/fowlighting.ts, client/src/game/shapes/interfaces.ts, client/src/game/shapes/shape.ts, client/src/game/shapes/trackers/draw.ts, client/src/game/shapes/trackers/empty.ts, client/src/game/shapes/variants/togglecomposite.ts, client/src/game/ui/ActiveShapeStore.ts, client/src/game/ui/selection/edit_dialog/TrackerSettings.vue, client/src/game/ui/tools/tools.vue, client/src/game/ui/ui.vue, client/src/game/units.ts, client/src/game/visibility/te/triag.ts, server/models/shape/__init__.py, server/save.py
This PR does a dramatic overhaul of the aura UI and additionally adds some new goodies!
new features include:
- enable/disable toggle for individual auras
- specify border colours
- restrict the aura to a smaller cone instead of a full circle
=> feat(Aura): Overhaul aura UI + new features

CHANGELOG.md, client/src/core/components/modals/SelectionBox.vue, client/src/game/api/emits/location.ts, client/src/game/api/events.ts, client/src/game/api/events/location.ts, client/src/game/comm/types/settings.ts, client/src/game/store.ts, client/src/game/ui/menu/locations.vue, client/src/game/ui/selection/shapecontext.vue, client/src/game/ui/settings/location/LocationAdminSettings.vue, client/src/game/ui/settings/location/LocationSettings.vue, client/src/locales/en.json, client/src/main.ts, server/api/socket/location.py, server/models/campaign.py, server/save.py
This PR adds archiving and unarchiving functionality to the location bar.
You can archive a location from its settings if no players are in that location.
A new button has been added below the add location button to restore any archived locations.
=> feat(Location): Archive locations

CHANGELOG.md, client/src/core/components/colorpicker.vue, client/src/game/comm/types/shapes.ts, client/src/game/shapes/variants/circle.ts, client/src/game/shapes/variants/circulartoken.ts, client/src/game/ui/tools/Spell.vue, client/src/game/ui/tools/tools.vue, client/src/game/ui/tools/utils.ts, client/src/locales/en.json, server/models/shape/__init__.py, server/save.py
This PR adds a spell measuring/previewing tool.
This closes #195
=> feat(Tool): Add spell tool

client/src/assetManager/manager.vue, client/src/locales/en.json
=> bug(Lang): Fix hover tooltip on download assets button

CHANGELOG.md, client/src/game/Game.vue, client/src/game/api/events.ts, client/src/game/store.ts, client/src/game/ui/floors.vue, client/src/game/ui/selection/shapecontext.vue, client/src/game/ui/tools/defaultcontext.vue
The websocket connection sometimes loses connection and from time to time does not properly reconnect.  This can be very annoying if you're not aware and continue to do some changes.
This PR adds a big red border to the side of the screen when disconnected.
=> feat(UI): Show a big red border on disconnect

CHANGELOG.md, client/src/game/ui/tools/Spell.vue, client/src/locales/en.json, server/static/img/cone.svg
The cone icon has been updated with a custom svg created by a friend of me, and is now a properly filled version.
=> feat(UI): Update spell cone icon

CHANGELOG.md, client/.eslintignore, client/.eslintrc.js, client/src/assetManager/manager.vue, client/src/game/input/keyboard.ts, client/src/game/operations/undo.ts, client/src/game/ui/tools/draw.vue, client/src/game/ui/tools/select.vue
This PR changes all ctrl key based keybindings on mac to use cmd instead.
This closes #678
=> feat(keybindings): Use cmd on mac

CHANGELOG.md, client/src/game/ui/selection/shapecontext.vue, client/src/game/ui/tools/defaultcontext.vue
=> bug(UI): Fix context menu going off screen

CHANGELOG.md, client/src/game/api/emits/shape/core.ts, client/src/game/models/shapes.ts, client/src/game/shapes/utils.ts, client/src/game/shapes/variants/text.ts, client/src/game/ui/tools/Spell.vue, client/src/game/ui/tools/draw.vue, client/src/game/ui/tools/map.vue, client/src/game/ui/tools/pan.vue, client/src/game/ui/tools/ping.vue, client/src/game/ui/tools/ruler.vue, client/src/game/ui/tools/select.vue, client/src/game/ui/tools/tool.vue, client/src/locales/en.json, server/api/socket/shape/__init__.py, server/api/socket/shape/data_models.py, server/models/shape/__init__.py, server/save.py
The draw tool now has a text shape :tada:
Click wherever you want and a modal will appear to ask for the text.
=> feat(Draw): Add text shape

CHANGELOG.md, client/src/router.ts
This fixes the back button in browser/mouse not working
=> bug(Navigation): Fix back navigating

client/src/game/shapes/shape.ts, client/src/game/ui/selection/edit_dialog/TrackerSettings.vue, server/save.py
This fixes the positioning to be consistent with zoom and also places it a bit higher so that it looks more natural for non circular shapes.
This also fixes the auto-creation of new trackers when clicking on the latest tracker but not changing anything.
Lastly this fixes a bug with the save format.
=> bug(Tracker): Small fixes to tracker bars

CHANGELOG.md, client/package-lock.json, client/package.json, client/src/game/ui/selection/ShapeContext.vue, server/VERSION, server/models/campaign.py, server/save.py
This hotfix addresses two issues:
- fresh installs having NOT NULL constraints on some new fields that were meant to be nullable
- markers context menu not working correctly on marker changes
=> hotfix(0.26.1)

client/src/locales/en.json
… 'cause I think there was one missing. :)
=> insert an 'of'

CHANGELOG.md, server/planarserver.py, server/server_config.cfg
=> feat(API): Make API server optional and disabled by default

CHANGELOG.md, server/api/socket/initiative.py
=> bug(Initiative): Fix Co-DM not seeing private initiatives

CHANGELOG.md, client/src/game/api/emits/location.ts, client/src/game/store.ts, client/src/game/ui/settings/location/LocationAdminSettings.vue, client/src/locales/en.json, server/api/socket/location.py, server/models/groups.py, server/models/label.py, server/models/shape/__init__.py
Intended to address #697 
Still have to make sure it copies over Aura's, trackers, labels, and groups. But wanted to send this out a little early to see if I could get any feedback. I feel like there should be a better way to do the make_copy methods, but I'm not super familiar with peewee, and I couldn't find anything in the documentation that would seem to help.
=> Copy location

client/src/game/ui/tokendialog/CreateTokenDialog.vue
This PR fixes a problem where the colour picker would always disappear when creating a token.
=> bug(CreateToken): Fix not being able to properly pick a colour for a token

client/src/game/assets/utils.ts
Some search filters would give false empty results
=> bug(AssetBar): Fix search filter not taking certain edge cases into account

client/src/game/ui/contextmenu/ShapeContext.vue
This was broken since the vue3 change
=> bug(ShapeContext): Fix move layer no longer working

CHANGELOG.md, client/src/game/input/keyboard.ts
=> bug(Redo): Fix redo on mac not working

client/src/game/ui/initiative/state.ts
This PR fixes the new initiative messing with the active tokens in a way that it's not supposed to do :v
=> bug(Vision): Fix initiative messing up active tokens

client/src/game/ui/contextmenu/ShapeContext.vue, client/src/game/ui/menu/LocationBar.vue, client/src/store/location.ts
This PR fixes the active location not being visible
=> bug(Locations): Fix active location not showing

client/src/game/ui/tools/DrawTool.vue
This PR fixes an issue with the draw tool's text feature not prompting for text
=> bug(DrawTool): Fix draw text not working

client/src/game/ui/settings/shape/GroupSettings.vue, server/models/shape/__init__.py
Since the big client rework, a bug prevented the paste functionality from working properly.
This also fixes a bug with the group settings panel not properly updating
=> bug(CopyPaste): Fix copy-paste not working

client/src/game/ui/settings/shape/AccessSettings.vue, client/src/game/ui/settings/shape/ExtraSettings.vue, client/src/game/ui/settings/shape/GroupSettings.vue, client/src/game/ui/settings/shape/PropertySettings.vue, client/src/game/ui/settings/shape/TrackerSettings.vue
This PR fixes an issue where a certain check in the UI was not properly updating and could show certain fields as inaccessible when you should have access or viceversa.
At no point did this actually pass the server sync
=> bug(Access): Fix some access permission errors

client/src/game/Game.vue, client/src/game/temp.ts
This PR fixes a problem that caused the template choice popup to not appear
=> bug(Templates): Fix template drop not prompting for choice

client/src/game/shapes/utils.ts
This PR fixes shape ownership not being copied when copy paste-ing
=> bug(CopyPaste): Fix access not carrying over

CHANGELOG.md, client/src/game/tools/variants/select.ts
This PR adds a small QoL that is often there in other programs, where if you ctrl click an already selected item it will deselect instead.
=> feat(Select): Ctrl clicking a selected shape will deselect

CHANGELOG.md, client/src/game/shapes/shape.ts
This PR fixes negative tracker bars with a display rendering a bar to the left.
=> bug(Trackers): Fix negative tracker bars

client/src/game/ui/menu/LocationBar.vue
This PR fixes an issue where opening the sidebar could cause a permanent scrollbar to be visible in firefox
=> bug(UI): Fix issue where scrollbar would appear on firefox

client/src/invitation.ts, client/src/router.ts
This PR fixes invitation urls no longer working since the client rework
=> bug(Invitation): Re-add invitation

README.md
Make sure to do your PR on the `dev` branch and NOT on the `master` branch.  This repo uses gitflow which only uses the master branch as a release branch.
Make sure to update the `CHANGELOG`.
=> grammar improvements

client/src/game/tools/variants/spell.ts
This fixes an error with reactive internals.
=> bug(Spell): Fix recursive effect error

CHANGELOG.md, client/package-lock.json, client/src/game/ui/Annotation.vue
This PR fixes HTML tags no longer working in annotations
=> bug(Annotations): Allow HTML again

CHANGELOG.md, client/src/core/components/ColourPicker.vue
-   Keep focus on saturation while mouse down
-   Increase height sliders
-   Fix hue slider click initially not moving
-   Add back checkboard background
-   Show cursor:pointer on slider hover
=> bug(ColourPicker): Multiple improvements/fixes

client/index.html
This is a remnant of the migration to Vite.js from Webpack.
=> Fix HTML template title property

client/package-lock.json, client/package.json, client/src/core/utils.ts, client/src/game/dice/environment.ts, client/src/game/dice/state.ts, client/src/game/tools/variants/dice.ts, client/src/game/ui/tools/DiceTool.vue
- Reduces the timer to automatically roll from 4 seconds to 1 second.
- Increases speed with which dice are thrown
- Randomize position and direction from where the dice are thrown
- The dice will always be thrown from one of the sides vaguely towards the center
- Use the player's ruler colour as the colour for the dice
- One small issue right now is that the font colour of the number is always black
- Increase wall height of dice box to prevent dice leaving the area
- Dice are cleared from the board when results are closed
- Limit height of history element with scroll behaviour
- Dice should stop rolling faster
- Add shadow to dice
- Add roof to make sure any funky dice throw stays within the box
=> feat(Dice): Further tweaks

CHANGELOG.md, client/src/game/temp.ts, client/src/game/ui/contextmenu/ShapeContext.vue
This fixes #799 as well as fixing locked shapes from being able to change floors
=> bug(LockedShapes): Prevent movement to other floors/locations

client/package-lock.json, client/package.json, client/src/game/dice/environment.ts
This PR fixes the strange halo appearing when selecting the dice tool
=> bug(Dice): Remove dice-halo

CHANGELOG.md, client/src/core/components/RotationSlider.vue, client/src/game/ui/settings/shape/TrackerSettings.vue
=> feat(Aura): Add number input to aura angle direction UI

.github/workflows/docker.yml
With the dockerhub changes to autobuild, the PA images haven't been build properly in recent times.
This PR adds build checks on PRs to master & dev and pushes tagged commits
=> chore(Docker): Fix build & push

.github/workflows/docker.yml
Also push docker images for dev branch changes
=> chore(docker): push on dev pushes

client/package-lock.json, client/package.json, client/src/auth/Login.vue
Something recently broke the login feature carousel from working
=> bug(Login): Fix carousel

CHANGELOG.md, client/src/game/ui/settings/shape/TrackerSettings.vue, client/src/store/activeShape.ts
The "Shared for all variants" toggle in trackers/auras for composite/variant shapes was not properly working
=> bug(Composite): Fix "share" tracker/aura toggle

Dockerfile
This PR upgrades the dockerfile to use node 16 instead of node 12.
=> feat(Docker): Upgrade node to 16 in Dockerfile

client/src/game/input/keyboard.ts, client/src/game/models/tools.ts, client/src/game/operations/movement.ts, client/src/game/tools/events.ts, client/src/game/tools/tool.ts, client/src/game/tools/variants/draw.ts, client/src/game/tools/variants/map.ts, client/src/game/tools/variants/pan.ts, client/src/game/tools/variants/ping.ts, client/src/game/tools/variants/ruler.ts, client/src/game/tools/variants/select.ts, client/src/game/tools/variants/spell.ts, client/src/store/logic.ts
- keyboard movement now also triggers a tp zone
- player cam is moved along with tp if move player on token change setting is enabled (this is the default)
=> feat(logic): Various QoL updates

client/src/game/systems/access/index.ts, client/src/game/systems/auras/index.ts, client/src/game/systems/index.ts, client/src/game/systems/logic/door/index.ts, client/src/game/systems/logic/tp/index.ts, client/src/game/systems/trackers/index.ts
A small thing I overlooked with my access systems change.
=> bug(Initiative): Fix access changes not updating initiative

.github/workflows/docker.yml, CHANGELOG.md
=> ci: :construction_worker: build for amd64 and arm64

client/src/assetManager/AssetManager.vue, client/src/assetManager/state.ts, client/src/game/layers/variants/layer.ts, client/src/game/svg.ts, client/src/game/tools/variants/draw.ts, client/src/game/tools/variants/ruler.ts, client/src/game/tools/variants/select.ts, client/src/game/vision/iterative.ts, client/src/game/vision/tds.ts
With ts 4.6 there is finally a more sane way to do relative indexing. This PR simply adjusts places where this improves code readability
=> chore(Refactor): Use Array.prototype.at()

client/src/game/tools/variants/draw.ts, client/src/game/tools/variants/ping.ts, client/src/game/tools/variants/ruler.ts, client/src/game/tools/variants/select.ts, client/src/game/tools/variants/spell.ts, client/src/game/ui/settings/shape/ExtraSettings.vue, client/src/game/ui/tokendialog/CreateTokenDialog.vue
Only the `edit` access right was being given to newly created shapes
=> bug(Access): Fix not all access rights given to new shapes

CHANGELOG.md, server/api/socket/asset_manager/__init__.py, server/models/campaign.py, server/save.py
A rather bad bug was triggering a SQL cascade delete where it should not have, causing a campaign to be removed entirely if the campaign logo was removed.
=> bug(Asset): Fix logo removal triggering campaign removal

client/src/game/systems/logic/common.ts, client/src/game/systems/logic/door/index.ts, client/src/game/systems/logic/models.ts, client/src/game/systems/logic/tp/index.ts, client/src/game/tools/variants/draw.ts, client/src/game/ui/settings/shape/LogicSettings.vue, server/api/socket/shape/options.py
There were some mistakes in how the server side saved tp-zone settings causing them to no longer function as expected upon reload of the page.
=> bug(TpZone): Fix various tpzone related issues with server syncing

server/export/campaign.py
Last PR happened to only fix the LUO for the campaign creator, this also fixes it for players.
=> bug(Export): Fix LUO not exporting for players too

CHANGELOG.md, client/src/game/api/events.ts, client/src/game/api/events/location.ts, client/src/game/id.ts, client/src/game/shapes/utils.ts, server/api/socket/location.py
The loading of spawn locations at location load was going wrong since the local/global id refactor.
=> bug(Spawn): Fix spawn location loading

CHANGELOG.md, admin-client/src/components/TokenLogin.vue, client/src/auth/Login.vue, client/src/dashboard/CreateCampaign.vue, client/src/game/api/events.ts, client/src/game/ui/settings/dm/AdminSettings.vue, client/src/router.ts
Not all `router.push` calls were being awaited.
=> bug(Tech:Router): Ensure router push calls are always awaited

CHANGELOG.md, client/src/game/client.ts, client/src/game/layers/variants/fowLighting.ts, client/src/game/layers/variants/layer.ts, client/src/game/shapes/interfaces.ts, client/src/game/shapes/shape.ts, client/src/game/shapes/variants/asset.ts, client/src/game/shapes/variants/baseRect.ts, client/src/game/shapes/variants/circle.ts, client/src/game/shapes/variants/line.ts, client/src/game/shapes/variants/polygon.ts, client/src/game/shapes/variants/rect.ts, client/src/game/shapes/variants/text.ts, client/src/game/tools/variants/draw.ts, client/src/game/tools/variants/map.ts, client/src/game/tools/variants/ping.ts, client/src/game/tools/variants/ruler.ts, client/src/game/tools/variants/select.ts, client/src/game/tools/variants/spell.ts, client/src/game/ui/contextmenu/DefaultContext.vue
There was some unnecessary overhead on updating which points can be snapped to in the case of some shapes that should never be snappable.
=> feat(Tech:SnapPoints): Check snappable points less often

CHANGELOG.md, client/src/dashboard/Dashboard.vue, client/src/dashboard/ImportGame.vue, client/src/dashboard/SessionList.vue, client/src/dashboard/socket.ts, client/src/dashboard/types.ts, client/test/setup.ts, server/server_config.cfg, server/src/api/http/rooms.py, server/src/api/http/server.py, server/src/api/socket/__init__.py, server/src/api/socket/constants.py, server/src/api/socket/dashboard/__init__.py, server/src/api/socket/dashboard/campaign.py, server/src/app.py, server/src/auth.py, server/src/export/campaign.py, server/src/planarserver.py, server/src/routes.py, server/src/save.py, server/src/state/dashboard.py, server/src/typed.py
Exporting campaigns is already possible if you know the correct API paths.
Before adding UI options to export campaigns, there has to be a use for them,
which brings us to this PR which is adding import functionality.
Importing campaigns is currently done from a new dedicated navigation entry.
The UI is just an ugly simple button to upload a .pac file (obtained after exporting).
There is no indication of progress at this moment. Once done it will be available in your rooms.
Some things to take into account:
- There is little feedback on the import/export process at this moment, so it's sometimes difficult to tell whether it's just still busy or actually failed.
- You cannot have two campaigns with the same name associated with your account, there is no way to specify the name of a …
=> feat(Import): Import campaigns

CHANGELOG.md, client/src/game/ui/SelectionInfo.vue
=> bug(Trackers): Fix shared trackers not appearing in selection info

client/src/game/layers/variants/layer.ts
Some filters in the layer draw loop could be done slightly earlier.
=> feat(Perf): Small layer draw perf tweaks

CHANGELOG.md, client/src/game/api/events/shape/options.ts, client/src/game/interfaces/shape.ts, client/src/game/layers/variants/layer.ts, client/src/game/shapes/shape.ts, client/src/game/systems/access/index.ts, client/src/game/systems/annotations/index.ts, client/src/game/systems/annotations/state.ts, client/src/game/tools/events.ts, client/src/game/ui/settings/shape/ExtraSettings.vue, client/src/store/_game.ts, client/src/store/activeShape.ts, client/src/store/game.ts
This PR moves the annotations to a 'system'. Following other migrations in the last months.
While migrating, I also found 2 bugs related to syncing updates to other clients.
=> feat(Systems): Migrate annotations to system

CHANGELOG.md, client/src/core/components/ContextMenu.vue, client/src/game/Game.vue, client/src/game/tools/events.ts, client/src/store/ui.ts
This is an alternative pan option for when you don't have a middle-mouse button to pan. (e.g. a laptop touchpad)
=> feat(Pan): Add pan with right-click drag

client/src/game/api/events/client.ts, client/src/game/input/keyboard/up.ts, client/src/game/rendering/basic.ts, client/src/game/systems/client/index.ts, client/src/game/systems/players/index.ts, client/src/game/systems/position/index.ts, client/src/game/systems/settings/players/state.ts, client/src/game/systems/state.ts, client/src/game/tools/variants/select/index.ts, client/src/game/ui/Floors.vue, client/src/game/ui/contextmenu/ShapeContext.vue, client/src/game/ui/initiative/state.ts, client/src/game/ui/menu/LocationBar.vue, client/src/game/ui/settings/client/AppearanceSettings.vue, client/src/game/ui/settings/shape/AccessSettings.vue, client/src/game/ui/settings/shape/LogicPermissions.vue, client/src/game/ui/settings/shape/LogicSettings.vue, client/src/game/ui/settings/shape/PropertySettings.vue, client/src/game/ui/tools/Tools.vue, client/src/game/vision/iterative.ts, client/test/game/systems/access/index.test.ts, server/src/api/socket/asset_manager/common.py, server/src/export/campaign.py
This is a collection of minor changes that are rectified between the gameboard codebase and this repository.
=> chore: Some small changes to sync with gameboard codebase

client/src/assetManager/state.ts, client/src/core/components/LanguageDropdown.vue, client/src/core/components/modals/ConfirmDialog.vue, client/src/game/Game.vue, client/src/game/api/socket.ts, client/src/game/layers/variants/fow.ts, client/src/game/systems/position/index.ts, client/src/game/systems/settings/players/state.ts, client/src/game/ui/DebugInfo.vue, client/src/game/ui/debug.ts
This is another PR to sync with changes made in the gameboard repo.
They are small in nature and should have no impact on the player experience.
=> chore: Variety of small changes

client/src/game/layers/variants/fowLighting.ts, client/src/game/systems/floors/index.ts, client/src/game/ui/tools/Tools.vue
These couple of lines were supposed to go in the previously merged performance prs
=> bug(Performance): Add missing improvements

CHANGELOG.md, client/src/game/api/events/shape/core.ts, client/src/game/layers/variants/layer.ts, server/src/api/socket/initiative.py, server/src/api/socket/shape/__init__.py, server/src/models/groups.py
Removing shapes was not properly removing entries in the initiative list.
Another bug was fixed regarding the initiative not appearing for shapes that were moved from the DM layer to a player-visible layer
=> bug(Initiative): Fix some initiative interactions with shape removal and layer changing

client/src/game/api/events/location.ts
Setting location settings would overwrite all other settings to undefined. This has been fixed
=> bug(Location): Fix location settings overwrite mode

client/src/game/ui/tools/SelectTool.vue
Somewhere in the current dev run I made a mistake causing the polygon edit UI to no longer be visible. This is fixed.
=> bug(Select): Fix polygon edit UI missing

client/src/dashboard/Dashboard.vue, client/src/dashboard/Settings.vue, client/src/router/bootstrap.ts
As with the previous PR, the account settings were missing from the dashboard rework.
This has been rectified in this PR.
=> bug(UI: Dashboard): Restore dashboard account settings UI

client/src/game/ui/initiative/Initiative.vue, client/src/game/ui/initiative/state.ts
I recently made a big logic fix to initiative and hoped that would fix all things initiative.
But one of the dependencies I use apparently didn't have proper typing, causing a couple of type changes to go haywire because the IDE couldn't report the mismatch.
Anyway, that should be resolved now.
=> bug(Initiative): Fix UI

client/src/apiTypes.ts, client/src/game/api/events/player/options.ts, server/src/api/models/helpers.py, server/src/api/models/players/options.py, server/src/api/socket/location.py
Bug caused by the api types rework.
=> bug(PlayerOptions): Fix player options not loading properly

server/src/api/socket/shape/options.py
Tracker and Aura visibility was not sending a proper Remove event to clients.
=> bug(Tracker/Aura): Fix visibility change not properly syncing to clients

client/src/apiTypes.ts, client/src/game/systems/access/emits.ts, server/src/api/models/shape/owner.py, server/src/api/socket/shape/access.py
Removing access from a shape was failing on a server validation check.
=> bug(Access): Fix access removal not longer working

server/src/api/common/shapes/__init__.py, server/src/api/socket/shape/__init__.py
A bug in the recent API type rework, caused shape creation and removal to no longer work.
Fixes #1200
=> bug(Shape): Fix shape creation and removal no longer working [dev]

server/src/api/socket/floor.py, server/src/api/socket/location.py, server/src/api/socket/shape/__init__.py, server/src/api/socket/shape/access.py, server/src/models/access.py, server/src/transform/floor.py, server/src/transform/layer.py, server/src/transform/shape.py
A recent change to access made it so that without default edit access, the DM would not be able to edit a shape. This is obviously not intended.
Fixes #1199
=> bug(Access): Fix DM not seeing anything if default access is turned off [dev]

server/src/api/socket/shape/options.py
Subtle bug introduced with the API change.
=> bug(Shape): Fix some shape options not saving properly

server/src/api/socket/initiative/__init__.py, server/src/api/socket/initiative/effect.py
The recent API change was causing some json serialization errors.
=> bug(Initiative): Fix initiative json errors [dev]

server/src/api/socket/location.py
=> bug(Locations): Fix location settings save [dev]

server/src/api/socket/groups.py, server/src/api/socket/location.py, server/src/api/socket/shape/options.py, server/src/db/typed.py, server/src/db/utils.py
Another casualty from the API changes.
This one fixes 2 method calls that were untyped causing this and a couple of earlier bugs to have slipped through the maze.
=> bug(Aura): Fix aura creation no longer working [dev]

client/src/game/ui/menu/AssetNode.vue
My iterator changes broke the nagivation oops
=> bug(Assets): Fix broken asset navigation in-game [dev]

client/src/game/interfaces/shapes/asset.ts, client/src/game/shapes/variants/asset.ts, client/src/game/ui/tools/VisionTool.vue
Vision tool and asset svgData was nog being collected in a permanent array since the iterator changes.
=> bug(Tech: Iterators): Fix more iterator exhaustion issues

client/src/game/layers/variants/layer.ts
The player side of things was not tested and I forgot one extra condition, woops.
=> bug(Rendering): Fix an oversight in the layer transparency fix

CHANGELOG.md, client/src/assetManager/socket.ts, client/src/assetManager/state.ts, client/src/core/utils.ts, client/src/dashboard/Assets.vue, client/src/game/Game.vue, client/src/game/api/events.ts, client/src/game/interfaces/layer.ts, client/src/game/layers/variants/layer.ts, client/src/game/tools/variants/draw.ts, client/src/game/ui/menu/AssetNode.vue, server/src/api/socket/asset_manager/core.py, server/src/api/socket/asset_manager/ddraft.py
This has been long overdue, but you can now drop assets onto the game itself and they will be uploaded to your root folder in the asset manager.
=> feat(Assets): Add option to add new assets by dropping on the game itself

.github/workflows/docker.yml, CHANGELOG.md, client/src/game/vision/cdt.ts
Another edge-case in the vision code that someone managed to stumble upon :D
=> bug(Vision): Fix edgecase in triangulation creation

CHANGELOG.md, client/src/game/systems/auras/index.ts, client/src/game/systems/properties/index.ts, client/src/game/systems/selected/index.ts, client/src/game/systems/selected/state.ts, client/src/game/tools/variants/map.ts, client/src/game/tools/variants/select/index.ts, client/src/game/tools/variants/spell.ts, client/src/game/ui/SelectionInfo.vue, client/src/game/ui/contextmenu/ShapeContext.vue, client/src/game/ui/settings/shape/ExtraSettings.vue, client/src/game/ui/settings/shape/ShapeSettings.vue, client/src/game/ui/tools/MapTool.vue, client/src/game/ui/tools/SpellTool.vue, client/src/store/activeShape.ts, server/src/export/campaign.py
This PR adds proper state for the selected system.
This makes access to the current focus more ergonomic and consistent with other systems out there.
=> feat(Tech: Selection): Introduce proper state for selected system

client/src/apiTypes.ts, client/src/game/api/events/shape/core.ts, client/src/game/layers/variants/layer.ts, client/src/game/operations/model.ts, client/src/game/operations/undo.ts, client/src/game/shapes/shape.ts, client/src/game/shapes/utils.ts, client/src/game/temp.ts, client/src/game/tools/variants/draw.ts, server/src/api/models/shape/__init__.py, server/src/api/models/shape/shape.py, server/src/api/socket/location.py, server/src/api/socket/shape/__init__.py, server/src/api/socket/shape/access.py, server/src/db/models/shape.py, server/src/models/access.py, server/src/transform/shape.py
As part of the work to support Characters, there is a need for Shapes to be able to exist without being linked to a specific layer.
=> feat(Tech: Shape): Make Shape.Layer optional

client/src/game/layers/variants/layer.ts, client/src/game/shapes/create.ts, client/src/game/shapes/utils.ts, client/src/game/shapes/variants/polygon.ts, client/src/game/temp.ts
I forgot to address one thing I removed in #1292, which this PR fixes :)
=> bug(Shape): Fix shape layer no longer being set

CHANGELOG.md, server/src/api/models/shape/position.py
=> bug(Rotation): Fix shape rotation no longer syncing

CHANGELOG.md, client/src/game/systems/modals/index.ts, client/src/game/systems/modals/state.ts, client/src/game/systems/modals/types.ts, client/src/game/ui/ModalStack.vue
This PR adds support for modals that are inserted on the fly.
=> feat(tech: Modals): Add dynamic modal support

server/requirements-dev.txt, server/requirements.txt, server/src/api/http/__init__.py, server/src/api/http/auth.py, server/src/api/http/rooms.py, server/src/api/http/users.py, server/src/api/socket/asset_manager/core.py, server/src/api/socket/connection.py, server/src/api/socket/dashboard/__init__.py, server/src/api/socket/location.py, server/src/auth.py, server/src/planarserver.py
By upgrading the server dependencies some type issues became apparent with the way I use the various aiohttp_ auth libs.
This PR thus also changes the use of `authorized_userid`, which apparently should always return a string, to instead use a new `get_authorized_user` function that behaves similarly to what the former function used to do.
Also a small set of sio events that were not properly awaited has been fixed.
=> chore: Update server deps & small auth changes

server/src/save.py
After landing notes on dev, 2 people reported problems with upgrading due to shapes that no longer have layer information.
I'm not sure yet how these shapes came to be in that position as it reeks of a bug somewhere,
but I was able to at least fix the upgrade errors.
If a shape without layer information is a character, a note is still created, in all other cases the note will be lost, but the shape is already lost anyway so it's not like we're really missing something here.
=> bug(Notes): Fix migration for layer=None shapes

client/package-lock.json
Something going on with npm (https://github.com/npm/cli/issues/4828)
Doing an `npm upgrade` alledgedly fixes it.
=> chore: npm upgrade

client/src/game/shapes/variants/toggleComposite.ts
Another patch for an issue with variants, but this is mostly a workaround then a proper fix, which as I outlined in the previous PR is postponed for a revamp of the concept.
=> bug(ToggleComposite): Add small patch for toggle composite

server/src/api/socket/note.py
A small bug in the server handling of default access toggling was resolved.
=> bug(Notes): Fix error with changing default note access rights

client/package-lock.json
Somehow forgot to actually run `npm i` when bumping deps yesterday.
=> chore: Fix package-lock

client/src/core/utils.ts, client/src/game/systems/notes/events.ts, client/src/game/ui/notes/NoteEdit.vue, client/src/game/ui/notes/NoteList.vue
- Fallback to gray colour if sha1 is unavailable
- Don't center on shape when removing shape from note
- Fix new shape note spacing issue
- Don't show notification for shape access if you're the author
- Style the 'add shape' button in the note manager shapes tab
=> bug(Notes): Varia small fixes

CHANGELOG.md, client/src/core/components/modals/SelectionBox.vue, client/src/core/plugins/modals/selectionBox.ts
Small QoL improvement for the SelectionBox dialog. It now offers a small action-row when it's in multiselect mode to immediately select all entries or clear them all.
=> feat(SelectionBox): Add clear/select-all options

CHANGELOG.md, client/src/dashboard/games/ImportGame.vue, client/src/dashboard/socket.ts, server/src/api/http/rooms.py, server/src/db/models/label_selection.py, server/src/db/models/shape.py, server/src/export/campaign.py
A couple of recent additions/changes were not updated in the export/import logic.
Datablocks and Characters were for example not exported and the new Note system even caused a crash as it changed multiple fields in existing tables.
Additionally it's now possible to specify the name that the campaign should have after importing instead of always copying the name as it is in the file.
=> bug(Export/Import): Update to recent save file structure changes

CHANGELOG.md, client/src/game/systems/properties/composables.ts, client/src/game/systems/properties/index.ts, client/src/game/systems/properties/state.ts, client/src/game/ui/SelectionInfo.vue, client/src/game/ui/settings/shape/GridSettings.vue, client/src/game/ui/settings/shape/PropertySettings.vue
This is an update to some internals that has no direct effect on the user side of things.
The properties system has been updated to be able to load/lease multiple shapes reactively instead of only the currently selected shape.
=> feat(Properties:Tech): Allow multiple reactive state shapes at once.

client/src/game/dropAsset.ts, client/src/game/interfaces/shape.ts, client/src/game/shapes/create.ts, client/src/game/shapes/index.ts, client/src/game/shapes/shape.ts, client/src/game/shapes/variants/asset.ts, client/src/game/shapes/variants/baseRect.ts, client/src/game/shapes/variants/circle.ts, client/src/game/shapes/variants/circularToken.ts, client/src/game/shapes/variants/line.ts, client/src/game/shapes/variants/polygon.ts, client/src/game/shapes/variants/text.ts, client/src/game/shapes/variants/toggleComposite.ts
Some refactoring work to reduce the heap of imports Shape is doing.
=> chore(Tech: Internals): Move Shape system init out of Shape

client/src/core/biArrMap.ts, client/src/game/shapes/index.ts, client/src/game/shapes/utils.ts, client/src/game/systems/notes/index.ts, client/src/game/systems/notes/state.ts, client/src/game/temp.ts, client/src/game/tools/events.ts, client/src/game/ui/SelectionInfo.vue, client/src/game/ui/contextmenu/ShapeContext.vue, client/src/game/ui/notes/NoteEdit.vue, client/src/game/ui/notes/NoteList.vue, client/src/game/ui/tools/NoteTool.vue
This PR upgrades noteSystem from a regular System to a ShapeSystem. This allows it to interact with shape addition/removal in a more consistent manner allowing some note specific code to be removed from other parts of the codebase.
Additionally this PR also changes the way shape-note relations are stored, which should result in some UI errors to no longer happen during shape removal/addition (e.g. moving between locations).
=> chore(Tech: Notes): Move noteSystem to be a shapeSystem

CHANGELOG.md, client/src/assetManager/AssetContext.vue, client/src/core/components/contextMenu/ContextMenu.vue, client/src/core/components/contextMenu/ContextMenuSection.vue, client/src/core/components/contextMenu/types.ts, client/src/dashboard/Assets.vue, client/src/fa.ts, client/src/game/ui/contextmenu/DefaultContext.vue, client/src/game/ui/contextmenu/ShapeContext.vue
The context menus (right click menus) were pretty ugly. I've done a pass to clean them up a bit :)
=> feat(Style): Update styling of context menus

README.md
Replaced old link for public servers with new link.
=> Update server listing link in README.md

client/src/dashboard/Assets.vue, client/src/game/ui/TrackerInput.vue, client/src/store/lastGameboard.ts, client/vite.config.ts
This adds some improvements to the main game bundle, reducing the initial load size.
- Two imports were not properly treeshaking, causing the full lodash dep to be part of the bundle
- Mathjs is a big dependency only used for the tracker quick modification UI, so is now only loaded if that is opened for the first time
=> chore: Bundle size improvements

CHANGELOG.md, client/src/dashboard/games/CreateSwitcher.vue
=> chore(Dashboard): Change border colours in create new game

CHANGELOG.md, client/src/core/components/WindowPortal.vue, client/src/core/components/modals/Modal.vue, client/src/game/systems/modals/index.ts, client/src/game/systems/modals/state.ts, client/src/game/ui/notes/NoteDialog.vue
Closes #1426
This relies entirely on magic that I'm not sure is 100% intended to be used, so it might break at a certain point, but this is the only way to actually achieve it I believe.
Chances that some things will not work 100% are greater than 0, but basic functionality seems to work.
=> feat(Notes): Add ability to pop-out notes

.github/workflows/pull_request.yaml
The CI setup was becoming a bit of a mess.
This adds deps caching as well as using a matrix to prevent all the duplicate boilerplate code between the common jobs
=> chore(CI): Rework client CI setup

.github/workflows/pull_request.yaml
Don't run client pipeline when only server files were changed and vice-versa
=> chore(CI): Update CI to only run client / server flows when relevant

CHANGELOG.md, client/src/core/components/contextMenu/ContextMenuSection.vue
=> bug(ContextMenu): Fix Shape context menu not closing when choosing an action

server/src/planarserver.py
With the config rework, the api server code was not properly updated and was re-using the main webserver connection config causing port clashes.
=> bug(Apiserver): Fix apiserver startup with new config

server/pyproject.toml, server/uv.lock
ruff formatting handles isort as well.
=> chore(formatting): Drop isort

.circleci/config.yml, CHANGELOG.md, client/package-lock.json, client/package.json, client/src/game/systems/access/index.ts, client/src/game/systems/access/state.ts, client/src/game/tools/variants/select/index.ts, client/src/game/ui/initiative/Initiative.vue, client/test/game/systems/access/index.test.ts, server/VERSION, server/pyproject.toml, server/uv.lock
This is a fix release that tackles the following issues:
-   Initiative effect rename losing focus after pressing 1 character
-   Locked shapes not being selectable directly
-   DM only auras where no longer rendered due to a bug in the new access logic
=> release: 2025.2.2

.github/workflows/pull_request.yaml, Dockerfile, client/package-lock.json, client/package.json, client/src/game/api/emits/shape/core.ts
Small dep changes. Changes the CI and docker file to run against node 24 instead of 22
=> chore(deps): Upgrade deps + node 24 base

CHANGELOG.md, client/src/admin/Users.vue, server/src/api/http/auth.py, server/src/api/socket/admin/__init__.py, server/src/db/models/user.py, server/src/save.py
This is a simple field on the User table that will be set to the current day (not time). It is listed in the admin dashboard.
=> feat(Admin): Track last login day per user

client/src/game/systems/customData/index.ts
Last minute changes and forgetting to double check behaviour, name a more iconic duo.
=> bug(CustomData): Fix silly pending branch name check
